### ISSUE TITLE
Typing indicator issues.

### ISSUE THREAD

**Issue by WX4300** [oxen-io/session-android#1000]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The typing indicator is delayed and shows me and others typing even if a message has been erased or sent. Closing the keyboard doesnt make it disappear either.

-> Suggestion: typing indicator disappears if keyboard has been closed

**To reproduce**

Steps to reproduce the behavior: As above

**Screenshots or logs**
xxxx

**Smartphone (please complete the following information):**

 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 12.1
 - Version of Session: 1.15.4 (3035)

**Additional context**
xxxx

**Comment by KeeJef** [comment]
Is this still occurring? i believe 1.16.5 has a fix for this
