### ISSUE TITLE
Ocean Light is Ocean Dark

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#1006]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

Just wanted to say good job on the update devs, keep up the amazing work you peeps are doing for the privacy community :)

**Describe the bug**

**To reproduce**

Select the "Oceon Light option in appearance settings.

**Screenshots or logs**

![Screenshot_Session_1](https://user-images.githubusercontent.com/57234536/195302082-70168fe6-7ce2-4029-b2c9-d029d9e133b4.jpg)

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Galaxy S10
 - OS: Android 13
 - Version of Session or latest commit hash: 1.16.0

**Additional context**

Even after restarting the app the issue still persists.

**Comment by ianmacd** [comment]
> Even after restarting the app the issue still persists.

Disable __Match System Settings__.

I do feel that the interface doesn't make clear why the light themes appear not to work properly when selecting them.

**Comment by Flam3z** [comment]
Ah ok, that seemed to work, thx for the clarification.

**Comment by GameOverFlowChart** [comment]
> > Even after restarting the app the issue still persists.
> 
> Disable **Match System Settings**.
> 
> I do feel that the interface doesn't make clear why the light themes appear not to work properly when selecting them.

The "match system settings" buttons needs to be moved to the top. Also than its enabled than we should just have the choice between classic and ocean and if they are showed as dark or light in the menue should depend on the actual system setting. Disabling the match function should split the options into their dark and light modes.
