### ISSUE TITLE
(Feature Request) Enhanced App Security

### ISSUE THREAD

**Issue by session11** [oxen-io/session-android#1007]
I feel that Session  should implement other locking methods apart from the default one. The app should provide an inbuilt option to use PIN or PATTERN.  Besides, in case of intruder attempt, we need something like PANIC MODE, where SESSION simply wipes itself after the predefined number of unsuccessful attempts. I strongly believe that this will make Session even more private and secure.

**Comment by KeeJef** [comment]
Closing as a duplicate of #424 and #914
