### ISSUE TITLE
Notifications on Graphene OS

### ISSUE THREAD

**Issue by AndrewNow2** [oxen-io/session-android#1016]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Hi
The problem is that on my device, notifications come to me 20 minutes after the SMS.
For example, someone sent me an SMS, my application is closed, and I will receive a notification in exactly 20 minutes, (not earlier, not later), how can I fix this?

**Smartphone (please complete the following information):**

 - Device: Google Pixel 3a
 - OS: Graphene OS
 - Version of Session or latest commit hash: V 1.16.0(3095)

**Comment by KeeJef** [comment]
Closing for #169 and #924
