### ISSUE TITLE
Replying to a message with an audio file does not work on Android

### ISSUE THREAD

**Issue by RetroAbstract** [oxen-io/session-android#1021]
**Describe the bug**
Replying to a message on Android with an audio file results in the audio message being sent as if it weren't replying to a message.

**To Reproduce**

1) Press and hold a message
2) Press "Reply"
3) Select an audio file to reply with
4) Notice the audio message is sent with no reference to the message you wanted to reply to

**Screenshots or Logs**

![5](https://user-images.githubusercontent.com/103272301/197339928-c5c1519c-6c37-4170-bd3a-92a8d457f00f.png)

**Smartphone (please complete the following information):**

 - Device: Irrelevant as bug happens on 2 different phones from 2 different brands
 - OS: LineageOS
 - Version of Session or latest commit hash: 1.16.0

**Additional context**

This bug is identical to the one I submitted in the desktop version of Session.

**Related additional bug: when replying to a message with an audio file from the desktop version, even if the audio message sent does not refer to the message it's replying to on desktop, it does on android. However, the audio reply is overlayed with the message it's replying to, resulting in the audio message being played when pressing it and also Session going to the message the audio file is replying to when it should be the message being replied to should be above the audio message reply, not overlayed.**

Screenshot of additional bug [#1022](https://github.com/oxen-io/session-android/issues/1022):

![4](https://user-images.githubusercontent.com/103272301/197339716-0841051d-aadf-46da-b9db-2e4ac0f29e65.jpg)

**Comment by bemusementpark** [comment]
https://github.com/oxen-io/session-android/pull/1278
