### ISSUE TITLE
Audio message reply overlayed with text/image message it's replying to when sent from desktop

### ISSUE THREAD

**Issue by RetroAbstract** [oxen-io/session-android#1022]
**Describe the bug**

When replying to a text or image message **on desktop** with an audio file, the audio message reply will be overlayed with the original message it's replying to on android.

**To reproduce**

1) Right click on a message
2) Click "Reply to message"
3) Select an audio file to reply with
4) Send
5) Open Session on android
6) Notice your reply is overlayed with the message you're replying to, resulting in the audio message being played when pressing it and also Session going to the message the audio file is replying to when it should be the message being replied to should be above the audio message reply, not overlayed

**Screenshots or logs**

![4](https://user-images.githubusercontent.com/103272301/197340390-ea9d2f7d-a6ed-4d99-a248-07d0126bbc33.jpg)

**Smartphone (please complete the following information):**

 - Device: Irrelevant as bug happens on 2 different phones from 2 different brands
 - OS: LineageOS
 - Version of Session or latest commit hash: 1.16.0

**Additional context**

**This happens exclusively when replying from desktop and using Session on android.** This bug is related to the other bug I submitted that affects both desktop & Android versions of Session [#1021](https://github.com/oxen-io/session-android/issues/1021) & [#2573](https://github.com/oxen-io/session-desktop/issues/2573).

**Comment by bemusementpark** [comment]
https://github.com/oxen-io/session-android/pull/1278
