### ISSUE TITLE
Chat bubbles sensitive to touch outside the bubble

### ISSUE THREAD

**Issue by GameOverFlowChart** [oxen-io/session-android#1023]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The chat bubbles are to sensitive. They get selected even if you rest your finger outside the bubble at the same vertical hight as the message.

**To reproduce**

Open a conversation. Press your finger at the right of a text bubble from a conversation partner that is not you. The message will be selected.

**Screenshots or logs**

Nope

**Smartphone (please complete the following information):**

 - Device: private information
 - OS: Android 12
 - Version of Session or latest commit hash: 1.16.0

**Additional context**

Nothing

**Comment by KeeJef** [comment]
This is intentional so that its easier to select messages

**Comment by GameOverFlowChart** [comment]
Well that's weird because sometimes directly longpressing on a message from your chatpartner doesn't select it but thanks to this intended feature scrolling through text is sometimes a pain.
