### ISSUE TITLE
Contacts sync/backup

### ISSUE THREAD

**Issue by xznhj8129** [oxen-io/session-android#1024]
Every time Session has to be installed or reinstalled for an update (conflicting versions sometimes), _every single contact_ has to be re-added manually, the name assigned, a new message sent. This is maddening. Please let there be some way to backup your contacts list and recovery phrase to a file, encrypted with a password obviously, so you can sync new devices painlessly. This is a serious problem, yes i have my recovery phrase but if i don't have a way to sync contacts from my old device because i don't have access to it, it is as useless as a completely new address.

**Comment by KeeJef** [comment]
Your contacts should actually be restored automatically if you restore from seed within 14 days of using your old device, was that not occurring for you? or were you trying to restore after 14 days of not using Session on any device?

**Comment by KeeJef** [comment]
Closed due to lack of info, please reopen if still happening
