### ISSUE TITLE
File attachments - size, format, reliability

### ISSUE THREAD

**Issue by gitbq** [oxen-io/session-android#1030]
Please allow attachments of ANY file format, of up 50MB or if possible 100MB to be attached to any message, and reliably arrive at destination 

While the size of the attachment is important, more importantly it needs to reliably send files of the stated size. Currently this does not happen. 

I would rather know that files of up to 20MB could be attached and sent 100% of the time, rather than having the option of sending 100MB attachments that only work 10% of the time.

**Comment by no149** [comment]
PLease read the whitepaper, section 5.3: 
https://arxiv.org/pdf/2002.04609.pdf
