### ISSUE TITLE
Introduce SMS support

### ISSUE THREAD

**Issue by Sn0whax** [oxen-io/session-android#1034]
With signal backing out of supporting SMS (All in 1 app) this allows for session to be the "one stop shop" as a private message app/imessage killer for everyone. 
Having this (at least as an option) has the potential to attract several new users. I believe having SMS as an option + No required phone number sign-up can appeal to the masses.
Please consider adopting this, it would make it a lot easier to migrate a lot of my personal contacts over as well.

Thanks!

**Comment by KeeJef** [comment]
Closing this for now, as i don't see Session moving towards using phone numbers any time soon

**Comment by octoshrimpy** [comment]
session would not need to use phone numbers for anything, just use the local device's sms db and maybe sync the db across to other devices.
