### ISSUE TITLE
Attachments deleted for everyone using Android still present on Linux

### ISSUE THREAD

**Issue by WX4300** [oxen-io/session-android#1035]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Attachments deleted for everyone using Android are still present on Linux

**To reproduce**

1. Delete a picture or file (for Everyone) on Android
2. Check on Linux if the file / picture is still present
3. The picture / file is still present

**Screenshots or logs**

xxxx

**Smartphone (please complete the following information):**

- Device: Xiaomi Redmi Note 8 Pro
- OS: Android 12.1
- Version of Session: 1.16.1 (3105)

**Comment by 825i** [comment]
How is this a bug? Messages deleted on Session are only ever deleted for the sender and not for the receiver.

**Comment by hjubb** [comment]
This might be a bug to raise in the session-desktop repository, as it sounds like the behaviour for the android app is working fine? Try raising it there https://github.com/oxen-io/session-desktop
