### ISSUE TITLE
Android 11 bug, F-Droid Repo

### ISSUE THREAD

**Issue by oxenreport** [oxen-io/session-android#1043]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

Message sent from one party in community was listed as a sent message from owner of the Android device, crossover recipient/sender issue. F-Droid repository, Android 11, Kernel v. 4+

**Comment by KeeJef** [comment]
I don't think this issue has enough context for me to understand what the actual issue is, please reopen with additional information if you have
