### ISSUE TITLE
Session doesn't auto reconnect on internet established

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#1048]
### Bug description
When reconnecting to the internet, or switching networks between data and wifi, Session doesn't reconnect to the network immediately. It will reconnect after several minutes, perhaps a half hour.

### Steps to reproduce
- Disconnect and reconnect to the internet

No messages come in. Network indicator icon Session shows disconnected.

**Expected result:**
When connecting to the internet in previous versions of Session, it would reconnect to the Loki network within about a minute. I have not upgraded nor made system changes to my device.

**Thoughts**
Perhaps this is a result of some change to make the client more battery efficient?

### Device info
**Device:** OnePlus 6
**Android version:** 10
**Session version:** 1.15.2

**Comment by hjubb** [comment]
perhaps this is the result of some kind of exponential backoff in the poller, might be a matter of just capping the max time to be a minute or two instead of whatever it sounds like it is. Is the behaviour any better on the later versions (1.16.x)?

**Comment by Sepero** [comment]
I've been trying to monitor this. Sometimes it reconnects immediately after internet is re-established. Other times it doesn't seem to reconnect after several minutes, then I swipe it out of recents, reopen Session and it will connect.

**Comment by hjubb** [comment]
Ah ok, it sounds like maybe capping the max retry time to be shorter might fix this issue. I'll try to get that added in

**Comment by Sepero** [comment]
Seems to be resolved with the latest update

**Comment by x80486** [comment]
Probably a candidate to be closed then :eyes:
