### ISSUE TITLE
Attachment size - help FAQ and support articles different

### ISSUE THREAD

**Issue by gitbq** [oxen-io/session-android#1055]
getsession.org homepage under "messaging" states attachment limit is 10mb.

Help - getsessionapp.zendesk.com - "can I share attachments..." 
Here states the limit is 6mb.

Preferred behaviour:
Same data in both places.

**Comment by KeeJef** [comment]
This one is a little tricky, we made some changes to the onion request protocol a few months ago which actually let us hit near to our 10mb onion request limit. The previous issue was that data sent through onion requests was b64 encoded which would add significant overhead to the total payload being sent, which meant that the actual file size which could be uploaded was more like 6mb. 

We should do an update in the new year which will update the limits we previously had set and bring the true file size upload limit to 10mb

Either way we will need to update the articles when this change goes live

**Comment by gitbq** [comment]
After spending time to test this out on both Android and ios, it seems anything 6mb or less is guaranteed to send regardless of the file type. In the past it is possible I have managed to send a larger file, and vaguely remembering  about the 10mb thing made me think that this was in fact possible.
The homepage seems to be the first page people might look. Would it be possible to state with clarity (1) what features currently do work reliably and (2) what features MAY work, but not reliably?

For example... " files of up to 6mb in any format can be sent. It is possible that files of up to 10mb may sometimes be sent, but this is a little inconsistent depending on..."
No doubt someone can come up with better wording...

For me this kind of thing is a real barrier for adoption. 
But as soon as a new user reads that "files of 10mb can be sent" , but then it doesn't actually work,  it causes users to lose confidence in the software reliability. But in actual fact anything less than 6mb works great.

**Comment by KeeJef** [comment]
This has been fixed in 1.16.5 Session now supports attachments up to 10mb
