### ISSUE TITLE
Android (Device Care) reporting Session excessive crash and battery drain.

### ISSUE THREAD

**Issue by Samillion** [oxen-io/session-android#1064]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Recently I've been getting reports on my Samsung A52s of Session crashing a lot and causing a battery drain, it is suggesting to put the app in deep sleep.

I've tried uninstalling the app completely and re-installing again, then waiting a week but same reports show up.

**To reproduce**

As far as I'm aware, just use the app on an Android device that is capable of producing usage and crash reports.

**Screenshot and log**

[samsung-a52sxq-API33-v1.16.1-1672777599634.txt](https://github.com/oxen-io/session-android/files/10339597/samsung-a52sxq-API33-v1.16.1-1672777599634.txt)

![photo_2023-01-03_21-23-58](https://user-images.githubusercontent.com/17427046/210435496-d966605e-498a-4c11-9daa-7667ba6b70ef.jpg)

**Smartphone (please complete the following information):**

 - Device: Samsung A52s
 - OS: Android 13
 - Session: 1.16.1 (3105)

**Additional Context:**
My use case scenario is basic, nothing excessive, as there aren't many people I know using Session (hopefully that will change soon).

**Comment by SzBenedek2006** [comment]
I have the same issue on a52 5g

**Comment by Samillion** [comment]
> We have fixed a number of common crashes in 1.16.5, can you check on this over the next few weeks and see if this is resolved, otherwise this might be battery related, which notification strategy did you choose, Fast mode or Slow mode?

Thank you very much for your efforts. Notifications are set to Fast mode.

I'll keep you posted once I get the update on Playstore and after 3 weeks usage.

To be objective in my report, the device's battery is functioning normal. If you would like, I can include a full battery report when I come back and post in 3 weeks.
