### ISSUE TITLE
Video call auto rotates, when auto rotate is disabled

### ISSUE THREAD

**Issue by WardPearce** [oxen-io/session-android#1085]
**Code of conduct**

-  [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Disabling auto rotate in my settings, doesn't disable auto rotate in video calls.

**To reproduce**

Disable auto rotate, start a video call. Tilt your device slightly making it unusable.

**Smartphone (please complete the following information):**

- Device: Google Pixel 6, Samsung Flip & other devices of friends.
 - OS: Android 
 - 1.16.3

**Comment by hjubb** [comment]
This one we can probably add some system specific check for whether auto-rotate is enabled (not sure if it exists or what it's called off the top of my head) in the `onCreate` of the `WebRtcCallActivity` and if it is enabled only then call `rotationListener.enable()`, same for the `disable()` call in `onDestroy` maybe?

**Comment by rugveddarwhekar** [comment]
@hjubb  Please check my attempt at fixing this: [PR](https://github.com/oxen-io/session-android/pull/1352)

**Comment by ThomasSession** [comment]
Thanks for the PR. We merged in the changes and they will be made in the next available app update coming out soon.
