### ISSUE TITLE
Session Android works on emulator but hangs on startup when testing on browserstack real devices

### ISSUE THREAD

**Issue by fracting** [oxen-io/session-android#1106]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Fresh installed Session hangs for a long time (forever?) on startup when testing with browserstack real devices.

The attached video shows for 20 seconds, I waited for more than one minute and gave up.

I tested on Android Emulator and it seems working fine.

**To reproduce**

Fresh installed Session, click Session launch icon to start. A black screen showed up for a long time until I gave up and kill the app. 

**Screenshots or logs**

https://user-images.githubusercontent.com/194342/217408965-1c54aec3-6092-4a53-beb1-09dfd8b41d33.mp4

**Smartphone (please complete the following information):**

 - Device: [Pixel 7 from BrowserStack | OnePlus 6T from BrowserStack] ( https://app-live.browserstack.com/ provides real devices with remote access )
 Update: as well as Pixel 7 Pro from BrowserStack. Potentially any devices from BrowserStack.
 - OS: [e.g. Android 13.0]
 - Version of Session or latest commit hash: Session 1.16.5
 [Edited] APK downloaded from https://github.com/oxen-io/session-android/releases/download/1.16.5/session-1.16.5-universal.apk

**Additional context**

There's user reporting Session extremely slow on OnePlus 3T and OnePlus One, I don't have those devices so I tested on devices from browserstack instead.

Update: See https://github.com/oxen-io/session-android/issues/1003 for performance issue on OnePlus 3T and OnePlus One, looks like a different issue.

**Comment by ianmacd** [comment]
> **Smartphone (please complete the following information):**
> 
> * Device: [Pixel 7 | OnePlus 6T] ( https://app-live.browserstack.com/ provides real devices with remote access )
> * OS: [e.g. Android 13.0]

My main device is a Pixel 7 Pro, so almost the same device as the plain 7, and I have no start-up issue with Session.

**Comment by fracting** [comment]
> My main device is a Pixel 7 Pro, so almost the same device as the plain 7, and I have no start-up issue with Session.

Thanks, that's really valuable information. 

I just tested Pixel 7 Pro from BrowserStack and it hangs for me as well.

There must be something important I don't understand, we might end up concluding it's a BrowserStack bug, in that case, I'll report to BrowserStack instead.

Session Android on BrowserStack never worked for me no matter what devices I selected, it never worked since the first time I tested BrowserStack a few months ago, I hesitated to report Session + BrowserStack issues because I thought it might be BrowserStack's problem, until I heard someone reported they there Session Android is very very slow.

**Comment by hjubb** [comment]
@fracting Is this running the production APK or being built from source somewhere? I'm not sure if the screen privacy settings might be causing it to not see anything from the app in that case? There is a flag specific for UI testing that will disable the default screen protection on first launch if running the app from the debug build flavour. If you can't build it I can probably give you an APK built that way to test if that is the issue

**Comment by fracting** [comment]
> @fracting Is this running the production APK or being built from source somewhere? I'm not sure if the screen privacy settings might be causing it to not see anything from the app in that case? There is a flag specific for UI testing that will disable the default screen protection on first launch if running the app from the debug build flavour. If you can't build it I can probably give you an APK built that way to test if that is the issue

It was a official production APK downloaded from https://github.com/oxen-io/session-android/releases/download/1.16.5/session-1.16.5-universal.apk

(BrowserStack supports upload apk or provide URL to apk)

**Comment by hjubb** [comment]
Looks like the screen privacy flag is the thing that is triggering this, I just tested the release version and experienced the same issue you are facing, then the debug version I built locally off master, the debug build seems to be the only one that allows the UI to display as expected

**Comment by fracting** [comment]
Is there anything we can/should do on the Session side, or should I contact BrowserStack support and report an issue to them? I'm not talking about a quick workaround bug more thinking about a proper long-term solution. I don't have enough knowledge about privacy flags so I can't judge by myself.

**Comment by hjubb** [comment]
I don't think it is necessarily an issue, it seems that the screen privacy is working as intended :smile: but maybe the documentation can be expanded upon to include notes about testing with devices and the screen privacy, although most people would be building against a debug / dev signed version on their local machines anyway. Adding something to the `README.md` about trying to run automated tests against the release APKs indicating that there may be issues due to the screen privacy default settings might be enough, and pointing someone to the `BUILDING.md` instructions (as well as making sure those are easy enough to follow I guess)

**Comment by fracting** [comment]
I contacted BrowserStack support and they are very fast, very friendly, very professional, very helpful:

> Please allow me to explain:
> At BrowserStack we use a custom streaming technology to stream video content from the remote devices hosted in our data centers to your local browser. Screen capture capabilities/permissions are essential to facilitate this video stream. Thus, our system apps need access to the screen of the app under test so that we can provide streaming of the device screen, and thereby allow the user to interact with the app.
> 
> Since the application restricts screen capture, you encounter the reported behavior.  With that said, I want to inform you that we have recently added support for testing Android apps that block Screen Capture. This feature is in private beta at the moment and I can get it enabled for your account. 
> 
> There are a few caveats we would like to share before we enable this for you provided you would like to proceed with this.
> 
> Caveats:
> 1. This would not work for apps uploaded directly via Playstore and you will have to manually upload the app to test it on Browserstack.
> 2. This workaround is in beta and might cause a high session start, app launch, and app install time.
> 3. Enabling this feature for the entire group is highly discouraged as this would degrade the session experience for all apps, so we recommend enabling it for select users.
> 
> Preconditions for the feature to work:
> 1. The app should be a native app (Xamarin framework apps are known to not work)
> 2. The app relies on FLAG_SECURE to block screenshots.
> 3. The app does not have any encryption which detects any code change in the app
> 4. The user has the app and can upload the app on BrowserStack for testing. (Manual app upload)
> 5. The app size should be < 130 Mb, if the app is larger our workaround will not work and the session will start with the original user app, hence the screenshot/screen capture will be blocked.
>  
> Another workaround would be to get this checked with your development team and get this screen capture security flag disabled in order to continue testing it on BrowserStack.

**Comment by hjubb** [comment]
Yep so you could use the debug version of the APK which would not have the screen capture security flag enabled. Just a matter of either building it locally or integrating some other process to get the non-release versions of the APK

**Comment by fracting** [comment]
Make sense, thanks @hjubb! Not a Session Android bug, close issue.

**Comment by fracting** [comment]
Update: the beta feature of disabling screenshot block from BrowserStack works for me. I guess they implemented some magic to binary patching the Android APK uploaded by the user and disabled the screenshot block flag.
