### ISSUE TITLE
Visual clarity: contrast of message selection is extremely low

### ISSUE THREAD

**Issue by fracting** [oxen-io/session-android#1110]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Selected messages have a low contrast compared to unselected messages, making them hard to distinguish.

**To reproduce**

Fresh install Session Android, default theme, and select some messages.

In the below example, "Hi this is Alice" is selected, "Hi this is Carol" and "Hi this is Bob" are unselected, they look very closely.

The selected messages have a very closed color / darkness compared to unselected messages.
This makes a moderator's life harder because they often need to delete messages in bulk.

**Screenshots or logs**

<img width="349" alt="Screen Shot 2023-02-09 at 5 27 51 am" src="https://user-images.githubusercontent.com/194342/217619674-353b43fb-852b-4aa0-b8e2-267153293a1d.png">

**Smartphone (please complete the following information):**

 - Device: [Android Emulator Pixel 6]
 - OS: [e.g. Android 13.0]
 - Version of Session or latest commit hash: [Session 1.16.5]

**Additional context**

There are users reporting the message selection visual clarity issue was fixed in some earlier version, but then came back again after theming support was implemented. In other words, it might be a visual regression.

However, on 1.16.3 release note there was

> "Make selected message colours more visible, fix classic dark read indicator by @0x330a in #1031"

So this could be a disagreement on the sense of visibility as well. At least to me the selected message is not very different to unselected messages.

In any case, visual regression testing is tricky itself. According to [1], "This can result in tens or even hundreds of thousands of potential screens to test".
We might want to investigate specialized testing frameworks for visual regression like [2].

[1] https://applitools.com/blog/visual-ai/
[2] https://percy.io/

**Comment by fracting** [comment]
Me:

> Session is a chat application. There is a visual clarity issue in the message selection feature in a conversation. When a message is selected, its color is too closed to unselected color, making them hard to distinguish. Please suggest some reading material, guidelines, books, articles, examples, tutorials, best practice etc, for designing color schemes of "message selection" feature

ChatGPT:

> Designing effective color schemes for the message selection feature in a chat application is an important aspect of user experience design. Here are some resources that you may find helpful:
>
> 1. Color Theory: A basic understanding of color theory can be helpful in designing color schemes for user interfaces. You may find the following books and articles useful:
> 
>    * "The Elements of Color" by Johannes Itten
>    * "Color Index" by Jim Krause
>    * "The Psychology of Color in Marketing and Branding" by Singh, K. (2018).
> 2. Design Guidelines: Guidelines and best practices for designing color schemes in user interfaces can be found in the following resources:
> 
>    * Material Design Guidelines by Google: https://material.io/design/color/
>    * iOS Human Interface Guidelines by Apple: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/
> 3. Accessibility: Ensuring that the color scheme is accessible to users with visual impairments is important. You may find the following resources helpful:
>
>    * Web Content Accessibility Guidelines (WCAG) 2.1: https://www.w3.org/WAI/standards-guidelines/wcag/
>    * A11y Color Contrast Checker: https://www.accessibility-checker.com/contrast-checker/
>    * Color Palettes: There are many tools and resources available for finding and creating color palettes for user interfaces. Some popular resources are:
>
> 4. Adobe Color: https://color.adobe.com/
>    * Coolors: https://coolors.co/
>    * Palette Generator: https://palettegenerator.dev/
>    * Case Studies: Studying real-world examples of effective color schemes in chat applications can be a helpful learning experience. You can find such examples by searching for chat application designs on design showcase websites such as Dribbble or Behance.
> 
> By using a combination of these resources, you can gain a better understanding of how to design effective color schemes for the message selection feature in your chat application.

**Comment by fracting** [comment]
According to https://pickcoloronline.com/

The selected message background color is `#1b1c1b`
The unselected message background color is `#111111`

According to https://color.a11y.com/ContrastPair/?bgcolor=1b1c1b&fgcolor=111111

The above pair of colors failed all contrast tests:

<img width="901" alt="Screen Shot 2023-02-09 at 8 40 16 am" src="https://user-images.githubusercontent.com/194342/217657405-2019c5f4-e08b-4815-a140-fd094f525ef6.png">

**Comment by hjubb** [comment]
It is simple enough to change these values, documenting it here in case anyone gets to it first or if someone wants to experiment with values to see what would look best:

In the `app/src/main/res/values/themes.xml` there are four items (one for each theme variant)
```
    ...
    <item name="message_selected">#VALUE#</item>
    ...
```

which currently reference the appropriate palette i.e. the ocean dark variant references `@color/ocean_dark_1` etc, changing these to either a different shade of that palette like `@color/[theme]_[variant]_[0-6]` so there's appropriate contrast would fix the issue, alternatively if none of those colours look good we could just use a different colour that fits with the rest of the overall theme

**Comment by fracting** [comment]
Here is the old color scheme:

| Theme         | colorPrimary    | message_received_background_color | message_selected |
|---------------|-----------------|-----------------------------------|------------------|
| Classic.Dark  | classic_dark_0  | classic_dark_2                    | classic_dark_1   |
| Classic.Light | classic_light_6 | classic_light_4                   | classic_light_5  |
| Ocean.Dark    | ocean_dark_2    | ocean_dark_4                      | ocean_dark_1     |
| Ocean.Light   | ocean_light_7   | ocean_light_4                     | ocean_light_6    |

|    |   |
|----|----|
|    <img width="314" alt="classic-dark-before" src="https://user-images.githubusercontent.com/194342/218187130-c0eb1c82-d316-495a-9ed6-85c6cfe21995.png">    |    <img width="310" alt="class-light-before" src="https://user-images.githubusercontent.com/194342/218187427-202471ce-9193-46f2-a09b-8031d9656d01.png">    |
|    <img width="309" alt="ocean-dark-before" src="https://user-images.githubusercontent.com/194342/218187489-f6b6e4cb-4509-448f-9e97-798f16bc9936.png">    |    <img width="308" alt="ocean-light-before" src="https://user-images.githubusercontent.com/194342/218187627-b05f6ce3-fd99-4adb-8979-9b29b8e59dfe.png">    |

**Comment by fracting** [comment]
I did some tweaks and came up with a new scheme, shifted `message_selected` farther away from `colorPrimary` while preventing collision with `message_received_background_color`:

* Classic.Dark:  (classic_dark_0, classic_dark_1) -> (classic_dark_0, classic_dark_3)
* Classic.Light: (classic_light_6, classic_light_5) -> (classic_light_6, classic_light_3)
* Ocean.Dark: In theory, I should do the same change but I didn't because it seems good enough already
* Ocean.Light: (ocean_light_7, ocean_light_6) -> (ocean_light_7, ocean_light_5)

So here is the new scheme:

| Theme         | colorPrimary    | message_received_background_color | message_selected |
|---------------|-----------------|-----------------------------------|------------------|
| Classic.Dark  | classic_dark_0  | classic_dark_2                    | classic_dark_3   |
| Classic.Light | classic_light_6 | classic_light_4                   | classic_light_3  |
| Ocean.Dark    | ocean_dark_2    | ocean_dark_4                      | ocean_dark_1     |
| Ocean.Light   | ocean_light_7   | ocean_light_4                     | ocean_light_5    |

|    |    |
|----|----|
|    <img width="314" alt="class-dark-after" src="https://user-images.githubusercontent.com/194342/218188974-c87758c8-3539-428e-9be6-fcd192cb6d61.png">    |    <img width="308" alt="classic-light-after" src="https://user-images.githubusercontent.com/194342/218188984-11add133-ae16-46a3-940b-3b08f0cd674b.png">    |
|    <img width="315" alt="ocean-dark-after" src="https://user-images.githubusercontent.com/194342/218188987-66aac6f8-f401-4f59-b712-e40231bfaa96.png">    |    <img width="306" alt="ocean-light-after" src="https://user-images.githubusercontent.com/194342/218188990-e36a6e7d-6d42-4813-8eb6-e9e757de46f4.png">    |

**Comment by fracting** [comment]
**Plan B**

* Classic.Dark | Classic.Light:
   * swap message_selected and message_received_background_color in Plan A, looks less aggressive
* Ocean.Dark | Ocean.Light:
   * same as Plan A


| Theme         | colorPrimary    | message_received_background_color | message_selected |
|---------------|-----------------|-----------------------------------|------------------|
| Classic.Dark  | classic_dark_0  | classic_dark_3                    | classic_dark_2   |
| Classic.Light | classic_light_6 | classic_light_3                   | classic_light_4  |
| Ocean.Dark    | ocean_dark_2    | ocean_dark_4                      | ocean_dark_1     |
| Ocean.Light   | ocean_light_7   | ocean_light_4                     | ocean_light_5    |

|    |    |
|----|----|
|    <img width="316" alt="classic-dark-plan-b" src="https://user-images.githubusercontent.com/194342/218195089-4aee52f2-3623-47c5-9173-a94a1aeeaf18.png">    |    <img width="307" alt="classic-light-plan-b" src="https://user-images.githubusercontent.com/194342/218195094-c18ee26e-b6cf-46d6-bb0b-f9cddebd1a98.png">    |
|    <img width="315" alt="ocean-dark-after" src="https://user-images.githubusercontent.com/194342/218188987-66aac6f8-f401-4f59-b712-e40231bfaa96.png">    |    <img width="306" alt="ocean-light-after" src="https://user-images.githubusercontent.com/194342/218188990-e36a6e7d-6d42-4813-8eb6-e9e757de46f4.png">    |

**Comment by fracting** [comment]
I submitted two pull requests, will close one of them based on feedback, feel free to comment / vote.

**Comment by KeeJef** [comment]
On first glance Plan B looks better to my eye. but I will raise this with our Graphics and UX and let you know what they think

**Comment by KeeJef** [comment]
Yeah team agrees on plan B
