### ISSUE TITLE
[Proposal] Mail on Session

### ISSUE THREAD

**Issue by serrq** [oxen-io/session-android#1121]
Pay attention: I don't told 'email'.

I want deliberately stay out standard.

I would like a boxed message system (with attachments) in email style (non-instant messages, no read recipes) with fixed limits like 6000 characters, subject, mail forwarding, smart labels, etc.

All this with only a Session ID. So DNS based nicknames are not necessarily needed (optionally you might have them).

To differentiate this new mail system from the more widespread e-mail (stands for electronic mail) we could call this alternative standard d-mail (stands for digital mail) or s-mail (session mail).

**Comment by KeeJef** [comment]
This isn't really our current focus at Session, we are focusing on instant messaging, might be a more suitable request for a new application on top of the Service Node network though
