### ISSUE TITLE
[Bug] Loading Session takes at least 15-20 sec after opening it the first time

### ISSUE THREAD

**Issue by breaking-loss** [oxen-io/session-android#1161]
**Code of conduct**

- [ √] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
Session loads up fast on the first try after reboot but from the second try onwards it takes 15-20 sec to load the main page .

**To reproduce**

1. Download session from izzydroid repo
2. Register
3. Close the app
4. Try to access it again

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [Redmi 6 pro]
 - OS: [Corvus Os (unofficial) Android 13]
 - 1.16.7

**Additional context**

**Comment by KeeJef** [comment]
Is this still occurring on the latest version 1.17.0? We have made some improvements to startup time

**Comment by breaking-loss** [comment]
> Is this still occurring on the latest version 1.17.0? We have made some improvements to startup time

My bad the issue is fixed in the newer version . I forgot to close the issue .
