### ISSUE TITLE
Recovery Phrase Cannot Finish

### ISSUE THREAD

**Issue by retsuakiko-sg** [oxen-io/session-android#1190]
Hi. I met this issue. Judging from the logs, it might be the problem with populating snode pool.

Such as:

```
<time> D Loki: Populating snode pool using: https://seed2.getsession.org:4443.

<time> D Loki: POST request to https://seed2.getsession.org:4443/json_rpc failed due to error: timeout.
```

I tried to visit the URL`seed2.getsession.org:4443` then got an warning "NET::ERR_CERT_AUTHORITY_INVALID". It seemed to be caused by HSTS failure.

Could u pls fix it soon? Thx! I had added the same content in #1147 but received no response. Therefore I open this issue.

**Comment by retsuakiko-sg** [comment]
Also I noticed the PR #1144 which might cause this issue. Pls check!

**Comment by hjubb** [comment]
I'll see if there's some server config messing with this, but I think the certificates themselves shouldn't be an issue. I'll let you know

**Comment by hjubb** [comment]
the hsts issue in browser I'd imagine is unrelated, and the timeout might just be some other reason for failure, like somewhere lower when the request is sent it just times out, could also be censorship or something else depending on the network / country that is making the request

**Comment by retsuakiko-sg** [comment]
> the hsts issue in browser I'd imagine is unrelated, and the timeout might just be some other reason for failure, like somewhere lower when the request is sent it just times out, could also be censorship or something else depending on the network / country that is making the request

Thank u. However, I'm **living in Singapore** where seldom takes network censorship measure(s). In addition, I tried several Wi-Fi access point and cellular. **None of them works.** I'll make more attempt and let u know results. Thx again!

**Comment by retsuakiko-sg** [comment]
Solved. I used a Cloudflare Warp proxy to succeed.

By the way, do you use specfied certificates on both the snode servers and Session clients in order to ensure that only can Session clients obtain snodes' info from the servers?

**Comment by hjubb** [comment]
the snode info isn't only for session clients, it is also for other service nodes and oxen wallets if they want to, possibly also lokinet but I'm not sure. the certificates are to verify a client is talking to who they think they are talking to, not to permit or deny requests from specific people. That would probably be done at a different layer

**Comment by hjubb** [comment]
I'll close this issue as it is solved now unless there is anything else related that is blocking
