### ISSUE TITLE
[UX] When i'm hearing an audio and i send a message the audio stops and moves to start

### ISSUE THREAD

**Issue by ReivenIV** [oxen-io/session-android#1202]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

## **Describe the bug** /  To reproduce 

 1. put play on an audio 
 2. reply in the same chat while hearing the audio
 3. your audio will stop and go back to 0 second

## I propose 

It would be nice if the audio continue playing while i reply in my chat

## Device 
 - OS: Window 10
 - Version of Session or latest commit hash
- version session i have : https://github.com/oxen-io/session-desktop/releases/tag/v1.10.8

**Comment by hjubb** [comment]
Could you please raise this in the desktop repo

**Comment by ReivenIV** [comment]
Done in here : https://github.com/oxen-io/session-desktop/issues/2770
