### ISSUE TITLE
Problems with answer call and video size

### ISSUE THREAD

**Issue by Projtos** [oxen-io/session-android#1208]
**Code of conduct**

- [x ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
Hello. 
At the begining I would like to thank you for your work. I'm not complaining but I found two problems.
1. Connection from PC with Ubuntu 22.04LTS and latest session app to Xiaomi Mi6 LineageOS 20 (latest) and session app version 1.16.7 (3355) - can't answer the call (pressing on answer call button), nothing happends, phone still calls 
2. Same configuration as above but direction from xiaomi to PC, can't make video full screen or just bigger than it is (very small)
Thank you and good luck

**Comment by KeeJef** [comment]
Regarding the 2nd issue, which device is the one where you cannot make the video full screen?

**Comment by KeeJef** [comment]
Closing this one due to lack of information
