### ISSUE TITLE
failed to send

### ISSUE THREAD

**Issue by tdpo2** [oxen-io/session-android#1226]
**Describe the bug**

Error: http request failed at destination(service node IP:port) with status code 406.

**To reproduce**

send a message... it will say "sending" for a while but at the end it will fail to send.

**Smartphone (please complete the following information):**

- OS: android 13
 - Version of Session: 1.16.7(3355)

**Additional context**

receiving messages works. Sending messages from PC(windows) works.

**Comment by cyberavis** [comment]
I have a similar problem. My phone app is not sending messages. While at the same time, the desktop application works normally. I get incoming messages normally. I will add that I am in China and I often change my IP address using a VPN. I noticed that when the phone application cannot send messages, the path changes quite often (several times a minute).

**Smartphone (please complete the following information):**

- Galaxy Note 9
- Version of Session: 1.16.7(3355)

**Comment by KeeJef** [comment]
Will need more info here, Session logs would be useful if you have them, you can send them to me via my Session ID 05d871fc80ca007eed9b2f4df72853e2a2d5465a92fcb1889fb5c84aa2833b3b40

**Comment by KeeJef** [comment]
i have not received any logs since posting, please reopen if you have relevant logs
