### ISSUE TITLE
[Feature Request] Replace "Delete" with "Delete Contact"

### ISSUE THREAD

**Issue by x80486** [oxen-io/session-android#1230]
## Code of Conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

## Description

In the desktop application, the contextual menu for any given contact reads as `Delete Contact`; in the `Android` application it's on `Delete` — which is a little bit confusing because it doesn't say exactly what it's going to be deleted, if the contact or the conversation.

> By the way, it would be handy if there is a `Clear Conversation` option as well to just remove all the messages.

**Comment by KeeJef** [comment]
Yep this will be fixed in an upcoming release
