### ISSUE TITLE
session and Great Wall of China firewall

### ISSUE THREAD

**Issue by kl0001** [oxen-io/session-android#124]
I know you are multiple distributed servers. If all distributed servers are blocked by the Great Wall of China, can you continue to use them to chat? Will there be friends list sync?

**Comment by kl0001** [comment]
Or is it possible to block them all?

**Comment by Haafingar** [comment]
It is possible to block them all. We do have plans to create more robust protections against censorship in the future. For now we will remain quiet about them so that state actors have less time to work against these new measures.

**Comment by kl0001** [comment]
> 有可能将它们全部阻止。我们确实有计划在将来创建更强大的保护机制，以免受审查。目前，我们将对它们保持沉默，以使国家行为者有更少的时间来采取这些新措施。

Thank you very much for your optimization of China.  China does need a place without censorship and Internet freedom, more than any other country.

**Comment by kl0001** [comment]
> 有可能将它们全部阻止。我们确实有计划在将来创建更强大的保护机制，以免受审查。目前，我们将对它们保持沉默，以使国家行为者有更少的时间来采取这些新措施。

The latest update on China. Where can I get the latest logs, blogs, or where can I get them? @ loki-project

**Comment by kl0001** [comment]
> 有可能将它们全部阻止。我们确实有计划在将来创建更强大的保护机制，以免受审查。目前，我们将对它们保持沉默，以使国家行为者有更少的时间来采取这些新措施。

I mean, if

**Comment by kl0001** [comment]
Excuse me, what new progress has been made on this issue.

**Comment by hjubb** [comment]
This is more of a hypothetical and evolving problem that may in future emerge but at the moment shouldn't affect anything
