### ISSUE TITLE
Let the user know if they have been blocked

### ISSUE THREAD

**Issue by RustoMCSpit** [oxen-io/session-android#1246]
To my knowledge, this is not yet done

**Comment by RustoMCSpit** [comment]
@tashijayla what do the emojis mean? also dyk if im wrong?

**Comment by tashijayla** [comment]
> @tashijayla what do the emojis mean? also dyk if im wrong?

I'm agreeing with you that I think this is an important feature that I would love the developers to add sometime
(ಠಿ⁠_⁠ಠಿ人⁠)). But I can see why it hasn't been added yet' because even popular messaging apps like WhatsApp have been too lazy to add that feature for some reason.

**Comment by KeeJef** [comment]
I think this goes counter to the idea of blocking someone... generally when you block someone you don't want them to know they've been blocked, this is more important in Session as new accounts can be created to circumvent blocks. Closing for now
