### ISSUE TITLE
Why the length of the random number is only 16bytes,Is it safe here?

### ISSUE THREAD

**Issue by chenjia404** [oxen-io/session-android#1250]
https://github.com/oxen-io/session-android/blob/7b0c0147917655c88782e21eb0321ab16671ad78/app/src/main/java/org/thoughtcrime/securesms/crypto/KeyPairUtilities.kt#L18C19-L33

Why the length of the random number is only 16bytes,Is it safe here?

**Comment by KeeJef** [comment]
Hey, this was actually covered as part of out Audit here https://blog.quarkslab.com/resources/2021-05-04_audit-of-session-secure-messaging-application/20-08-Oxen-REP-v1.4.pdf

Ill post the excerpt here too 

> Session key generation is performed as standard Ed25519 key generation, with one modification: we use a random 128-bit value for the seed rather than a 256-bit seed value. Although this reduces the number of resulting possible private key values, because Ed25519’s private key generation uses a cryptographically secure hash (SHA-2/512) of the seed value, it does not introduce any correlation into the bits of the private key value which would otherwise weaken the cryptographic properties. Furthermore, the cited x25519 issue does not apply here: the SHA-2 hash is explicitly used in Ed25519 to eliminate possible correlation in the bits of the private key. This reduction was deliberately chosen to provide Session users with more usable 13-word recovery phrases as opposed to the 25 words which would be required if using a 256-bit key. Though the smaller seed does, in theory, result in a smaller brute force attack space, this is a distinction in theory only: a brute force attack against 2 128 possible seed values is simply not practical.

In short, yes this is safe, the reason its done is to provide shorter seeds

Closing for now
