### ISSUE TITLE
Malware detected 

### ISSUE THREAD

**Issue by Ghozt3k** [oxen-io/session-android#1252]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Malware detected by antivirus on Android .

**To reproduce**

**Screenshots or logs**

![PSX_20230618_172014](https://github.com/oxen-io/session-android/assets/137006644/8007eb50-b167-4a46-91e3-283768dddd42)

**Smartphone (please complete the following information):**

 - samsung
 - android
 - newest version of session

**Additional context**

What is that about?

**Comment by KeeJef** [comment]
Hey, this was a false detection by Avast, they have confirmed this, just trying to get the false detection removed on all the builds now, it was false detected for two of the ARM builds and the universal build. See tweet for context https://twitter.com/JefferysKee/status/1671006709677191169
