### ISSUE TITLE
Malwarebytes flagging google-play Session

### ISSUE THREAD

**Issue by mcmurphy8097234789** [oxen-io/session-android#1255]
**Code of conduct**

- [ x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Malwarebytes is flagging the Session app as being malicious. The Session app is downloaded from Google Play in India

**To reproduce**

Download app from google play, run the app, and scan with Malwarebytes app

**Smartphone (please complete the following information):**

Android; made in India device, will update this information within 24 hours

**Comment by KeeJef** [comment]
Does it tell you which file is being flagged? i checked and it looks like the universal build is not being flagged by any virus scanner right now https://www.virustotal.com/gui/file/12bab137a8c6321d8477169b733c942f55cc873b14f466c4d46cbfbe59ae05a3?nocache=1

**Comment by KeeJef** [comment]
Closing this should be resolved, for more info check here https://twitter.com/JefferysKee/status/1671006709677191169
