### ISSUE TITLE
Cannot initialize account using QR code

### ISSUE THREAD

**Issue by matso167** [oxen-io/session-android#1258]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Using QR code scanner does not detect QR code that is displayed by session desktop

**To reproduce**

Try to initialize session account using QR code, read QR code from session desktop

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: OnePlus Nord CE 2 Lite
 - OS: OxygenOS 13.0, Android version 13, security update 3 June 2023
 - Version of Session or latest commit hash: 1.16.9 (3385)

**Additional context**

**Comment by bemusementpark** [comment]
Are you using a camera app, QR code reading app, or Session Android to scan the QR?

Currently we only support reading QR codes from the app.

**Comment by bemusementpark** [comment]
ok, so you open the app, select new message, scan QR code, and it's just not recognized?

can you scan the QR code with other apps/cameras? (it won't open a session automatically, but you can copy the id and paste it in to start a session)

**Comment by matso167** [comment]
1. Clear session data

--> now on session start screen

2. Create session ID
3. Continue your session
4. Scan QR code

Reader camera doesn't recognize QR

I can scan recovery QR code using QR code reader app from play store.

However the value it reads is some kind of hash string, and not mnemonic of words. Also when copy pasted in seed phrase input it does not work as its not seed phrase.

**Comment by matso167** [comment]
Maybe its issue with session desktop creating QR code that does not contain seed phrase?

**Comment by matso167** [comment]
Session desktop version v1.10.8

**Comment by bemusementpark** [comment]
The QR has your session id, like a public key, you scan this from inside the app to start a chat.

Your `Recovery Phrase` is your seed phrase. That's accessible in the settings.

**Comment by matso167** [comment]
![Screenshot_2023-06-29_09-13-54-](https://github.com/oxen-io/session-android/assets/39828861/e627a594-1df7-4f8d-b6c4-ba0740e50763)

**Comment by matso167** [comment]
Different dialog

**Comment by bemusementpark** [comment]
Did you delete a comment? You're right. The QR code on the recovery phrase / mnemonic page is not the session id. And it's not your mnemonic. 

And I can' scan it from the app.

It could be your private key, but that doesn't seem to be usable as input on desktop or the apps.

Do you want to file an issue on [session desktop](https://github.com/oxen-io/session-desktop)?

**Comment by KeeJef** [comment]
Closing for now as no response was received
