### ISSUE TITLE
Cross-device syncing: Session Android unread count does not update when viewing a community while Session iOS is exploring the same community

### ISSUE THREAD

**Issue by fracting** [oxen-io/session-android#1266]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When viewing a Community using Session Android from a self built version on the libsession-integration branch, the unread count in the thread does not update if a Session iOS with libsession-intergration is browsing the same Community.
This seems like a UI glitch rather than a config message syncing problem or network problem, because if I return from the Community thread to the main contact list, the unread count is displayed properly in the main contact list immediately.

**To reproduce**

1. fresh installed Session iOS with libsession integration and fresh account Alice
2. link Alice's account to Session Android with libsession integration
3. Subscribe and enter any Community from Session iOS (Official Crypto Community for example)
4. Wait for full syncing of the new added Crypto Community to display on Session Android
5. Now here is the first UI glitch: Session Android should display an unread count for the Crypto Community in the main contact list, but in my case I don't see the unread count.
6. Then enter the Community thread on Session Android, the unread count is displayed properly in the begining
7. Now browse exactly the same Community thread on Session iOS, the unread count decreases in the iOS side
8. However, the unread count does not decrease in the Android side
9. If I return from the Community thread back to the main contact list, the unread count of the Crypto Community is displayed synced immediately.
10. If I replay the same experiment but switch the role of iOS and Android, I can see the Community thread unread count from the iOS side is always following the update of the Android side.

**Screenshots or logs**

UI glitch 1:
<img width="735" alt="android unread count does not show" src="https://github.com/oxen-io/session-android/assets/194342/34d665a3-9878-47b3-9463-3332665f7512">

UI glitch 2:
<img width="853" alt="android unread count does not update" src="https://github.com/oxen-io/session-android/assets/194342/953664f3-e628-4af7-b36d-dd6c90258a44">

**Smartphone (please complete the following information):**

 - Device: [Android Emulator]
 - OS: [Android]
 - Version of Session or latest commit hash

commit c9885739529fefaee40da77721ed7917c2d51dac (HEAD -> libsession-integration, 0x330a/libsession-integration)
Author: 0x330a <92654767+0x330a@users.noreply.github.com>
Date:   Mon Jul 10 17:15:15 2023 +1000

    build: update build number

**Additional context**

**Comment by fracting** [comment]
Session iOS version:

```
commit 38420997b0585efcd7e46a840cc2af8457af4efa (HEAD -> feature/updated-user-config-handling, mpretty-cyro/feature/updated-user-config-handling)
Author: Morgan Pretty <morgan.t.pretty@gmail.com>
Date:   Mon Jul 10 17:56:58 2023 +1000

    Fixed a couple of bugs and made some performance tweaks

    Cleaned up some duplicate poller logic (avoid going back to the main queue)
    Updated the code to remove a profile image if a user sends a message which doesn't have a profile image (ie. they've explicitly removed it)
    Fixed an issue where some more logic could incorrectly run in the DBWrite queue
    Fixed a bug where the OpenGroupPoller could stop polling when getting an error
    Fixed a bug where messages which had the same timestamp wouldn't get correctly marked as read when scrolling under the right circumstances
```

**Comment by hjubb** [comment]
Ah, this may be due to not listening for updates on the UI element while you are in the conversation. Just to confirm, if you are in a conversation on one device and the other device is on the conversation list does the unread count decrement as expected on the device in the conversation list? (This will rule out any syncing logic or issues and should be an easy fix in that case)

**Comment by fracting** [comment]
> Ah, this may be due to not listening for updates on the UI element while you are in the conversation. Just to confirm, if you are in a conversation on one device and the other device is on the conversation list does the unread count decrement as expected on the device in the conversation list? (This will rule out any syncing logic or issues and should be an easy fix in that case)

Yes, if my Session iOS is in a conversation and my Session Android is on the conversation list, then the unread count decrease as expected on Session Android.

**Comment by fracting** [comment]
> should be fixed in `a382700e6c22103f7ea8600ed71d5cc328326e50` on libsession-integration branch on my repo

Confirming fixed in `a382700e6c22103f7ea8600ed71d5cc328326e50` on libsession-integration branch.

I'll submit another issue in a seperate ticket for easier tracking.

**Comment by fracting** [comment]
https://github.com/oxen-io/session-android/issues/1270

**Comment by fracting** [comment]
https://github.com/oxen-io/session-android/issues/1272
