### ISSUE TITLE
Nodes behave in a non-anonymous way

### ISSUE THREAD

**Issue by RustoMCSpit** [oxen-io/session-android#1267]
Forgive me if I'm missing something but if each user has a unique set of node chains then the middle node could identify its unique path (added with IP revealing calls this is really bad), each message sent could be traced to its sender. The solution? Have multiple users on the same exact node chain to obfuscate uniqueness or have every node send their info to a trusted self-bleaching node or something I don't know I'm not very tech-savvy.

**Comment by RustoMCSpit** [comment]
Even if the data is encrypted, the sender is uniquely tagged. Thats the cause of concern

**Comment by hjubb** [comment]
Each node has little to no information about the next and previous location. At best the very first node could know that "a user", without knowing their actual session ID or the intended destination, is sending a message. More information: https://docs.oxen.io/oxen-docs/products-built-on-oxen/session/network-infrastructure#onion-requests
