### ISSUE TITLE
Session's User Base Growth and Antivirus False Alarms: A Correlation or Coincident?

### ISSUE THREAD

**Issue by venezuela01** [oxen-io/session-android#1268]
The Session team has recently put effort into marketing activities, and it seems to be paying off. Official reports show that Session's user base has grown significantly in just a few weeks. 

Unfortunately, at around the same time, Session's Android app was incorrectly marked as malware by several leading antivirus vendors sharing a common database. The Session team is aware of the situation and has already reached out to these vendors to rectify the false alarm [1]. Sadly, during this period, the 30 days moving average of Google Play review score for Session has dropped from 3.78 to 3.69. This decline is largely due to complaints about antivirus alerts. [2]

It makes me wonder if Session's rapid growth and this antivirus false alarm are just a coincidence, or if there's some link between them. This is a valid question, considering that many sectors, including antivirus and security, have been shifting towards big data and machine learning solutions over the past decade. They might have crawlers scanning app stores, and a sudden surge in an app's downloads could trigger their risk control system. This can sometimes result in a false alarm, especially if other unlucky factors come into play at the same time.

A common challenge with risk prediction models based on machine learning is that they're often hard to interpret. This can mean it takes longer for vendors to check their systems and figure out why a false alarm went off. And there's no perfect way to prevent another false alarm from happening when Session sees a large spike in new user downloads in the future.

To reduce the risk of false alarm and then having to clear things up, we might want to stay in touch with antivirus vendors, and submit our app to their database for checking before we roll out each new release, or at least do so at the same time.
This lesson could be equally important for other products, such as the Oxen wallet and Lokinet. If our wallet were to be mislabeled as malware, it would lead to a loss of user trust and cause FUD. Trying to then explain the situation and persuade users to trust us again would be a considerable challenge and possibly a bit too late.

According to [3], Avast has 145 million mobile users, according to [4], Avast has nearly 300 million Android installation, which confirms their official claim of 145 million mobile users. This is a big player that we can't ignore, especially if they are causing more harm than good.

It seems there is a place where we can submit Apps for analysis and share the sample to the security community:
https://www.virustotal.com/gui/home/upload

[1] https://sessionapp.zendesk.com/hc/en-us/articles/19915563353753-AVG-Avast-Security-Concerns-False-Positive-Report- 
[2] https://www.appbrain.com/app/session-private-messenger/network.loki.messenger
[3] https://web.archive.org/web/20180623143149/https://investors.avast.com/our-story/at-a-glance/
[4] https://www.appbrain.com/app/avast-antivirus-security/com.avast.android.mobilesecurity

**Comment by venezuela01** [comment]
~10 days ago someone from Reddit asked about the antivirus alert of the Session Android app while no one is aware that it was a false alarm:

https://www.reddit.com/r/Session_Messenger/comments/14pqg41/session_messanger_keeps_flagging_as_malware/

If would be nice if someone from the official team to response to them on Reddit. @KeeJef 

According to https://www.similarweb.com/website/getsession.org/#social-media, over 60% of social traffic source of getsession.org comes from Reddit, much more than Twitter and Youtube, I'm surprised by the number and I don't know whether they are accurate. If the number is accurate, we should pay more attention to Reddit, maybe the marketing team would have a better idea.

**Comment by venezuela01** [comment]
I have seen the relentless efforts of the Session team in addressing users' concerns about the antivirus false alarm on Google Play. Your hard work is greatly appreciated!

Unfortunately, developer responses are often overlooked by many users who tend to focus more on the top comments, which may result in them missing your clarifications. As such, I would recommend that the Session team post a review comment to enhance its visibility among users.

> ⭐⭐⭐⭐⭐
> 
> Greetings to our users, this is a comment from the Session development team. Typically, we avoid rating or commenting on our own application to maintain the integrity of the ratings. However, due to the recent confusion and concern caused by a false antivirus alarm, we find it necessary to provide a direct clarification.
> 
> We extend our sincere apologies for any confusion or concern this incident may have caused our valued users. It is vital to note that AVG/Avast's identification of Session as a potential threat resulted from their system error and has been confirmed as a false positive. Rest assured, they are rectifying this issue.
> 
> For more information, please visit this link: https://sessionapp.zendesk.com/hc/en-us/articles/19915563353753-AVG-Avast-Security-Concerns-False-Positive-Report
> 
> We wish to reassure our users that Session continues to be a safe and reliable platform for your communication needs. Your trust and continued support are of paramount importance to us, and we are committed to preserving and enhancing the security of Session.
> 
> We kindly request our dedicated Session users to upvote this comment if you find it helpful, ensuring more users can see it. We greatly appreciate your support!

**Comment by KeeJef** [comment]
Do reviews by the app developer get bumped to the top of the review list?

**Comment by venezuela01** [comment]
> Do reviews by the app developer get bumped to the top of the review list?

No I don't think so, I mean the app developer can explicitly ask users to upvote this comment, and hopefully users will cooperate and help us bump it to the top of the review list.

**Comment by KeeJef** [comment]
Hmmm good to know, we are going to release a new version for Session Android shortly which should stop virus reports for the specific version which was flagged so might not be worth it for now, I've passed this release via VirusTotal and nothing was flagged so lets see how we go. If this happens in the future i think this could be a good response though.

**Comment by KeeJef** [comment]
Still monitoring for reports but it seems we have not been flagged this release, closing this for now as it may have just been a once off, will repoen if we get flagged again
