### ISSUE TITLE
Let's make session get out to the masses in privacy and private communications. Voice chat rooms. Social media, and oxen token more mainstream!

### ISSUE THREAD

**Issue by digitalnb** [oxen-io/session-android#1306]
Session seems to be among the best social media platforms out there! It's open source and built on-top of tor.  So users can have some level of privacy and a strong encryption, but that can be strengthened even more. 
Why do you have a weak encryption when it can be strong? Even self created and unique. 
Not everyone wants Facebook and third parties listening in and shallow social media. Voice based social media is the most real in my opinion. Session is the perfect alternative for me! You can have private conversations and just talk, but session needs to look more like discord, but encrypted.
That's the thing. Voice chat rooms on the left... Just people getting to know one another. And that can talk and call to one another in private, without 3rd parties and people that have noting to do with individuals conversations being there. Or wanting to listen in. They can call and talk to the individuals themselves then instead.

We need to make session to have ore users and more people using the oxen token! This can be a great community where people learn languages, and just talking in private. Where they can feel safe and not being bothered by 3rd parties, or the government and such wanting to know everything about everyone, instead of minding their own business. 

So... How do we bring more people into session and private communities? Make it easier so it looks like discord, where people can hang out in voice chat rooms, that's the key. This is a good start. I love this!
But, there is much more that can be created to get people to invest in oxen and session as a social media platform. 

To me it's one of the best options out there for a social media platform, and i know i'm not alone in thinking like that. 
People just having private conversations between two people is very important in life. It's very hard to be oneself with the thought of creepy third parties listening in, or mass surveillance and such. 
Technology overall is kinda creepy. In real life people would just take a walk and talk between two people!

Session might be the closest artificial technology solution, to that natural behavior, so respect for that!

But there should be encrypted voice rooms also. Where people can just talk. 
Security and privacy do not need to be abused. Now it's more social media platforms that sell the data and such.. 
So i think there should be some "revolution" where session gets to be a big platform online! No need to sign up. Just like now, no metadata, but better security, better encryption, and more normal language rooms. 

It's not a platform for illegal stuff.. It's the user-base that creates social media platforms. Thanks for creating this awesome project, and the oxen token needs to get around and bought.. i support this 110%. Thanks! Keep it up!

The thing that's missing is the voice based social media functions in private rooms in my opinion.. But sure people can talk in private also. One on one.. That is true. 
But why not have the option for voice chat rooms encrypted?
How many are socializing on session encrypted in voice? Text is shallow is my point. 
Discord open sourced and encrypted would be awesome in my opinion, but maybe session could be the next thing like that? Plus the oxen token..  people need to invest in the oxen token more. 
Just because they value privacy, etc. I don't get why session is not way bigger then it is!

Why do they choose facebook? It's mainstream, sure, but it's lame. And not respecting of privacy. etc..
Why can't this become way bigger? The new whats app, and such. Might be on the way, i hope. In time.. 
What kind of encryption do you use? I heard it's weak, or that you downgraded it. 
Why? If so that could be considered a bug.. 

Also, why don't you store the messages locally on every device? Also an bug. I heard someone talk about briar and that it's more secure. 
https://wikiless.org/wiki/Briar_(software)?lang=en

Session could maybe take some inspiration from there?
I'm no coder, i just thought i try and give some constructive criticism.. 
And you are just creating the platform which seems great, so it might be the userbase that needs to change. 

More learn languages channels maybe..  maybe voice chat rooms?
Get in more normal people that value privacy in there. I have not explored session much, there might already be rooms like that.. 
It just feels like voice based chat rooms would get more users in to session and oxen to me.. text is to shallow, and people value privacy in voice talk, and no 3rd parties recording and/or selling the data to the highest bidder. 

Also, add 2fa and manual codes to login. That's also a bug, or weak security. Why is that not an option in the settings even?  Or a password to login. MIight need external servers? If so maybe not then.. 
And why can't every message and everything be local? Is it local like briar? How could session be improved like briar when it comes to security?
I clearly don't even understand how session works. Might need to read up on that. But the option to have a strong password locally to unlock session would be a good thing when it comes to privacy in my opinion. 
Now you don't have that option and just some word combination. I'm very thankful for session and i don't mean to be rude or anything. :) 
Just saying that there could be better security, right.. Because in this day and age where others are so nosey on what others are doing, and want to sell that data, this is needed. Even governments buy data from social media platforms with tax money i heard online in some youtube video...
Thanks for creating this. Make it more strong perhaps..

**Comment by KeeJef** [comment]
Closing this as you said your intention was to open this on Session desktop repo https://github.com/oxen-io/session-desktop/issues/2877
