### ISSUE TITLE
New messages are hidden under keyboard.

### ISSUE THREAD

**Issue by shahedurrahman** [oxen-io/session-android#1316]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

During an active chat, new incoming messages are appearing under the keyboard and typing area.

**To reproduce**
- Start a conversation with any contact
- Receive few messages from your contact
- New messages will start appearing under keyboard and typing area

**Screenshots or logs**
![Screenshot_20230905_003842_Session](https://github.com/oxen-io/session-android/assets/588711/7716f36b-d788-48f1-a385-77edd57efae9)

![Screenshot_20230905_003901_Session](https://github.com/oxen-io/session-android/assets/588711/98d7d661-4aa7-4321-8426-84192ee76d8f)

**Smartphone:**

 - Device: Samsung Galaxy A52s 5G
 - OS: Android 13, OneUI 5.1
 - Version of Session: 1.17.0 (3545)

**Comment by KeeJef** [comment]
This is something iOS has fixed which we should bring to Android have put this one in the backlog for now

**Comment by keybreak** [comment]
I'd like to add that same thing happens when you're at the bottom of dialog, start typing and your message has new lines - new lines shifting dialog in the same way.

**Comment by alansley** [comment]
This is tracked internally as: https://optf.atlassian.net/browse/SES-1145
