### ISSUE TITLE
So many failed things in logs

### ISSUE THREAD

**Issue by SzBenedek2006** [oxen-io/session-android#1327]
[samsung-g0s-API33-v1.17.1-1695291507076.txt](https://github.com/oxen-io/session-android/files/12683417/samsung-g0s-API33-v1.17.1-1695291507076.txt)

**Comment by bemusementpark** [comment]
Yes, there's some room for improvement.

Are you noticing any issues in the app itself?

[This PR](https://github.com/oxen-io/session-android/pull/1328) should fix the JSON issues.

**Comment by SzBenedek2006** [comment]
Some general stuff, like lag and slow message sending. Nothing special at the moment.

**Comment by hjubb** [comment]
This should now be fixed PN side, and fixed in clients in a new release
