### ISSUE TITLE
[BUG] App does not start, slows down phone.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#1335]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upon opening up the app it just gives me a gray screen and seems to slow down my navigation controls.

### Expected Behavior

To just boot up the app while it fetches and loads messages.

### Android Version

Android 12

### Session Version

1.17.2

**Comment by KeeJef** [comment]
Is this something which only appeared when you upgraded to 1.17.2 or was occurring previously?

**Comment by Flam3z** [comment]
Just started happening but finally opened to the chat list after a half hour.

**Comment by Draken013** [comment]
I'm having this issue as well. Installed the F-Droid version in the meantime.

**Comment by KeeJef** [comment]
With the crash on startup can you post your device logs here, or message them to keejef on Session

**Comment by Flam3z** [comment]
here you are:
[samsung-beyond1q-API31-v1.17.2-1696997952659.txt](https://github.com/oxen-io/session-android/files/12864794/samsung-beyond1q-API31-v1.17.2-1696997952659.txt)

**Comment by KeeJef** [comment]
> here you are: [samsung-beyond1q-API31-v1.17.2-1696997952659.txt](https://github.com/oxen-io/session-android/files/12864794/samsung-beyond1q-API31-v1.17.2-1696997952659.txt)

Sorry i think that log file is empty

**Comment by Flam3z** [comment]
Odd, i exported it from the app and it came up empty

**Comment by Flam3z** [comment]
Did not encounter the issue this time thsnk you
