### ISSUE TITLE
[BUG] Session crashes almost instantly on launch

### ISSUE THREAD

**Issue by GrahamboJangles** [oxen-io/session-android#1345]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Session opens for about 1 to 2 seconds then crashes. I don't know how to send logs other than `adb logcat` so I've attached that:
[adb logcat session.txt](https://github.com/oxen-io/session-android/files/13049228/adb.logcat.session.txt)

I've also noticed this only seemed to happen when I recovered my account, and when I made a brand new account and joined the Lokinet updates public group it wasn't crashing.

### Android Version

13

### Session Version

1.17.4

**Comment by KeeJef** [comment]
Seems strange, will look into this one

**Comment by GrahamboJangles** [comment]
@KeeJef Thank you, Jeff. I have no idea if this is it, but I have a feeling it has something to do with an overflow of too many messages.

**Comment by GrahamboJangles** [comment]
@KeeJef It works fine now. So it must have been something in the swarm it was trying to load since it's been about a month since I last tried and failed.

**Comment by KeeJef** [comment]
Okay closing for now
