### ISSUE TITLE
[BUG] App crashes when first character in message search is not a number or letter 

### ISSUE THREAD

**Issue by ProjectAsleep** [oxen-io/session-android#1346]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app crashes or sends me back to the unlock screen when first character in message search is not a number or letter (partially tested by author)

### Expected Behavior

The app shouldn't 'crash' and find the respective messages including the character ＾ω＾ 

### Steps To Reproduce
1. Open the App
2. Open a Chat
3. Navigate to the Search Option
4. Enter one character excluding 'standart' numbers or letters

### Navigating to the Search Option:

3.1. Open the context menu via clicking on the ellipsis in the upper right corner.
3.2. Click on Search (if that's what it's called in the English version)

### Test Examples:
&, %, ', |, ?, (

### Android Version

Android 14 (GrapheneOS)

### Session Version

1.17.4

**Comment by KeeJef** [comment]
Reproduced locally, global search doesn't have a problem, but in chat search does
