### ISSUE TITLE
[BUG] Send link previews on Android should be OFF by default

### ISSUE THREAD

**Issue by keybreak** [oxen-io/session-android#1347]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

By default **Send link previews** on Android settings is set to ON

### Expected Behavior

By default **Send link previews** on Android settings should be set to OFF

Reasons:
1. Privacy by default
2. Consistency across platforms, currently only Android version seems to behave that way.

### Android Version

Android 9

### Session Version

1.17.4 (3595)

**Comment by KeeJef** [comment]
Yep, this needs to be changed to be inline with other platforms
