### ISSUE TITLE
[Feature] Automaticall scroll down to the new message

### ISSUE THREAD

**Issue by ozturkberkay** [oxen-io/session-android#1364]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

It is very annoying to having to manually scroll down to see the new messages. It would be nice to have an option to have Session do it automatically.

**Comment by mpretty-cyro** [comment]
@ozturkberkay just wanted to get some clarity on this feature request

At the moment if the conversation is scrolled all the way to the latest message it should automatically scroll to show new messages when they are received - is this behaviour not working for you? or are you looking for a setting which will **always** scroll to show the latest received message regardless of where you currently are in the conversation?

**Comment by alansley** [comment]
This bug is tracked internally as: https://optf.atlassian.net/browse/SES-789 and primarily relates to that our scroll behaviour should be to automatically scroll to the bottom of a long message rather than to the top of it, as discussed in the preceding link.
