### ISSUE TITLE
[BUG] Android Wear Notifications

### ISSUE THREAD

**Issue by Nemisor** [oxen-io/session-android#1381]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Android Wear notifications do not vibrate. 
Have tested this on multiple Pixel phones with both Pixel 1 and 2 watches.

### Expected Behavior

Expect notifications to vibrate the watch when silenced.

### Steps To Reproduce

1. Message a contact.
2. Contact responds.
3. Notification appears on phone and watch.
4. Watch does not vibrate, regardless of vibration settings.

### Android Version

Android 14

### Session Version

1.17.4

### Anything else?

![Screenshot_20231220-133456](https://github.com/oxen-io/session-android/assets/1268315/90764773-b6ce-4975-b9b8-90fe321eb0ba)

**Comment by mpretty-cyro** [comment]
Jira ticket SES-1378

**Comment by Nemisor** [comment]
Closed because recent updates to Android or WearOS have resolved the issue and it now vibrates consistently while paired to a phone that previously did not respect the setting.
