### ISSUE TITLE
Message notifications are delayed

### ISSUE THREAD

**Issue by jokase** [oxen-io/session-android#139]
**Describe the bug**

Received a notification from Android that I had a message from someone.
Immediately clicked the notification.
The message said it was 20 minutes old.

**To reproduce**

Do not have the app open.
Get someone to send you a message.
Wait....
Eventually you get a notification.
My worst case was 45 minute after the message was sent.

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android Pie
 - Version of Loki Messenger: 1.0.6

**Additional context**
If the app is open (running in the background?), then notifications seem to happen when messages arrive.

**Comment by jokase** [comment]
This issue was also reproduced by the person I was sending messages to.

**Comment by steelcg** [comment]
me too, happens on iOS too.

**Comment by gmbnt** [comment]
We're working on fixing this.

**Comment by EchedeyLR** [comment]
I can confirm this in last version until today (1.1.0.445) with FCM sometimes (as background polling is not working)

**Comment by nielsandriesse** [comment]
This should be fixed now.
