### ISSUE TITLE
Deleting chats using a pin code

### ISSUE THREAD

**Issue by Kocope3** [oxen-io/session-android#1406]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Your application can be made even more secure in the event that the user is subjected to physical force (or pressure) and is required to unlock the application.
This requires 2 pin codes:
- the first pin code simply unlocks the application;
- the second pin code will also unlock the application, but will first delete (at the user's discretion):
1) all chats;
2) all chats and contacts;
3) only pinned chats

No other messenger existing today has this level of protection.

**Comment by KeeJef** [comment]
Thanks for the suggestion, closing as duplicate #1078 i believe "Duress code" is the correct term
