### ISSUE TITLE
[BUG] Disappearing Messages function doesn't work

### ISSUE THREAD

**Issue by session11** [oxen-io/session-android#1423]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Before the update disappearing messages was set to 5 minutes. The updated version doesn't give timer to be set in minutes but has the option "legacy", which is selected by default. However, messages in the chat remain and they don't disappear by itself. The other options are greyed out and cannot be selected. 

### Expected Behavior

Disappearing messages should work as usual when "legacy" is selected. 

### Android Version

Android 14

### Session Version

1.17.6 (3685)

**Comment by eddynamite** [comment]
Hello,
I have the same problem. I have to delete messages manually.

**Comment by session11** [comment]
Glad to see that someone noticed this issue. With LEGACY option enabled, messages should disappear as usual but they dont. And new timers in hours are not convenient. And why DISAPPEAR AFTER READ and DISAPPEAR AFTER SEND option is greyed out?

**Comment by eddynamite** [comment]
a friend of mine who uses an iPhone told me she had the same problem with ephemeral messages

**Comment by bemusementpark** [comment]
Thanks for filing the issue.

Can you specify which platform you are sending/receiving and if sender and/or receiver's messages fail to disappear?

If you long press the message it should show the remaining time of the message. Can you have a look? It looks like this:

<img width="179" alt="Screen Shot 2024-03-12 at 11 15 02 am" src="https://github.com/oxen-io/session-android/assets/9282178/958e1d5e-945a-4c23-954a-7e7f0de60ed5">

Thanks.

**Comment by session11** [comment]
> Thanks for filing the issue.
> 
> Can you specify which platform you are sending/receiving and if sender and/or receiver's messages fail to disappear?
> 
> If you long press the message it should show the remaining time of the message. Can you have a look? It looks like this:
> 
> <img alt="Screen Shot 2024-03-12 at 11 15 02 am" width="179" src="https://private-user-images.githubusercontent.com/9282178/311903828-958e1d5e-945a-4c23-954a-7e7f0de60ed5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTI3NzIsIm5iZiI6MTcxMDIxMjQ3MiwicGF0aCI6Ii85MjgyMTc4LzMxMTkwMzgyOC05NThlMWQ1ZS05NDVhLTRjMjMtOTU0YS03ZTdmMGRlNjBlZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDMwMTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDNkYzgwZTZmOWVmOTYyYzAwNzJhYzQwNzlkZDJlMGNjOTg4ZjZiYTY2NDNkOTA0N2RhMmEwZDQ4ZDFkNzFiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5fOtxJbyWmCLB1_eU2nLA7354qcrzOqQx7eXon6fGOU">
> Thanks.

I am using it on **Android 14**. The receiver is also using it on Android. The screen shot you shared is a new thing for me, I don't see any such timer option under the "delete" button.

**Comment by bemusementpark** [comment]
Ok, if a message is disappearing this should be visible. The other tell is the timer icon next to the send/read indicator.

Can you see the disappearing timer setting in the chat? can you see it in the appBar/actionBar at the top of the screen? (you might need to swipe)

Did you set the timer and send the message from the same device?

_This feature is programmed to transition to the full V2 in about a day, so please have another look in a day or 2 to see if the issue persists. (You'll know it's been turned on when Legacy is no longer be an option.)_

**Comment by session11** [comment]
As I said in my original post, messages used to disappear before the update. In previous version of Session, the timer was set to 5 minutes, and I could see the timer next to sent/received messages. The problem started after the update. Now, messages only disappear, if I manually delete them. Disappearing Messages settings does have timer function, but they are not available in minutes but hours and I find it very inconvenient. (if I select 12 hours, it works, I then see timer icon before the messages) but with legacy, it doesn't work.

**Comment by session11** [comment]
@bemusementpark, just as you said, the feature has been activated. Option "Legacy" is gone and "Disappear after read and send" options are available. For me, at least,  this issue can be marked as closed. Thank you for your assistance.

**Comment by bemusementpark** [comment]
Great, thank you.

**Comment by eddynamite** [comment]
@bemusementpark un the option for deleting messages when sending 5 minutes is indeed present but when receiving messages they remain on 12h
![Screenshot_20240313-095841](https://github.com/oxen-io/session-android/assets/162713877/1bfe21e3-12e6-4dc5-b5a7-63f460ef81fd)
![Screenshot_20240313-095829](https://github.com/oxen-io/session-android/assets/162713877/3160fc98-1d8e-49eb-ad7d-8ca1c92039c1)

**Comment by bemusementpark** [comment]
@eddynamite Yeah, Disappear after Read has some shorter time options available.

**Comment by KeeJef** [comment]
The different settings reference how the timers work for your messages, both on your device and when your messages are received. Your chat partner can also set disappearing message rules for their own messages. This is a change from before when the setting was per conversation; now it's per user.

**Comment by eddynamite** [comment]
@KeeJef everything is perfect, it works perfectly.
Thank you
