### ISSUE TITLE
[BUG] problems with F-droid repo

### ISSUE THREAD

**Issue by GameOverFlowChart** [oxen-io/session-android#1433]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The F-droid repo isn't working anymore, updating to 1.18.1 isn't possible "invalid response from server". Other repos like the official F-droid repo works fine so it's a problem on your end.

### Expected Behavior

Updating from F-droid clients is possible again.

**Comment by tashijayla** [comment]
Works for me. I wonder if it's a network problem or a problem with your F-Droid client!. I use Droid-ify as my F-Droid client without a VPN.
When 1.18.1 became available my F-Droid client didn't offer me the update' most likely because it's a small version number!, I needed to click on the version I wanted to download in the UI 

![IMG_20240315_171710_406.jpg](https://github.com/oxen-io/session-android/assets/93866029/6233a62d-5490-4587-a897-cf939a9ea8bc)

**Comment by GameOverFlowChart** [comment]
> Works for me. I wonder if it's a network problem or a problem with your F-Droid client!. I use Droid-ify as my F-Droid client without a VPN. When 1.18.1 became available my F-Droid client didn't offer me the update' most likely because it's a small version number!, I needed to click on the version I wanted to download in the UI
> 
> ![IMG_20240315_171710_406.jpg](https://private-user-images.githubusercontent.com/93866029/313279909-6233a62d-5490-4587-a897-cf939a9ea8bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTUwNDUsIm5iZiI6MTcxMDU5NDc0NSwicGF0aCI6Ii85Mzg2NjAyOS8zMTMyNzk5MDktNjIzM2E2MmQtNTQ5MC00NTg3LWE4OTctY2Y5MzlhOWVhOGJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMWE4NGIxNDk4NzIyMzFhODI4ZGYwZTE2OGRjMGIyMTAyZGRiZDk3ZWRlZTczMzhkOTc5NzIyYzZhMjRlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3tPi0MrYJHN8ThMSpIL4vGlIcalSh5jPHOUJnybL2tY)

I also use Droid-ify, and all the other apps updated fine

**Comment by GameOverFlowChart** [comment]
Stopping Droid-ify and deleting it's app cache seems to have fixed the problem, now the download is running.
