### ISSUE TITLE
[BUG] Delivery status remains on "Sending" and displays forever on each sent message in Communities despite having successfully sent

### ISSUE THREAD

**Issue by alansley** [oxen-io/session-android#1438]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Messages sent in Communities (only, not 1-on-1 or in closed groups) always display their delivery status for every sent message, and the delivery status never ticks over to "Sent" despite the message(s) having been successfully sent.

### Expected Behavior

Messages sent in Communities only display the delivery status for the last sent message, and the delivery status ticks over to either "Sent" on successful delivery or "Failed to send" on delivery failure.

### Steps To Reproduce

Send any message, whether SMS or MMS in a Community and observe the delivery status.

### Android Version

All

### Session Version

1.18.1

### Anything else?

This issue is tracked internally as: https://optf.atlassian.net/browse/SES-1567

**Comment by mpretty-cyro** [comment]
We're working on resolving this bug
