### ISSUE TITLE
Feature & menu parity with desktop version

### ISSUE THREAD

**Issue by kekukui** [oxen-io/session-android#144]
The following menu appears in the desktop version of Session, but does not exist in the mobile app.

![image](https://user-images.githubusercontent.com/20834957/76731026-cfc45e00-6732-11ea-9357-f39dccad006c.png)

On the following page it says:

> **How do I know if the person I am talking to is the person I want to talk to?**

> Session's "**Safety Numbers**" feature makes it easy for people in a conversation to verify each other if both parties would like to do so. You can use another channel of communication outside of Session to ask for and verify someone's Session Safety Number, and then check that the Safety Number in the app matches what you've been told. If the Safety Numbers match, you're speaking to the correct person. If they do not, the Session account may be an imposter.

https://getsession.org/faq/

I cannot find this "**safety number**" on Android... it only seems to exist in the desktop version.

**Comment by Brice-W** [comment]
Safety number is not used anymore
