### ISSUE TITLE
Adding Custom Image to Contact. 

### ISSUE THREAD

**Issue by session11** [oxen-io/session-android#1440]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

The feature to change the display name of contacts is very useful and I believe that, it would be very convenient if the feature could be extended to allow us to change the display picture of contacts as well. This, combined with disappearing messages, further helps to anonymize the contacts.

**Comment by session11** [comment]
Having requested the feature, I realized that it could also be used the other way. So, its in user's best interest that such a feature is not activated. However, something like hiding the display picture of contacts could be implement instead.

**Comment by KeeJef** [comment]
OK ill close this one for now, open another issue if have a specific approach you want to suggest
