### ISSUE TITLE
[BUG] Special video link message affects other messages

### ISSUE THREAD

**Issue by qux-bbb** [oxen-io/session-android#1444]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

About he Android app. After I send a special video link message to someone, some messages near the video link message will not be long pressed.  

### Expected Behavior

After I send a special video link message to someone, all messages can be long pressed.  

### Steps To Reproduce

1. Send the link to an android user: https://www.bilibili.com/video/BV1nA4m1N7TT
2. The android user cannot long press this message and near messages

### Android Version

Android 14

### Session Version

1.18.1 (3695)

**Comment by qux-bbb** [comment]
> Had a second community report of this issue, tracking internally via Jira as https://optf.atlassian.net/browse/SES-1724

Sorry, I don't have permision to view this page.

**Comment by HenriGrant** [comment]
This issue affected a Pixel 8 running Android 14, Session version 1.18.1
I sent two twitter links with previews to the android device, the messages caused scrolling to lag a little, and when the messages with previews were on the screen, no messages could be long pressed.

**Comment by qux-bbb** [comment]
This version doesn't have the bug: https://github.com/localsend/localsend/releases/tag/v1.15.0

**Comment by KeeJef** [comment]
I'm no longer experiencing this issue with 1.19.1, tested that link

**Comment by qux-bbb** [comment]
> 1. https://www.bilibili.com/video/BV1nA4m1N7TT

No this issue from v1.15.0.  
@KeeJef @HenriGrant If you all agree, I can close this issue.

**Comment by HenriGrant** [comment]
> > 1. https://www.bilibili.com/video/BV1nA4m1N7TT
> 
> No this issue from v1.15.0. @KeeJef @HenriGrant If you all agree, I can close this issue.

Tested it on the pixel 8 with 1.19.1. I think the bug is gone now.

**Comment by qux-bbb** [comment]
OK, Thank you!

**Comment by qux-bbb** [comment]
Sorry that I pasted a wrong url.  I mean that no this issue from https://github.com/oxen-io/session-android/releases/tag/1.18.5
