### ISSUE TITLE
[BUG] 1.18.1 So Slow It's Unusable

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#1450]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upgraded to 1.18.1 today. Open Session, and go into a chat or group with significant history. Constantly popping up with App not responding. I have to kill Session just to use my phone normally again. Possibly related to issue #1399 

### Expected Behavior

I don't know the version I had installed prior, but that version was working well.

### Steps To Reproduce

Open app, then open any chat or group with a significant history.

### Android Version

10

### Session Version

1.18.1

### Anything else?

I have Enabled trim messages to 2000 over 6 months yes. Attached debug export logs.
[OnePlus-OnePlus6-API29-v1.18.1-1712587191063.txt](https://github.com/oxen-io/session-android/files/14907095/OnePlus-OnePlus6-API29-v1.18.1-1712587191063.txt)

**Comment by Sepero** [comment]
Additional info: Installed from GitHub releases, not Google play

**Comment by Sepero** [comment]
Prior to entering a group, Session appears to run fine. I'm aware of other people who have experienced this. To get rid of the issue, they said they restored from passphrase already. My account is essentially in an unusable state. I'm waiting for upgrade to fix.

More logs
[OnePlus-OnePlus6-API29-v1.18.1-1712828141149 (1).txt](https://github.com/oxen-io/session-android/files/14970363/OnePlus-OnePlus6-API29-v1.18.1-1712828141149.1.txt)

**Comment by pottsandpans** [comment]
This issue is being tracked internally in Jira - SES-1904

**Comment by Sepero** [comment]
I see SES1901 was merged into v1.18.3. I'm now running v1.18.4 and this issue is still not resolved.

On v1.18.1 I eventually ended up erasing all my chat history to make the app usable again.

I've been using Session since then, and I'm in some popular community groups. Now that the chat history is building up again, I notice the app slowing down, scrolling jerky, and using more resources. As more chat history accumulates, the worse the problem becomes.

**Comment by KeeJef** [comment]
We are working on a host of performance improvements currently, hoping to get various improvements out in next point release, very aware of how the app slows down as message history increases and working on fixes 👍

**Comment by KeeJef** [comment]
Would you be able to provide logs from the slow device @Sepero ? could help us diagnose

**Comment by Sepero** [comment]
Absolutely @KeeJef . My apologies. I appreciate your help with this.

[OnePlus-OnePlus6-API29-v1.18.4-1719248751738.txt](https://github.com/user-attachments/files/15959126/OnePlus-OnePlus6-API29-v1.18.4-1719248751738.txt)

**Comment by Sepero** [comment]
At the end of that log I tried to do some things that cause more extreme UI lag.

**Comment by KeeJef** [comment]
Thanks @Sepero , @simophin some logs to look at for performance issues, might provide some insights

**Comment by ThomasSession** [comment]
Hey there. Are you still seeing issues on the latest builds?

**Comment by Sepero** [comment]
This issue appears to be resolved for me. Thank you.
