### ISSUE TITLE
Signing key changed?

### ISSUE THREAD

**Issue by IzzySoft** [oxen-io/session-android#1614]
Today's update triggered an alert at IzzyOnDroid:

```
! 2024-08-12 20:08:53,094 WARNING: "network.loki.messenger_3781.apk" is signed by a key that is not allowed:
a450db029aa14789d32fd44cecdc2fd36f0d221f7eafb071561eb5ab437978e6
```

The update was hence rejected ("tamper-alert"). I've checked the release notes, but found no hint. What happened, if I may ask? Dragons ahead?

**Comment by IzzySoft** [comment]
Umpf, a debug cert…

```
$ sigcheck network.loki.messenger_3781.apk
package: name='network.loki.messenger' versionCode='3781' versionName='1.19.0' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: a450db029aa14789d32fd44cecdc2fd36f0d221f7eafb071561eb5ab437978e6
Signer #1 certificate SHA-1 digest: d018d7b55102dab2606b279bd02ca49cf2c78fb2
Signer #1 certificate MD5 digest: ea316601996dabab4587374812dfec7f
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: e9af39978391325ec498883d3a43cf2cca2934b1d68d74cd7de1ad5fda81d890
Signer #1 public key SHA-1 digest: be74411a649d4b59b0194732b63bcdfac5d8984a
Signer #1 public key MD5 digest: 36d0c95bed459fba1fbc19fb9bc76ed1
Signature algorithm name: SHA1withRSA (weak)
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
```

In case it matters: the armeabi APK. But I'm afraid the others, too…

**Comment by KeeJef** [comment]
Just pushed another update to F-Droid, should be signed under correct keys now

**Comment by IzzySoft** [comment]
> Just pushed another update to F-Droid

Guess you meant "to Github releases" :wink: I'm calling in from IzzyOnDroid here. And yes, that seems to be properly signed (release key), and the signature matches. Just manually triggered an update to see that it goes through, went smooth as butter. One thing the scanner showed was:

    ! repo/network.loki.messenger_3791.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

which can easily be avoided with a tiny addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks a lot! Feel free to close this issue (signing problem is solved), or adjust the `build.gradle` first and close then :wink:

**Comment by IzzySoft** [comment]
One more thing: Seems like the latest release added MLKit. Now we're getting in an area where the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy) gets heavily stretched and I need to evaluate whether we can keep Session in still:

* APK size is already twice the per-app size limit of 30 MB
* there were already the `NonFreeNet` and `NonFreeComp` anti-features set, now we'd also need to add `Tracking`
* there were already 3 non-free components (Google Cloud Messaging, Google Mobile Services, Firebase), now we have a forth (MLKit)

Is there any chance we can solve some of those, or would we need to remove Session from IzzyOnDroid?

**Comment by KeeJef** [comment]
Looking into this now, will provide some clarity soon

**Comment by AL-Session** [comment]
@IzzySoft Just a quick update, the wrong signing key was used on the release (which has now been addressed in more recent updates), and we have removed MLKit and replaced it with ZXing (Zebra Crossing) for all QR code recognition. The zxing work has passed QA and will be available as part of an upcoming release.

**Comment by ThomasSession** [comment]
We will also rework our build types in future releases so that the non-store builds will exclude the dependencies binary.
This will come in a later release, but is in our pipeline.

**Comment by IzzySoft** [comment]
Cool, thanks! Looking forward to the next releases then. The scanner here will notify me once an anti-feature should be dropped (here: MLKit, Google Mobile Services and Firebase dropped would send me a notice to remove NonFreeComp); if you just drop some of them, give me a ping and I'll update the AF description to reflect that.

**Comment by KeeJef** [comment]
1.19.2 is out now, and signatures are all correct again, closing this for now

**Comment by IzzySoft** [comment]
1.19.2 was pulled fine, and I can confirm the signing issue resolved as well as MLKit being gone. What is still left is `DEPENDENCY_INFO_BLOCK`. Will you address that, at least for the APKs (`includeInApk = false`)?

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Concerning the remaining proprietary components (GMS/FCM/Firebase), there are other issues open addressing them; especially #558 sticks out in this context, so I'll leave my corresponding note(s) there.

**Comment by ThomasSession** [comment]
Thanks! 
We really want to consider alternative options for notifications. We're a small team so everything  needs to be prioritised.
Rethinking our build flavour is on our upcoming list of tasks, and that's where we'll make sure to remove `DEPENDENCY_INFO_BLOCK` in the APKs (the aab can keep it for the store).

**Comment by IzzySoft** [comment]
Thanks @ThomasSession – and ack for the AAB.
