### ISSUE TITLE
[BUG] JCenter Sunset on August 15th, 2024

### ISSUE THREAD

**Issue by linsui** [oxen-io/session-android#1616]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JCenter is used. https://jfrog.com/blog/jcenter-sunset/

### Expected Behavior

Libs from JCenter should be replaced or updated.

**Comment by ThomasSession** [comment]
Hi there!
That's absolutely right!
We have a build with changes about to be pushed today to fix this.
And another version after that to finish off this task entirely.

**Comment by ThomasSession** [comment]
This has now been addressed in the latest 1.19.1 release.

**Comment by linsui** [comment]
Thanks!
