### ISSUE TITLE
Messages and Conversations that were deleted months ago randomly reappear.

### ISSUE THREAD

**Issue by AztecCodes** [oxen-io/session-android#1642]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**How the bug occured:**
1. Started a new conversation with someone.
2. Set up a timer to delete messages automatically 
3. Also manually deleted messages
4. Months later the whole chat randomly reappeared in the app. This happened multiple times and also happens to my friends on iOS.

This happened on multiple session accounts and on different Android phones.

### Expected Behavior

I expect that deleted messages stay deleted and don't randomly reappear months later.

### Steps To Reproduce

1. Start a conversation
2. Set up a timer
3. Send messages and receive messages
4. Wait a few weeks/months.

There is no way I know how to reproduce this bug guaranteed.

### Android Version

Android 14

### Session Version

1.19.1 (3795 - 09e461)

### Anything else?

I can't tell in which versions this bug occurs. However it just happened recently again.

My friends report me this issue from time to time too. It doesn't happen very often and it generally happens after longer timespans.

Fast Mode is activated.

**Comment by KeeJef** [comment]
Since we released our updated version of disappearing messages, local deletion timers will sync with the network deletion timers. So this shouldn't be occurring anymore on modern versions of Session past 1.17.6 let me know if it continues to occur / or if you have a reproducible case for it on the latest versions of Session Android.

**Comment by AztecCodes** [comment]
I can't really tell if it happened after this version. I will close the ticket and reopen one if the bug reoccurs.
