### ISSUE TITLE
External profile image not loaded

### ISSUE THREAD

**Issue by EchedeyLR** [oxen-io/session-android#185]
**Describe the bug**

After connecting with an user, a image already put by that person is not loaded from my side, being displayed a default image.

**To reproduce**

Create a new Session ID and connect with a user who already had a profile image.

**Screenshots or logs**

![Screenshot_20200429-195632](https://user-images.githubusercontent.com/56733813/80636051-b82c0500-8a54-11ea-98cb-c3c0e1e6867e.png)

**Smartphone (please complete the following information):**

 - Device: BQ Aquaris U Plus
 - OS: LineageOS 14.1 from microG
 - Version of Loki Messenger: 1.1.0.495

**Additional context**

In my case this happened after resetting Session from the settings panel and created a new ID. Before of that, this mobile was linked to other desktop client.

**Comment by nielsandriesse** [comment]
It's expected that you don't see their profile picture until you're friends. Did the profile picture still not show after they sent you a message?

**Comment by EchedeyLR** [comment]
> It's expected that you don't see their profile picture until you're friends. Did the profile picture still not show after they sent you a message?

Yes, this is why I made the report. After being friends, the image was not showed. I cannot confirm in new releases trying again from scratch because I am not using Session anymore by now.

**Comment by pjv** [comment]
I am experiencing the same issue with Session Android 1.2.4. Friend / Session requests have been accepted on both sides, able to send texts back and forth, but no profile image.

**Comment by schattenpanzer** [comment]
session 1.5.0, still no profile pictures from others, even friends

**Comment by 123chuck123** [comment]
I'm on 1.5.3 we both use android and none of us can see each other's profile picture.
![18104](https://user-images.githubusercontent.com/37484367/93028751-3230e500-f616-11ea-9d42-870177ce1804.png)

**Comment by Brice-W** [comment]
This should be fixed
