### ISSUE TITLE
Add option to silence a chat "Forever"

### ISSUE THREAD

**Issue by EchedeyLR** [oxen-io/session-android#186]
This is just a report for feature request. The idea is to add an additional option in a future to be able to silence a group without a time limit like other chat applications.

![image-1422163589](https://user-images.githubusercontent.com/56733813/80672728-66f83180-8aa5-11ea-8d86-90b203b9b679.png)

**Comment by brecla** [comment]
I also like the "notify only when mentioned" option on session-desktop that is also available on major IRC and XMPP clients

**Comment by EchedeyLR** [comment]
I think that should be in other issue as has nothing to do with muting a chat.

**Comment by hjubb** [comment]
we have the ability to mute a chat forever, as well as notify only when mentioned now
