### ISSUE TITLE
Picture and UI problems

### ISSUE THREAD

**Issue by zcstrife** [oxen-io/session-android#194]
Hello,

Here is a list of problems that I found after 1 day of use:

- Some pictures can't be opened in a discussion, short/quick press does nothing. 
- Long user names hide checkbox when adding member to a group.
- Long user names hide date of the last message in the thread list.
- Long messages hide message state (failed, sent, received, read) in the thread list.
- Camera and Mic icons do not show in discussion (randomly).

Others problems:
- When a new message is a picture, the last  written message shows in the thread list, which is confusing. *Document type* would be preferable.
- No ways to remove a threads (?)

**To reproduce**
Does not apply or self explanatory

-------------------------------------------
 - Device: Hisense A5
 - OS: Android 9
 - Version of Session: 1.1.0

**Comment by Brice-W** [comment]
I believe this is all fixed now
