### ISSUE TITLE
Can't send or receive message with Data Connection

### ISSUE THREAD

**Issue by zcstrife** [oxen-io/session-android#197]
Hi,

I have to enable wifi to use session. On mobile data,  nothing go through.

-----------------

 - Device: Hisense A5
 - OS: Android 9
 - Version of Session 1.1.0

**Additional context**

All others apps works perfectly on mobile data, whatsapp, browsers, etc...
Could it be my network operator, blocking session? I live in France.

I need help, i'm rarely using wifi.
Also I got 4 friends to install session just for me, saying that I will leave whatsapp, but I can't even use it myself.

**Comment by zcstrife** [comment]
Does anyone else have that problem?
Still no way to use session without wifi.
I get a "failed to deliver" notification, and on the message it says "send failed, tap for details", details being "some issues need your attention" and a button to resend.

This is a huge problem for me, I can work with UI problems and notifications delays, but if I can't even use it without wifi, what the point.

**Comment by Skelaton4** [comment]
I haven't personally had this issue on Android but there will be an Android update coming soon that will incorporate many of the same fixes as the most recent Desktop+IOS versions. 

Hopefully that will fix this issue; you are correct if it doesn't work on data, what is the point.

**Comment by zcstrife** [comment]
> I haven't personally had this issue on Android but there will be an Android update coming soon that will incorporate many of the same fixes as the most recent Desktop+IOS versions.
> 
> Hopefully that will fix this issue; you are correct if it doesn't work on data, what is the point.

i installed 1.2.0, no change, message fail trying to "trace a path".

Also, as i tried to update, there was a problem, and it asked me to first uninstall session. So i copied my recovery phrase, uninstalled session 1.1.0, installed 1.2.0, entered my recovery phrase... but i had to reenter my pseudo, reupload my picture, and all my contacts were lost

**Comment by hjubb** [comment]
If this is still an issue in the latest version, please feel free to re-open. synchronizing your profile information after restoring your account from recovery should no longer be an issue either :+1:
