### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [oxen-io/session-android#198]
Would help improve the poor quality of the string-base.

**Comment by EchedeyLR** [comment]
If it could help, I agree with it as to avoid using the other propietary services for similar purposes.

**Comment by comradekingu** [comment]
All the other forks are on Hosted Weblate now.
I can help set up shop at https://hosted.weblate.org/hosting/ :)
Or add https://hosted.weblate.org/user/kingu/ once set up.
