### ISSUE TITLE
Swipe left to reply [feature request]

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#203]
![anigif_sub-buzz-15901-1502379384-1](https://user-images.githubusercontent.com/66033666/83061844-f0c3fc00-a05d-11ea-996a-607e072647cf.gif)

Most popular messaging applications have the opportunity to swipe left on a message to reply to them. For now, Session only has - press and tap reply button -.  Adding this functionalty would increase user experience.

**Comment by hjubb** [comment]
Latest versions of Session now feature a swipe to reply experience :+1:
