### ISSUE TITLE
Add client-side Nicknames

### ISSUE THREAD

**Issue by OlderNews** [oxen-io/session-android#225]
Request- Nicknames for users

As many users have random names on Session, it would be great to add a nickname to the contact such as "Garry from Melbourne" just a short phrase so you can't forget who people are. 

This will make it easier to remember who people are and reduce the chance of an embarrasing encounter.

**Comment by trymeouteh** [comment]
+1 for contacts management. To have a contacts section were you can add names to your contacts and easily import/export this contact list and have it sync between your devices.

**Comment by nielsandriesse** [comment]
Hi @OlderNews, this feature has now been implemented (version 1.10.8)!
