### ISSUE TITLE
Session uses legacy storage permission

### ISSUE THREAD

**Issue by cyborgninjaneer** [oxen-io/session-android#248]
The legacy "Storage" permission has been depreciated since Android 4.4 when the Storage Access Framework was introduced. It will be removed in Android 11, making Session incompatible. Session needs to switch over to the Storage Access Framework for sharing files and photos.

Furthermore, using the legacy Storage permission does not respect user privacy since it requires access to all files, not just specific ones. This will lead some users to distrust the app and its developers - it's a bad look for a privacy-oriented messenger.

**Comment by nielsandriesse** [comment]
Hi @cyborgninjaneer, we fixed this now. Thanks for pointing it out!
