### ISSUE TITLE
Show, display and allow copy of session partner's Session ID

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-android#254]
When I have a session (one-to-one chat) with a partner, there is no way to see, display or copy my partner's Session ID. When I am viewing a session, in the top bar I only see my partner's display name and half of their Session ID, and I cannot copy their Session ID to the clipboard.

Am I just not seeing how to do this, or is this feature missing?

As a comparison, in open groups I can tap and hold a message and copy the Session ID of the message's author, though I cannot see or display their full Session ID. I don't know if copying or displaying are possible in closed groups.

Suggestions:

- In the list of sessions and groups (the first screen of the app), display a partner's details (including Session ID) when their circle is tapped.
- Inside a session, display the partner's details (including Session ID) when the top bar is tapped.
- Allow the user to copy a partner's Session ID to the clipboard.
- Inside a session, make the partner's full Session ID visible in the top bar. Make the full Session ID left-to-right scrollable or wrap it over 2 lines. *Note: This is nice to have, but may end up being very small or not possible due to space constraints.*

Version: Session Android 1.2.3

**Comment by nielsandriesse** [comment]
Great suggestion! No idea why we don't have this yet. Added it to our to do list :)

**Comment by LongJohn-Silver** [comment]
This is already released, shouldn't this be closed now? @nielsandriesse

Well, last point of OP is not yet added but IMO that should wait until there is a full profile page like Signal does.

**Comment by beantaco** [comment]
Some of the suggestions have been added. I can copy a partner's Session ID, and I can hold-tap a session (when viewing the first screen) to bring up the partner's details (including Session ID). Therefore, the user can now obtain their partner's Session ID.

Although my last point has not been added as @LongJohn-Silver has commented, I think the features already added are good enough to warrant closing this issue.

**Comment by beantaco** [comment]
I'll close this issue since there are at least 2 ways to copy a session partner's Session ID that have been added:

- press the three dots -> Copy Session ID
- long press the session -> Details -> Copy
