### ISSUE TITLE
Allow message TTL (time to live) to be controlled by recipients

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-android#262]
Assuming I understand TTL (time to live) correctly, if a Session user doesn't touch their device or stay offline for days or weeks, they will fail to receive messages. A short TTL makes user check their incoming messages frequently in order to avoid losing messages.

Session Desktop has a setting that allows the **sender** to change TTL. The default TTL in Session Desktop was 24 hours. Making users check their Session messages daily is clearly undesirable. Although the default TTL in Session Desktop was extended to 1 week (see [session-desktop PR #1089](https://github.com/loki-project/session-desktop/pull/1089)), some users may lower their own setting to as low as 12 hours, causing headache for recipients who aren't glued to their devices.

The default TTL in Session iOS was extended. See [session-ios PR #161](https://github.com/loki-project/session-ios/pull/161).

Session Android 1.2.5 has no TTL setting.

My request is a TTL setting for either the **recipient** or **session**. That way the recipient has control over TTL and can adjust it to their needs.

I acknowledge there are likely privacy/security implications of extending TTL or allowing individual sessions to have their own TTL value, and message storage issues if TTL is too long. Furthermore, for the little I know about the Loki network and infrastructure, allowing the recipient or session to change TTL may require changes to how the network/infrastructure operates. For example, there appears to be a relationship between TTL and PoW (proof of work) difficulty.

# About TTL

According to [this Loki news page (2019-11-26)](https://loki.network/2019/11/26/loki-messenger-breaks-new-ground/):

> The TTL is the time that the message will be stored on the receiving Loki Service Node swarm before being deleted (this storage-and-deletion process occurs if the recipient is offline at the time of the message being sent).

> The default TTL for messages is 24 hours. This means that if your secondary device is turned off (or otherwise offline) for more than 24 hours, its sent message history will become out of sync with the primary device.

**Comment by nielsandriesse** [comment]
We'll increase the TTL significantly in the future, but in order to do that we'll first need to replace proof of work with a better mechanism. Otherwise the encryption step will take too long.

**Comment by beantaco** [comment]
After some rough testing, between Session Android 1.6.7 and Session Desktop 1.4.4, I have found that messages must be received within 48 hours or else the recipient will fail to receive their messages.

I hope the TTL can be extended to at least 1 week or be made configurable.

**Comment by nielsandriesse** [comment]
The default TTL is 2 weeks now.
