### ISSUE TITLE
Can't listen to long audio messages

### ISSUE THREAD

**Issue by gitmaker032** [oxen-io/session-android#279]
If somebody records a long audio message (about over a minute), it is impossible to listen to it. After pressing the Play button, nothing happens, the audio does not load. Only short audio messages work as expected. Apparently, if the size of an audio file exceeds a certain limit, it is not transmitted :(

Session version: 1.4.1
OS: Android 10

**Comment by klochden** [comment]
Same here. But not even a long audio message but all audio messages are inaudible!

**Comment by sc0w** [comment]
seeing release notes, it seems to be the expected:

https://getsession.org/session-release-roundup-10/

` Voice messages limited to one minute duration. iOS, Android`

I am wondering why

**Comment by nielsandriesse** [comment]
This should be fixed now.
