### ISSUE TITLE
[Feature request] 2x speed for voice messages

### ISSUE THREAD

**Issue by gitmaker032** [oxen-io/session-android#315]
Very long voice messages, but very little time :)  Therefore, this feature is necessary.  It is important that the speed state is individual for each chat (if at least one voice message in the chat was set to 2x, all received voice messages in this chat will be played in 2x speed).

**Comment by gitmaker032** [comment]
I'm really looking forward to this feature on Android. It is already available on ios.

**Comment by nielsandriesse** [comment]
This will be done as part of the upcoming conversation screen redesign :)

**Comment by nielsandriesse** [comment]
We have this now. You can double tap a voice message as it's playing to speed it up to 1.5x!

2x was a bit * too * fast :)

**Comment by gitmaker032** [comment]
I've been waiting a long time for this feature) But I think it is implemented inconveniently and not very logical. How a person who has not read the documentation can guess that the double tap triggers speed up playback? Moreover, the single tap is set to pause, and the double tap to speed up playback. There is a very high chance of mistakenly turn on the pause (in my experience), and not to turn on the necessary speed-up. About 2x... You say it was too fast. What voice did you test on? :) I have friends who speak very slowly and 1.5x is just not enough for them. I think there is something to work on here. Right now the feature is hidden deep and doesn't work very well. Better make a separate button for speed up (1.5x/2.0x) as implemented in Telegram or Threema.
