### ISSUE TITLE
Bad Encrypted Message, when opening synced Desktop App

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#361]
### Bug description
A lot "Bad Encrypted Message " errors in the chat window on Android, when opening Linux Desktop Client with the same (synced) ID. When closing synced Desktop App, conversation going fine. 

p.s. localization string key:
MessageDisplayHelper_bad_encrypted_message

### Sender desktop device info

**Android version:** Ubuntu Linux 20.04
**App version:** v1.3.1

### Sender mobile device info

**Android version:** 10
**App version:** 1.5.4 (995)

### Recipient mobile device info

**Android version:** 9
**App version:** 1.5.4 (995)

**Comment by Y0lan** [comment]
I have the same problem but using the android app. Most of the times Session works fine, but sometimes I can't chat with someone because there is too much "Bad Encrypted Message"... 
Thank you.

**Comment by KeeJef** [comment]
Which app version are you using? and what is the version of the app your chat partner is using?

**Comment by Y0lan** [comment]
latest version on my part, no idea for my partner.

**Comment by Y0lan** [comment]
Since we can not see each others messages I can not tell you his version. :(

**Comment by KeeJef** [comment]
This issue should be resolved now that we have switched from the Signal protocol to the Session protocol
