### ISSUE TITLE
Couldn't join group? 

### ISSUE THREAD

**Issue by yuis-ice** [oxen-io/session-android#380]
I am new here so sorry if I'm saying something totally not bug. 

I downloaded the app for windows here [Download - Session Private Messenger](https://getsession.org/download/)

Installed, launch, create a new account, turned off vpn (just in case, idk), open group url, type "chat.getsession.org", it said "Couldn't join group" as screenshot below

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_1136b637-924b-4c98-b0ee-cf1c3530e7a7.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_1136b637-924b-4c98-b0ee-cf1c3530e7a7.png)
![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_08890fcc-6d5c-41f8-8bbd-6cc34a12ed9c.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_08890fcc-6d5c-41f8-8bbd-6cc34a12ed9c.png)

**Comment by feroxaquila** [comment]
I can't join the Feedback Session group on my mobile phone https://feedback.getsession.org 
I'm using the same link on PC and Mobile phone but only with my phone, it doesn't work. Before I got the message joining failed, but now it's just loading forever and nothing happens.
Strange thing is that I can join groups like 'Session Public chat' and 'Loki Public Chat'

Smartphone (please complete the following information):

Device: Huawei p20, EML-L29
OS: Android 10
Version of Session: 1.6.3 (1185)

**Comment by nielsandriesse** [comment]
This is a desktop issue, not an Android issue.
