### ISSUE TITLE
The avatar flashes when switching back to the main page from the chat page 

### ISSUE THREAD

**Issue by jamesmccoy0405** [oxen-io/session-android#387]
**Describe the bug**

When switching back to the main page from the chat page, the user avatar and group avatar will flash once, from the avatar color to black, and then back to the avatar color, sometimes it is two times, which takes a short time and cannot take a screenshot.

**To reproduce**

1. Open a chat page
2. Go back to main page

**Screenshots or logs**

The log file has been uploaded to google drive
https://drive.google.com/file/d/1Xclp9MfxZTPNBX4DG6ndMcRhDKH5qej9/view?usp=drivesdk

**Smartphone (please complete the following information):**

 - Device: essential ph-1
 - OS: android 10 (QQ1A.200102.032)
 - Version of Session: 1.6.4

**Additional context**

**Comment by jamesmccoy0405** [comment]
The log file has been re-fetched.
https://drive.google.com/file/d/1XE3RcoIWDk5s0-BYzVoPrE5BzG50DzZS/view?usp=drivesdk

**Comment by jamesmccoy0405** [comment]
The screen recording file has been uploaded to YouTube
https://youtu.be/C6USpG6ZEnI

**Comment by hjubb** [comment]
@jamesmccoy0405 I believe this is fixed now, please let me know if the issue persists in the current version

**Comment by jamesmccoy0405** [comment]
Thx, the bug was fixed.
