### ISSUE TITLE
Bad encrypted message/you reset secure session

### ISSUE THREAD

**Issue by christianwells11** [oxen-io/session-android#388]
**Describe the bug**

Getting many notifications for bad encrypted message. When I go to the conversation, it's an endless list saying you reset the secure session. This makes Session useless to communicate with individuals; public groups are working fine, though.

**To reproduce**

Not doing anything I know of to cause this.

**Screenshots or logs**

![Screenshot_20201201-201628](https://user-images.githubusercontent.com/31749525/100931473-95654180-34b8-11eb-885d-9fe15c7fe5f1.png)

**Smartphone (please complete the following information):**

 - Device: Google Pixel 5
 - OS: Android 11
 - 1.6.4 (1215)

**Additional context**

NA

**Comment by KeeJef** [comment]
Theres some upcoming fixes for this in the pipeline

**Comment by LongJohn-Silver** [comment]
Same here, Samsung J4 Android 10 version 1.6.4, I just updated it to 1.6.5 but I don't know if this keeps happening, it hasn't happened so far but I haven't used it that much since I started to receive these errors.

**Comment by KeeJef** [comment]
This issue should be resolved now that we have switched from the Signal to Session protocol
