### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by JeffRockatansky** [oxen-io/session-android#389]
**Describe the bug**

Session often lags and stutters while writing and sending messages.

**To reproduce**

* Nothing specific really, just write and send messages to someone on a setup similar to mine

**Screenshots or logs**

Don't really know how to access logs on Android. Can't be screenshoted. Maybe will try to do a screen video capture later.

**Smartphone (please complete the following information):**

 - Device: Xiaomi Redmi Note 4 MTK (nikel)
 - OS: Android 6.0 Marshmallow (latest official ROM for the device, rooted)
 - Version of Session: 1.6.6 (F-droid)

**Additional context**

There's also sometimes a toast message about wrong time zone, but my clock is automatically synced. Will screenshot it when it comes up again.

**Comment by JeffRockatansky** [comment]
Still an issue in Session 1.8.1

**Comment by Sepero** [comment]
OnePlus 6 + Android 10
Session: 1.9.1

I just wanted to report having this issue also for multiple versions of Session. It appears that Session regularly enters some kind of process intense background loop that lasts for a very long time (several minutes with screen on). My phone is not a Snapdragon 855, so I would expect most apps to be able to complete any needed processing within at most a couple seconds. The background process not only causes Session to lag, but also every other app and the system. Also, no steps to reproduce the behavior, just opening Session on a fresh boot can be a trigger. I have attached a screenshot with Termux of the CPU at high use.
![Screenshot_20210502-114423__01](https://user-images.githubusercontent.com/1575546/116802566-e481d200-ab3d-11eb-8f5e-05fba82fd788.jpg)

**Comment by Sepero** [comment]
Still having this background process issue in version 1.10.4. I noticed my phone lagging again, so I opened htop in termux to monitor the situation. These were my results (times are approximate).

1. 4 minutes high CPU
2. 15 seconds idle 
3. 2 minutes high CPU
4. 15 seconds idle
5. Continue high CPU (stopped timing)

In the end I swiped Session out of memory so I could go about using my phone as normal again without lag. In older versions I used to get messages about clock out of sync, but I no longer get those messages anymore.

If there is anymore information I can give on this, then please let me know and I'll try to provide.
![Screenshot_20210518-074419](https://user-images.githubusercontent.com/1575546/118576529-e5a83580-b7b2-11eb-84f5-11dd9db64dbb.jpg)

**Comment by nielsandriesse** [comment]
Performance should now be * much * better. Going to close the issue :) .
