### ISSUE TITLE
Issue linking phone to desktop

### ISSUE THREAD

**Issue by Vepnar** [oxen-io/session-android#393]
**Describe the bug**

There is no device button on the settings menu. While a toast message tells me to go to settings and press the device button when I'm trying to link my phone to my desktop

**To reproduce**

1. Attempt to link the phone (master) to a desktop (slave)
2. Go to settings to link the devices

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/26712719/103482808-378f8680-4de3-11eb-8037-649de5043ff4.png)

**Smartphone (please complete the following information):**

 - Device: Oneplus 6
 - OS: Android 10; OxygenOS 10.3.7
 - Session version: 1.6.7.1 (1295)

**Additional context**

None.

**Comment by KeeJef** [comment]
Device linking is not officially supported, we will be adding multi device back to the application with an improved implementation soon

**Comment by Vepnar** [comment]
Thank you for your answer. I'll look forward to see this feature implemented.

**Comment by AstroGD** [comment]
+1 - Hope to see it implemented soon
