### ISSUE TITLE
Help in Building this app

### ISSUE THREAD

**Issue by crusaderkarthik** [oxen-io/session-android#397]
Hi All, 
I am trying to build this app on Android Studio, but I am unable to do that.
Can any one help me building this app. 
Thank you and looking forward for replies

You can also send me a link of documentation on how to build this app

**Comment by hjubb** [comment]
hey @crusaderkarthik the latest `dev` branch should be a lot easier to build from source! the external android service dependencies have been brought into this repo

**Comment by crusaderkarthik** [comment]
Hey @hjubb 
Thanks for the reply. 
I will try and will let you know :)

**Comment by crusaderkarthik** [comment]
Hey @hjubb 
I need help from you buddy. 
How can I contact you dude ?

**Comment by hjubb** [comment]
drop me a dm on twitter if you'd like, link is in my profile :+1: otherwise if you're on the oxen channels on TG or session send a msg there :)

**Comment by hjubb** [comment]
have just improved the docs on https://github.com/oxen-io/session-android/blob/master/BUILDING.md to remove the outdated instructions, let me know if this helps as well :)
