### ISSUE TITLE
Crashes when trying to select your own message in a group chat

### ISSUE THREAD

**Issue by j-greffe** [oxen-io/session-android#406]
**Describe the bug**

Session stops when I try to select (long touch on the message) my own messages in a group chat.

In a chat:
- Selecting received messages works
- Selecting sent massages works

In a group chat:
- Selecting received massages works
- **Selecting sent messages crashes the app**

**To reproduce**

Go to a group chat and select a message you sent.

**Screenshots or logs**

How do I get the logs?

**Smartphone (please complete the following information):**

 - Device: HTC One M8
 - OS: Android 6.0 Marshmallow
 - Session 1.6.10 (1335)

**Comment by Ax9D** [comment]
> **Describe the bug**
> 
> Session stops when I try to select (long touch on the message) my own messages in a group chat.
> 
> In a chat:
> 
> * Selecting received messages works
> * Selecting sent massages works
> 
> In a group chat:
> 
> * Selecting received massages works
> * **Selecting sent messages crashes the app**
> 
> **To reproduce**
> 
> Go to a group chat and select a message you sent.
> 
> **Screenshots or logs**
> 
> How do I get the logs?
> 
> **Smartphone (please complete the following information):**
> 
> * Device: HTC One M8
> * OS: Android 6.0 Marshmallow
> * Session 1.6.10 (1335)

**Here's the stack trace,**
![session_stack1](https://user-images.githubusercontent.com/40864118/106167839-a6c68380-61b3-11eb-929d-afc679a79a2f.jpg )
![session_stack2](https://user-images.githubusercontent.com/40864118/106167850-a8904700-61b3-11eb-891c-a445042fa72d.jpg)
![session_stack3](https://user-images.githubusercontent.com/40864118/106167855-a9c17400-61b3-11eb-818f-82b6f306b1aa.jpg)

Problem originates from this line maybe? 
https://github.com/oxen-io/session-android/blob/8d440060b17e423317bd0b59358dbf43c72ffca4/src/org/thoughtcrime/securesms/conversation/ConversationFragment.java#L416

**Comment by Brice-W** [comment]
This bug has been fixed
