### ISSUE TITLE
Add in Chat Check icon

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#409]
### Bug description
If use Desktop version and send message, i see this icon and know user read my message
but if use Android client i can see this only if exit in chat and see user list

**Expected result:**
it would be great if this could be seen in the android / ios chat as well how in the Desktop version

### Screenshots

![check](https://user-images.githubusercontent.com/43858033/105874695-8d7fd480-6005-11eb-92c8-6ae4a0c50b0e.png)

**Comment by klochden** [comment]
Yes, I noticed the same! Please add these icon in android app as well.

**Comment by gitmaker032** [comment]
I agree. It is very inconvenient not to see in the chat if the message is read or not. I made a similar request a few months ago. It was closed, but there was no change.

**Comment by nielsandriesse** [comment]
This will be done as part of the upcoming conversation screen redesign.

**Comment by xbvrhlmb** [comment]
@nielsandriesse 
it seems to be done, but it is visible only under the last messages and not over all.

**Comment by KeeJef** [comment]
Read receipts should be present on all platforms now
