### ISSUE TITLE
Translate button Invite in Menu

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-android#414]
### Translate 
I not find in translate file this button, please add translate in this button in menu, maybe in iOS app version too

**Example RU:**
Invite = Пригласить

### Screenshots
![invite](https://user-images.githubusercontent.com/43858033/106383905-09489b00-63d1-11eb-84c3-017b1ed2a683.png)

### Device info
**Session version:** 1.6.11 (1345)

**Comment by Brice-W** [comment]
This should be fixed
