### ISSUE TITLE
Saving MP4 Files To MP4 Files

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-android#427]
**Describe the bug**

When you save a MP4 file it saves its a 3GP file

**To reproduce**

Send or receive a MP4 video file
Save the video to your phones storage

**Smartphone (please complete the following information):**

Device: Samsung Galaxy S8
OS: Android 9
Sessions 1.6.12

**Comment by hjubb** [comment]
This should be fixed :+1:
