### ISSUE TITLE
Cannot Save Audio Files

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-android#428]
**Describe the bug**

Cannot save any audio files to phone storage

**To reproduce**

Send or receive any MP3, FLAC, M4A file
Save it to phones storage

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Sessions 1.6.12

**Comment by nielsandriesse** [comment]
This should be fixed :)
