### ISSUE TITLE
SMS & Phone Call Syncing

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-android#434]
A cool feature Session could add which no other free open source app does is allow you to send and receive SMS messages and have outgoing or incoming calls from your other mobile devices like tablets and desktop devices. Session can use its encryption and Tor like IP cloaking technology to ensure the connection from your phone to your other devices when sending or receiving SMS messages or on a phone call is secure and private as it can be.

This can also make Session a SMS and Dialer app on Android, making Session the all-in-one ecosystem for communication.

**Comment by patoshii** [comment]
+1

**Comment by beantaco** [comment]
Can you please elaborate on the role of Session's protections (eg: end-to-end encryption and onion routing) in relation to sending and receiving SMS and phone calls? I discuss SMS/call handling apps below, but I may be missing something about this feature request.

There exists free open source software that handles SMS and phone calls. Signal has (optional) support for handling SMS and phone calls, but SMS and phone calls are not afforded protection that Signal messages/calls are given (eg: end-to-end encryption).

However, personally I believe including such a feature in Session is a mistake. Such a feature has the following risks that would violate Sessions's goal/value/priority of privacy:

- Session users could mistakenly communicate over SMS and phone calls (non-secure channels). This can happen either by mis-operation ("hitting the wrong button") or by wrongly assuming SMS and phone calls handled by Session are afforded Session's protections. Such mistakes would result in exposure of sensitive information or enable identification/tracking of Session users.
- Session clients would require permissions (eg: contacts, camera, microphone) in order for SMS/call handling to function properly.

**Comment by PopeNobody** [comment]
I intend to build something similar to this for another project.

The plan is to have a communications architecture which allows it to use any real time messaging system to communicate.  This is because we fear being deplatformed, and we want to keep working as long as anybody will carry our traffic.

**Comment by mesh4545** [comment]
> I intend to build something similar to this for another project.
> 
> The plan is to have a communications architecture which allows it to use any real time messaging system to communicate. This is because we fear being deplatformed, and we want to keep working as long as anybody will carry our traffic.

A similar app exists, but I don't think it's actively developed anymore... 
https://git.silence.dev/Silence/Silence-Android
