### ISSUE TITLE
Linux Mobile Client?

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-android#435]
Would be amazing to have the desktop client work on mobile linux devices with a good UI or a mobile linux client. This way even new Linux phone users wont miss out on Session ecosystem.

**Comment by invalid-error** [comment]
When Linux than it should be in the desktop issue section. This would be: https://github.com/oxen-io/session-desktop/issues/1304

**Comment by JeffRockatansky** [comment]
This should be closed then

**Comment by Xeoneid** [comment]
I think so, this issue should be closed
