### ISSUE TITLE
"Screen Lock" Feature doesn't work

### ISSUE THREAD

**Issue by TuxKruger** [oxen-io/session-android#448]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Enabled "Screen Lock" in Privacy Settings, then closed the app and cleared it from the Recents menu (background apps or whatever you call it), opened the app and Screen Lock doesn't work, it straight up opens the main screen. Ofcourse I have set up a fingerprint lock on my phone and yes, it works well with Signal Messenger. (I have added a link to a screen recording below that can better explain what I am trying to say)

### Steps to reproduce
- Enable "Screen Lock" in Settings > Privacy.
- Close the app and clear it from recents.
- Open the app.

**Actual result:**

Main screen opens straight up without asking for fingerprint.

**Expected result:**

The app is supposed to ask for fingerprint after every launch if Screen Lock is enabled.

### Screen recording
[Here's the video](https://drive.google.com/file/d/1-hgB0R8Z_hrt58xbKs8ECZ8MDT8CZtzx/view?usp=drivesdk)

### Device info
**Device:** Redmi Note 9S

**Android version:** 10

**Session version:** 1.7.1

**Comment by LorisTecnology** [comment]
same thing happen to me on mi a2

**Comment by TuxKruger** [comment]
Seems like it is not a MIUI related issue. I flashed LineageOS 18.1 a few hours ago and faced the same bug when I force stopped session after enabling Screen Lock.

**Comment by TuxKruger** [comment]
Seems like v1.7.3 fixed the Screen Lock issue for me.
