### ISSUE TITLE
Wrong order of messages while using multiple devices

### ISSUE THREAD

**Issue by klochden** [oxen-io/session-android#454]
Session 1.7.2 installed on Android 11 Smartphone (Galaxy S 10 Plus) and Windows 10 Desktop (1.4.9). 
While chatting on windows desktop (private chat), the messages on android, are shown in a completely wrong order.

**Comment by KeeJef** [comment]
this should be fixed in 1.7.3 +, messages were being ordered by the wrong timestamp
