### ISSUE TITLE
v1.7.3 installed from Google Store crashes instantly 

### ISSUE THREAD

**Issue by HostFat** [oxen-io/session-android#463]
After upgrading to the new v1.7.3, it now crashes instantly.

It can't be used.

**Comment by Abu-Khulzat** [comment]
Same here. The app crashes instantly after today's update on Galaxy s21 ultra, Android 11

**Comment by klochden** [comment]
Same here too! No possibility to start the app. It crashes immediately. Galaxy S10 plus (Android 11)

**Comment by HostFat** [comment]
Solved with the v1.7.4
