### ISSUE TITLE
Session App closing after launching app after I restored from a backup

### ISSUE THREAD

**Issue by abbasmaheryar** [oxen-io/session-android#466]
**Describe the bug**

I installed the session app on my new phone, and I imported a backup to use. Once I restored the backup, my messages were shown, as expected. However, when I closed the app, and launched it again, session no longer launches as expected, and immediately quits.

**To reproduce**

- Install Session app from APK
- Restore from backup
- Enter 30-digit passcode
- Once messages are restored, close the app
- Attempt to launch the app again

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S21 5G
 - OS: Android 11
 - Version of Session or latest commit hash: 1.7.3-arm64-v8a

**Comment by j-greffe** [comment]
I don't know if this is related but for me the app now straight up crashes at launch.
I didn't do anything, it worked fine yesterday.

HTC One M8
Android 6.0
Session 1.7.3

![Screenshot_20210227-082909](https://user-images.githubusercontent.com/8793576/109390001-59067d80-790f-11eb-87ba-42aa3b0be079.png)

**Comment by KeeJef** [comment]
this should be fixed in 1.7.4 which addresses a crash on startup for certain devices
