### ISSUE TITLE
Can't view entire image in chat.

### ISSUE THREAD

**Issue by seansnydercc** [oxen-io/session-android#471]
### Bug description
I can't view the entirety of an image without saving it and opening it in a different app.  The top of the image is covered by a bar that contains: a back arrow, the sender, the time elapsed from sending, a share button, a save button, and a burger menu.

### Device info

**Device:** Blackberry Key2 (BBF100-2)

**Android version:** 8.1.0

**Session version:** 1.7.4 (1425)

**Comment by hjubb** [comment]
If you tap the image now it will let you fullscreen the image
