### ISSUE TITLE
Try optimize RAM in the background work

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-android#490]
try to optimize and reduce the amount of memory consumed when working in the background 

now he uses about 60-80 MB which is not a little
I'm not sure, but I think it's possible to do less (which will be useful for those with weak phones)
the application will also be much faster

**Comment by hjubb** [comment]
Will look into continuously improving the usage of resources and optimisations in the future

**Comment by nielsandriesse** [comment]
This is an ongoing effort, not one particular issue. Closing this for that reason :)
