### ISSUE TITLE
App can't be installed (probably due to missing SIM card)

### ISSUE THREAD

**Issue by mdPlusPlus** [oxen-io/session-android#491]
**Describe the bug**

App can't be installed via Google Play. Error message says "This device isn't compatible with this article."  

**To reproduce**

Open Google Play, search for "Session", click on install.

**Screenshots or logs**

![Screenshot_20210331-183350_Google_Play_Store](https://user-images.githubusercontent.com/9272131/113180333-e875b800-9250-11eb-9bd7-4a0b2080c3ce.png)

**Smartphone (please complete the following information):**

 - Device: Xiaomi Redmi Note 7 `lavender`
 - OS: LineageOS 17.1 (Android 10)
 - No SIM card, no mobile data, only WiFi

**Additional context**

I've read about Signal having the same issue with devices that didn't have SIM cards before. Maybe it is related to Session's past as a Signal fork?

**Comment by invalid-error** [comment]
Install f-droid
https://f-droid.org/

and add this repo:
https://fdroid.getsession.org/fdroid/repo?fingerprint=DB0E5297EB65CC22D6BD93C869943BDCFCB6A07DC69A48A0DD8C7BA698EC04E6

Source: https://getsession.org/faq >> 'Privacy'

It also works without SIM card

**Comment by mdPlusPlus** [comment]
Unfortunately that's not a solution to the problem. I can't tell people to enable unknown sources and install third-party app stores so they can add me on Session.

**Comment by hjubb** [comment]
Do any of the binaries distributed through the website or F-Droid install and run? If that is the case it might be an app store limitation for some app manifest declaration, might be able to pinpoint the issue for one of those in that case

**Comment by mdPlusPlus** [comment]
The F-Droid version installs and starts fine, so I assume it is a Play Store issue. Can I do anything to get this fixed?

**Comment by hjubb** [comment]
I'm not sure off the top of my head what might be preventing this from being installed via Google, but if there is any similar issues people have had and fixed they probably relate to a permission in `app/src/main/AndroidManifest.xml` if we can track that down and if it doesn't affect any other part of the app it might be a simple fix to delete whichever offending permission is listed there. Any help and PRs would be appreciated :)

**Comment by mdPlusPlus** [comment]
Unfortunately `adb logcat` does not put out anything useful during the failed installation.  
Would a `build.prop` help to pinpoint this issue? And if so, where to locate this file?

**Comment by hjubb** [comment]
not entirely sure where the issue stems from, but it might have something to do with a declared `<permission>` tag in the AndroidManifest.xml file

**Comment by mdPlusPlus** [comment]
Any way to debug this?

**Comment by hjubb** [comment]
Trying to build the application and install it to the offending device might give a failed installation and some message as to the reason behind it. But I fear if that doesn't give anything helpful and the issue is tied to some internal Google Play Store device incompatibility it would not be easy to track down. The application logs for the play store (tagged `finsky`) might also have some better info

**Comment by mdPlusPlus** [comment]
Okay, I have no idea what has changed in the time between opening this issue and now, but I was able to install Session via Play Store just fine right now.

**Comment by hjubb** [comment]
Great news @mdPlusPlus !
