### ISSUE TITLE
Hability to send messages from future

### ISSUE THREAD

**Issue by extremelf** [oxen-io/session-android#492]
**Describe the bug**

The hability to send a message from years ahead, and all the messages sent correctly will appear before the "message from future".

**To reproduce**

Change time in the phone to a year of choice.
Try and send a message in Session.
It will fail.
Change the time back to the correct.
Try and send again and it will be sent from the year set before.

**Smartphone: **

 - Device: Samsung Galaxy S10+
 - OS: Android  11
 -  Version - 1.8.1

**Comment by nielsandriesse** [comment]
Hi @extremelf, this is a known issue. The alternative is to order messages by date received, but in that case messages might appear out of order due to the decentralized nature of the Service Node network (message 1 might take longer to travel through the network and arrive after message 2).

**Comment by extremelf** [comment]
Hi, I get that but I guess the problem is that it blocks when trying to send with the wrong date/time but sends it when reset to true settings, although the message is still shown with that wring date/time

**Comment by nielsandriesse** [comment]
We have a solution for this now, which'll be deployed in the coming few days.
