### ISSUE TITLE
Display name is blanked when receiving messages sent by session desktop on the same session ID

### ISSUE THREAD

**Issue by chairmantheboring** [oxen-io/session-android#500]
**Describe the bug**

When linking session desktop and session android, using session desktop to send messages causes the display name to be blanked when Session Android receives messages sent by session desktop.

**To reproduce**

1. Make a new Session ID on Session Desktop
2. Receive a message from any Session ID
3. Link Session Desktop and Session Android
4. Send a message to the conversation in step 2 using Session Desktop.

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/70743311/114639817-462cea00-9cbe-11eb-9fda-d91d7d0e1751.png)

**Smartphone (please complete the following information):**

 - Device: OnePlus 7 Pro
 - OS: LineageOS 18.1
 - Version of Session or latest commit hash: Session Android 1.9.0 (1505) and Session Desktop 1.5.3

**Additional Context:**

Two linked Session Android instances (both are version 1.9.0 (1505)) doesn't result in blanking of the display name.

**Comment by Norbert80** [comment]
Me and some friends experience this bug frequently. :-(

**Comment by Norbert80** [comment]
Me (Android + Linux)
Friend (Android + Windows)

**Comment by Norbert80** [comment]
Maybe these issue is caused by the desktop client?

**Comment by hjubb** [comment]
looking into this now :+1:

**Comment by Norbert80** [comment]
@hjubb Thanks in advance! If you need additional info, let me know...

**Comment by Norbert80** [comment]
Additional info: It looks like not only the Name is blanked but also the avatar image is blanked to a grey circle.

**Comment by hjubb** [comment]
Think I've found the issue, working on a fix now

**Comment by chairmantheboring** [comment]
No longer experience this since the release of Session Android 1.10.

**Comment by hjubb** [comment]
Great news! Thanks for the update
