### ISSUE TITLE
IMPORTANT FEATURES TO ADD TO SESSION MESSENGER

### ISSUE THREAD

**Issue by CAPTAIN1001** [oxen-io/session-android#504]
Bellow I have various important features to add into the app for further strengthened security as well as better experience for users.

- LINKED / ACTIVE DEVICES SECTION IN SETTINGS - So that you can remove unwanted, un-authorized or old devices and block unwanted use of your account.
- USER SET PASSWORD IN ADDITION TO RECOVERY PHRASE FOR LINKING DEVICES AND RECOVERING ACCCOUNT - Currently, if anyone was to get your recovery phrase they are straight into your account and all the recent messages come back onto any device that's linked and therefore not very secure for all your messages. Furthermore if this happened currently you wouldn't even know because currently there is no active devices section to monitor what has been added.
- SEPPARATE SESSION ID CONTACTS SECTION FOR ANDROID APP - Currently PC version has it but android version doesn't? why not? for example: If you delete the chat on android you loose the Session ID too then you cant contact that account again. 
- DELIVERY AND READ RECIPTS TIME AND DATE INSIDE THE CHAT - Currently just has a tick and coloured tick for read and you have to go back out of the chat to check it.

**Comment by Xeoneid** [comment]
I'm not a session developer but this issue seems no te be a "bug"

**Comment by nielsandriesse** [comment]
Hi @CAPTAIN1001, thanks for your suggestions. Let me address them in order:

• **Linked devices screen.** This is something we want to do, but achieving it in a way where a malicious actor couldn't simplify lie about it is hard in a decentralized environment. We're looking into it.
• **Password in addition to recovery phrase.** Your recovery phrase essentially * is * your password and you should treat it as such.
• **Separating contacts and conversations.** This is on our to do list. We agree that this'd be great!
• **Delivery/Read receipts.** We're about to start on a major overhaul of the Session Android conversation screen UI. This'll be addressed as a part of that.

**Comment by Sepero** [comment]
> Password in addition to recovery phrase. Your recovery phrase essentially * is * your password and you should treat it as such.

Thank you for addressing this, as anything more than the recovery phrase would be redundant. I agree with everything else.

**Comment by KeeJef** [comment]
Closing as some of these are duplicates like password authentication #424 and some have been covered like the contacts screen, please reopen any relevant issues as individual issues so we can better track
