### ISSUE TITLE
Massive sync issues in groups as soon as some members start to use desktop client on same ID

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#513]
We experience massive issues in Group conversations as soon as participants start to share their IDs with the Desktop client.

- Massive message flooding about timer changes
- No sync between devices (participant message do not show up on all own devices, own messages are no longer synced between phone and desktop)
- Participants are displayed with IDs in group participant list although they are displayed with name in general contacts view

Found with:
- Session Desktop v1.5.4
- Session Android v1.9.1

**Comment by LeoBoudet** [comment]
Same here. Huge delays, some messages never arrive. Some are missing between the Android app/desktop client.

**Comment by KeeJef** [comment]
we are making some updates to closed groups this week which will be released in a new version of Session

**Comment by Norbert80** [comment]
@KeeJef: That's great news! Thank you very much!
Will both the mobile apps and the desktop client be updated?

**Comment by Norbert80** [comment]
I close this one as du0plicate of  #1574.
