### ISSUE TITLE
Groups don't appear on iPhones after ID has been added

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#523]
f I (Android) add members who use iPhone to my private group they do not see the group!

I use Android build: v1.9.1

See also
https://github.com/oxen-io/session-ios/issues/399

**Comment by nielsandriesse** [comment]
Hi @Norbert80, thanks for the heads up. We believe we've figured out this issue and will be rolling out patches soon that fix it :) .

**Comment by twinboi90** [comment]
I have a similar issue, so I don't think it was resolved
