### ISSUE TITLE
Intergrate session network and system into telegram api/ui

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#527]

**Comment by nielsandriesse** [comment]
This certainly isn't a bug, and I'm not sure what you mean either :)

**Comment by User1l0** [comment]
> This certainly isn't a bug, and I'm not sure what you mean either :)

I mean, imagine if we could use true private and secure telegram but with session loki  network instead of telegram proprietary servers, just change telegram network with session's loki net, woth that way session can be today's best messenger with many telegram like features, like public channels, Chanel creation, group creation, stickers, voice chats etc.

**Comment by nielsandriesse** [comment]
I appreciate your feedback, and that you want to help make private messaging better. That said, please refrain from making unproductive comments such as "crappy interface and lags", especially if you want us to look into an issue or suggestion you're raising.

**Comment by nielsandriesse** [comment]
Closing this as this suggestion is to essentially re-build all of Session, and that's not something we're going to do.

**Comment by martin-braun** [comment]
> I mean, imagine if we could turn this session messenger with his crappy interface and lags into truly powerful private and secure telegram based messager

@User1l0 You just insulted the work of the devs of Session. You really have talent to find the right words.

@nielsandriesse I get where he is coming from. Telegram is a damn awesome chat client, but it is centralized. The idea is to fork Telegram and implement the loki network into it. Why did you choose Signal over Telegram? I'm curious, but please note, I respect any decision. Anybody is free to do the first step, nobody should complain, especially for free work. :)
