### ISSUE TITLE
Translate Russian Not accept

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-android#529]
Some things remain with the English text (even when there is a translation in the file) 

**Dialog User Window "Copy Session ID"**

![Profile](https://user-images.githubusercontent.com/43858033/117537583-a3d8fb80-b00a-11eb-8bd8-b2b501e37266.png)

**Qr Scan page "Scan  Me" and Button "Share"**

![QR](https://user-images.githubusercontent.com/43858033/117537585-a50a2880-b00a-11eb-9598-1284880a5e89.png)

**Route Page text "Resolving"**

![routePage](https://user-images.githubusercontent.com/43858033/117537586-a5a2bf00-b00a-11eb-87fc-ff1996792469.png)

**Settings Page Notification**

![Settings](https://user-images.githubusercontent.com/43858033/117537589-a5a2bf00-b00a-11eb-9298-d07c0e9f09f7.png)

**Profile Page Day/Night Theme**

![Theme](https://user-images.githubusercontent.com/43858033/117537590-a63b5580-b00a-11eb-901d-7f4233a83860.png)

*update*

***Page Add to new group***
![1](https://user-images.githubusercontent.com/43858033/118799559-88da7700-b8a7-11eb-9ba2-362028a068d2.png)

***Contact List if send image***
![2](https://user-images.githubusercontent.com/43858033/118799700-b3c4cb00-b8a7-11eb-8f7e-63740cb4fc94.png)

**Comment by hjubb** [comment]
Thanks for the heads up, I'll make sure these are referencing the translated "strings.xml" files appropriately or create entries for them

**Comment by nielsandriesse** [comment]
Things should be set up correctly now on https://crowdin.com/project/session-android!

**Comment by xbvrhlmb** [comment]
thanks for this work, 
not translate Screenshot 3 and Screenshot 4

**Comment by hjubb** [comment]
Will look at it, Thanks for the response
