### ISSUE TITLE
Regression: Session Android closes as soon as no data connection is available

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#530]
Session Android crashes and closes as soon as no data connection is available (for example in flight mode).

Found with build 1.10.0.

**Comment by Norbert80** [comment]
Bug still reproducible with build 1.10.1.

**Comment by gitmaker032** [comment]
On my smartphone, the app crashes in any mode. Immediately after opening it. It started after upgrading to 1.10 (1.10.1 nothing changes). MIUI 12, Android 10.

**Comment by Norbert80** [comment]
@nielsandriesse may I kindly ask you to have a look at this bug? It is a regression that crashes and closes the app permanently.

**Comment by Norbert80** [comment]
I can confirm that this issue is fixed in Android build 1.10.2. ==> Closing.
