### ISSUE TITLE
Make Button "Clear All Mesage in Dialog"

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#531]
It would be nice to have a button to clear all messages in the dialog.

**Comment by nielsandriesse** [comment]
Hi @xbvrhlmb, which dialog is this?

**Comment by xbvrhlmb** [comment]
> Hi @xbvrhlmb, which dialog is this?

Hi, if i open chat to user (dialog window)  i see chat message but if I need to delete messages, I need to delete each message in turn.

It would be great to have a button that deletes all the message in the chat with that user

**Comment by nielsandriesse** [comment]
I see what you mean now! This is on our to do list :) .

**Comment by xbvrhlmb** [comment]
@nielsandriesse  Thanks i see, you make this for desktop version
I hope this will also be done on the phone version)

**Comment by gitbq** [comment]
Hi. Just wondering if there were any updates on this feature?  :)

**Comment by KeeJef** [comment]
closing as duplicate of #497
