### ISSUE TITLE
Android build 1.10.6 crash-closes immediately

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#550]
Android build 1.10.6 crash-closes immediately on every attempt to start the app. No GUI acces possible!

Device info: Samsung Galaxy S8, Android 9

**Comment by Norbert80** [comment]
@KeeJef I add you because of the high severity.

**Comment by Norbert80** [comment]
Additional Information: Accessing a new received message by clicking on the Android notification opens the message thread. However, pressing the back button in order to navigate to the overview page immediately crash-closes Session.

**Comment by chriddi** [comment]
+1 (Android  11, Pixel 3a)

**Comment by chriddi** [comment]
1.10.7 fixed it for me! Thx

**Comment by Norbert80** [comment]
1.10.7 fixed it for me too! Thanks!
