### ISSUE TITLE
App crashes after tapping on Delete button to a delete a conversation

### ISSUE THREAD

**Issue by TuxKruger** [oxen-io/session-android#551]
**Description**
As the title states, the app crashes when I tap on Delete button to delete a conversation. When opened again, the conversation is partially deleted but not completely as it should be.

**Steps to reproduce the behavior:**
1. Start a conversation
2. Go back to main screen, tap and hold the conversation
3. Tap on 'Delete' button and tap on 'Yes'

**Logs:** https://del.dog/crewuwesto.txt

**Smartphone:**
 - Device: Redmi Note 9S
 - OS: Android R (11)
 - Session version: 1.10.6

**Comment by nielsandriesse** [comment]
This is already fixed; will roll out with the next release.
