### ISSUE TITLE
App crashes on message loading.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#557]
**Describe the bug**

When I open the app and go into the "session" open group it loads messages for half a second then crashes.

**To reproduce**

1. Make sure you are on the 1.10.7 version
2. Ooen the app and search for any open group.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10
 - OS: Android 11 | One UI 3.0
 - Version of Session: 1.10.7

**Additional context**

**Comment by nielsandriesse** [comment]
Hi @Flam3z, please let us know if this still happens on 1.10.8.

**Comment by Flam3z** [comment]
@nielsandriesse fixed, thx alot :)
