### ISSUE TITLE
Add Read only channels (Formerly RSS Feeds)

### ISSUE THREAD

**Issue by xznhj8129** [oxen-io/session-android#569]
Hello, i'm making this Issue to make sure someone reads this idea. 
A big part of the popularity of Telegram is due to the channels, who allow a user to create a public branded channel where only they and selected contributors can anonymously (to users) post content and links or forward content from other channels. This makes Telegram a sort of semi-social-network and a valuable information source and has become a de-facto standard to be imitated. 

I myself was intent on taking this model and making a stand-alone app out of it, but i now realize that Session with it's future roadmap that implements everything i wanted, 2-way anonymity, peer-to-peer, serious encryption and lokinet layer, is a perfect vehicle for this. Session implementing this (as well as an "all subscribed channels" feed that Telegram SORELY lacks) would turn it into a much more valuable app and greatly increase it's attractiveness, possibly even making Telegram completely obsolete once the P2P/Lokinet layers are online. Please seriously consider this request, it is to everyone's benefit.

**Comment by Flam3z** [comment]
I have no words but a +1, hoping this at least gets considered looking into and if its possible with the loki lib gets integrated.

**Comment by KeeJef** [comment]
We already have something approximating telegram channels, called Session open groups, you can find an unofficial list here https://sessiongroups.com , and you can run your own by going here https://github.com/oxen-io/session-open-group-server , the only thing missing is the ability to easily create channels inside the app, which is something we want to add in the future

**Comment by xznhj8129** [comment]
Open groups are more like public chat groups, it's completely different from channels. Only the owner (and whoever he assigns) can speak in a channel. Think a Facebook page.

**Comment by KeeJef** [comment]
Read only channels are now accessible using [PySOGS](https://github.com/oxen-io/session-pysog) you just have to modify the permissions (see sogs --help) to only allow moderator/admins write privileges
