### ISSUE TITLE
crash when looking at group create message info

### ISSUE THREAD

**Issue by Alexander3a** [oxen-io/session-android#587]
**Describe the bug**

App crash when opening the info tab about group message create message

**To reproduce**

Create a group and then press on the info button on the creation message

**Screenshots or logs**

https://youtu.be/rPdDOzxTvIA

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S8
 - OS: Android Oreo
 - Version: latest beta version from google play store (1.10.10)

**Comment by nielsandriesse** [comment]
This should be fixed on 1.11.0
