### ISSUE TITLE
Open group issues

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#589]
A question: Does session leak your ip to the server side of the open group that you join?

Problems: Every open group has connected the individual site server but not in the session network, the saddest part  is that you can't create open groups inside session network, it's dangerous, you don't know  what is behind every server of the group you join, make so that people can create a group inside session not in individually servers, it's masochism connecting to another server for some open session group, you made this app for decentralized and anonymous chatting so don't destroy the idea that you created, 😬 just  don't abuse your own app, just keep improving

**Comment by Prophet-26** [comment]
Although the IP of the open group server is known, interacting with the server still uses the full 3 hop onion routing, so no user IP is leaked to the server. It's also important to note that all messages on open group servers are encrypted. 

In the (hopefully) near future open groups can be hosted on Lokinet which will obfuscate both the user and server IP, and not just the user.
