### ISSUE TITLE
Release F-Droid repo build at the same time as the build for the Play Store

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-android#590]
I haven't used Session long enough to claim that this **always** happens, but version 1.10.8 appeared in the Play Store several days before it found its way to the Session F-Droid repo. Version 1.10.10 showed up in the Play Store three days ago, and it still does not appear in the Session F-Droid repo (synced it again just now). I can't think of any reason why anyone would build Session for the Play Store without building it for the Session F-Droid repo at the same time (if some reason exists, please enlighten me). I would actually expect to see new releases in the Session F-Droid repo first, as the developers (I assume) have full control over it, but Google might not immediately display a new release in the Play Store for a number of reasons.

**Comment by xbvrhlmb** [comment]
Agree, I also update with F-Droid and unfortunately the version always lags behind the current one.

**Comment by nielsandriesse** [comment]
We generally release them at the same time. There were one or two versions where F-Droid lagged behind. Closing this as it's not an ongoing issue :)

**Comment by 2011** [comment]
@nielsandriesse You might have released 1.10.10 to the Session F-Droid repo before closing this.
