### ISSUE TITLE
Search in Chinese only work sometimes

### ISSUE THREAD

**Issue by rdai** [oxen-io/session-android#592]
**Describe the bug**

Searched for Chinese in a conversation, only works a minority of times. Maybe applicable to other languages as well.

**To reproduce**

Start a conversation in Chinese and search.

**Screenshots or logs**

Sorry, no screenshot due to security :)

**Smartphone (please complete the following information):**

Samsung Galaxy S9+
Android 10
version: 1.10.10

**Additional context**

**Comment by nielsandriesse** [comment]
Hi @rdai, thanks for the bug report. We'll look into this!

**Comment by hjubb** [comment]
Hey @rdai please let me know if the new global search has problems when searching in Chinese, from our testing it appears to work nicely but if that's not the case let us know by re-opening this issue :+1:
