### ISSUE TITLE
How long does it take for the messages to disappear from the session network

### ISSUE THREAD

**Issue by AdrianStone0405** [oxen-io/session-android#601]
**Code of conduct**

- [Y] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When a new account joins the group chat, you can still see the old messages that have disappeared. The current test is up to three days. 

**To reproduce**

1.Create a closed group chat of three users: Device A to C;
2.Set disappear time to 1 minute;
3.Send some information in the group;
4.Wait for more than 1 minute and confirm that all three users have read the message and the message has disappearedl
5.Add the fourth user in a closed group chat: Device D;
6.The fourth user can see the message sent before joining the group, and the message disappears according to the previously set time; 

**Screenshots or logs**

Because a PC cannot obtain the logs of two android devices at the same time, the log is provided by device B, and the screenshot is provided by device D. 
log:
[logcat.txt](https://github.com/oxen-io/session-android/files/6633334/logcat.txt)
Add the fourth user in a closed group chat, see the message sent before joining the group
![Screenshot from 2021-06-11 01-37-48](https://user-images.githubusercontent.com/11817602/121571818-ff841380-ca12-11eb-83d7-d7f1dc47cc2a.png)
The first message before joining the group 
![Screenshot from 2021-06-11 01-37-56](https://user-images.githubusercontent.com/11817602/121571901-1cb8e200-ca13-11eb-88cd-732e79acbc31.png)
The first message after joining the group 
![Screenshot from 2021-06-11 01-38-04](https://user-images.githubusercontent.com/11817602/121571967-335f3900-ca13-11eb-94dc-9552657eb9e0.png)
The message starts to expire and disappear 
![Screenshot from 2021-06-11 01-38-41](https://user-images.githubusercontent.com/11817602/121572071-4b36bd00-ca13-11eb-9e51-9abe9817969d.png)
All messages are expired messages, only setting information is left 
![Screenshot from 2021-06-11 01-38-47](https://user-images.githubusercontent.com/11817602/121572164-66a1c800-ca13-11eb-9389-c93cfd46be39.png)

**Smartphone (please complete the following information):**

 - Device A: Essentia ph-1
 - OS: lineageOS 18.1 (Android 11)
 - Version of Session or latest commit hash: 1.10.13, download from google play

 - Device B:Redmi K30 5G
 - OS: MIUI 12.5.2 stable (Android 11)
 - Version of Session or latest commit hash: 1.10.13, download from github

 - Device C: Samsung Galaxy S6 (SM-G9208)
 - OS: Android 7.0
 - Version of Session or latest commit hash: 1.10.13, download from github

 - Device D: HP OMEN 2 (Desktop)
 - OS: Ubuntu 21.04
 - Version of Session or latest commit hash: session-desktop 1.6.5, install from the command line  

**Additional context**
As we all know, the message of the session network uses the tor network and is transmitted to multiple servers. Can it be suspected that the message has been stored in the seesion network, but it has not really disappeared, but only disappeared from the device that logged in the session.
The session is very dangerous for users. As long as the device of a user in the group chat is controlled and the controller's device is invited to join the group chat, the controller can completely copy the content of the group chat and check the private information of the people in the group. cause some damages.

**Comment by jamesmccoy0405** [comment]
The first step is to use Device A, Device C, Device D;
Step 4 Use Device B;
This bug can still be reproduced

**Comment by jamesmccoy0405** [comment]
I have tried to test the above steps on four android devices and the bug still exists.
Device A Samsung Galaxy S6/SM-G9208 (Android 7.0)
Device B Redmi K30 5G (MIUI 12.5.2 stable/Android 11)
Device C Mi 9 (MIUI 10.9.8.22 beta/Android 10)
Device D Google Pixel 2XL (Android 11)

**Comment by chairmantheboring** [comment]
@jamesmccoy0405 All messages exist on the Session network for 14 days, regardless of the expiring timer or not (and honestly, you should expect that once a message leaves your device, you have no control over it. Message timers are completely client side and a custom client could be made to completely ignore this timer). However, the developers are working towards resolving the issue with expiring messages being retrievable, but it requires a lot of work before it will be complete. You can see some conversation about this in issue #535.

**Comment by jamesmccoy0405** [comment]
> @jamesmccoy0405 All messages exist on the Session network for 14 days, regardless of the expiring timer or not (and honestly, you should expect that once a message leaves your device, you have no control over it. Message timers are completely client side and a custom client could be made to completely ignore this timer). However, the developers are working towards resolving the issue with expiring messages being retrievable, but it requires a lot of work before it will be complete. You can see some conversation about this in issue #535.

Thanks for your answer

**Comment by KeeJef** [comment]
Closing as answered (14 days), see #407 regarding disappearing messages reappearing
