### ISSUE TITLE
No timestamps shown by default in conversations.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-android#633]
The Android client now shows no timestamps by default in conversations. One must long-press a message to see when it was sent.

This provides a subpar UX, deviates from desktop client behaviour, **and** deviates from a pretty much universal convention of instant messaging software.

Please explain the reasoning behind removing this feature and give due consideration to reinstating it.

**Comment by nielsandriesse** [comment]
We considered this thoroughly before removing it. The rationale is that adding the timestamp to every message bubble clutters up the design (makes it harder to parse what's on the screen), and it's rarely relevant. Like you mentioned, it's still accessible by simply long pressing the message.

Also, desktop isn't the design goal :) .

**Comment by ianmacd** [comment]
Your response surprises me.

Whether or not the timestamp is relevant is surely decided entirely by the user. In my own case, I deem it to be highly relevant. I need to see at a glance precisely when a particular set of messages arrived, not after individually long-pressing each of them. That's unworkable in a busy conversation.

It's not without good reason that the display of timestamps is a near-universal convention in messaging applications. A message's timestamp ranks second only to its sender in terms of metadata importance.

Did you conduct any usability testing among actual users prior to making this change? I have already gathered enough anecdotal evidence suggesting that users generally dislike this change that I would be surprised to hear that usability testing was performed and suggested otherwise.

This is such a detrimental change to the Android UX that it effectively renders the Android client unusable for my purposes. That relegates Session to being a desktop-only experience, which is of only limited use to me.

I urge you to reconsider the wisdom of inflicting this change on users. I say _inflict_, because the display of timestamps could have simply been made a user-configurable option. This is such a radical change to a universally accepted and expected UI element that it's hard to grasp any rationale for unilaterally deciding to remove it.

**Comment by nielsandriesse** [comment]
I wouldn't call displaying timestamps near-universal. Facebook Messenger for example (second most used messenger globally and generally considered to have very good UX) doesn't show timestamps by default.

Also, the majority of users we've talked to like the new design. In addition to this, it has been around on iOS for several months already where it has been received very well.

Adding an option to show timestamps is something we can definitely consider (I'm noting this down), though as with everything it's a matter of priorities.

**Comment by nielsandriesse** [comment]
Just merged a change that makes grouping a lot more granular, similar to what Facebook Messenger does. So even though messages still don't show a timestamp on each bubble, "conversations" are now grouped by hour rather than by day. This should alleviate things for now.

**Comment by ianmacd** [comment]
The grouping is an improvement; thanks for adding it. It's not a substitute for proper timestamping, however, so I retain the hope that timestamp display will become an configurable feature at some point in the future.

As for FB Messenger being widely thought to have a good UX, I've actually never heard that claim before, but don't doubt that it has its fans, as all messaging clients do. It is, however, just one client, no matter how popular it is.

Even the ubiquitous WhatsApp displays timestamps by default, as do Telegram, Signal, Status, Threema, Olvid, Slack, Zulip, Discord, Element, Conversations and many others. That's what I meant by near-universal.

**Comment by Gioele-Bencivenga** [comment]
I would also benefit from timestamps being always visible, the text is small and not highlighted so the eye easily ignores it when scanning the page unless we search for that info.

I also understand many users won't care about timestamps, so the best option in my opinion would be to have an option to "always show" timestamps that is disabled by default.
