### ISSUE TITLE
The app title is in arabic

### ISSUE THREAD

**Issue by mrcnpp** [oxen-io/session-android#650]
Hi , sorry for the low quality issue , I'm posting this by phone.

The session app title is now in Arabic . 
My phone language is in Italian

Smartphone model: one plus 5
OS: oxygen OS 10.0.1

**Comment by HostFat** [comment]
I've updated the italian translation on both Android and Iphone, if they'll add the updated translation it will be fixed.

**Comment by nielsandriesse** [comment]
Thanks for reporting! This'll be fixed with the next release. Closing the issue :)
