### ISSUE TITLE
Text sharing from any app to Session chats broken

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#651]
Steps to reproduce:

- Open any app that allows to share text to other apps
- Share some text to Session app
- Click on any chat inside Session app

Result: The message box in the Session chat is blank.

Additional information:
This function is broken since build 1.11.0 or 1.11.1. Sharing pictures from any app to Session chats works as expected.

**Comment by Norbert80** [comment]
@nielsandriesse any chance to address a fix for this annoying regression bug for next release?

**Comment by nielsandriesse** [comment]
This is fixed and will be shipped soon.

**Comment by Norbert80** [comment]
Yes, I can confirm that this issue is fixed in 1.11.4. Thanks @nielsandriesse.

**Comment by Norbert80** [comment]
@nielsandriesse could you please re-open this issue?

The reason I ask is a remaining regression bug related to this issue.

Try the following steps:
- Share any link (for example from YouTube app) to a Session chat

Note that Session does NOT generate a preview.

- Edit the URL somehow (for example delete and re-add the last character of the URL)

Now Session DOES generate a preview.

I am rather sure that former Session builds directly generated a preview of the shared URL. This is what the user expects.

**Comment by Norbert80** [comment]
I cannot reproduce this bug anymore with Android client v1.11.7.

==> Closing.
