### ISSUE TITLE
Change background colors for highlighted messages (more contrast needed)

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#655]
Since the polished GUI (v1.11.0/1) selected messages show no background highlighting (only in darkmode the background is highlighted).

@nielsandriesse can you confirm this regression bug?

**Comment by nielsandriesse** [comment]
They do actually; it's just hard to see. We need to decide on a better color in light mode.

**Comment by Norbert80** [comment]
@nielsandriesse yes, I can confirm that. I suggest to change highlighted background colours for both light and dark modes to achieve more contrast.

**Comment by nahuhh** [comment]
I believe this main issue is likely fixed?

**Comment by ianmacd** [comment]
> I believe this main issue is likely fixed?

What makes you say that?

Just try it. It's still barely possible to make out highlighted messages.

**Comment by nahuhh** [comment]
> > I believe this main issue is likely fixed?
> 
> What makes you say that?
> 
> Just try it. It's still barely possible to make out highlighted messages.

Sincerest apologies. I misunderstood the issue.

I see now that if you tap and hold on a message while using "day" mode, there is no highlighting.

**Comment by Norbert80** [comment]
Seems to be fixed now.
