### ISSUE TITLE
Sending messages in the future?

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#662]
Today I witnessed a bug I don't fully understand.

What happened:
In an Open Group person X sent a message. It arrived as the newest message, everything appearing as normal. As people continued to chat, new messages were sorted before the message from person X. Some people even remarked on it, asking why their messages are being sorted before the message from person X in the chat.

I assume this may be a clock issue? Message from the future? It's possible that some bad actor could use this technique to disrupt groups

**Comment by hjubb** [comment]
The open group server should now set the times appropriately after receiving messages as of a few updates ago, this particular open group may need an update to the latest if this is still occurring. Synchronising client clocks would need a bit more effort across the entire network and clients but would be an improvement for the future :+1:

**Comment by Sepero** [comment]
Yes, I believe the Open Group server was out of date. The issue seems to be resolved.
