### ISSUE TITLE
Links don't open when pressed

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#664]
![Screenshot_20210717-224901__01](https://user-images.githubusercontent.com/1575546/126042623-9e5abed3-0956-49cd-ab52-b974c4901814.jpg)

Sometimes in 1 to 1 chat, links don't respond to bring pressed/clicked. Imaged is a link that did not respond.

I think this bug may also affect Private Groups.

Android 10
Session 1.11.4

**Comment by Sepero** [comment]
Adding info: This bug also present in Open Group chats.

I hate posting non-reproducible bugs like this. I know they can be a challenge to fix. Unfortunately, it is still present in the latest version.

Session 1.11.5

**Comment by Sepero** [comment]
I think I know how to reproduce this bug. It seems to only occur when also replying to another message.

**Comment by Flam3z** [comment]
Can repo
Version: 1.11.7

**Comment by eyeberic** [comment]
Here are some findings for Version 1.11.8

- If your message is a reply: Links are parsed on display but **non-clickable**
- If your message @'d someone: Links are **not parsed**
- If your message is a reply + @'d someone: Links are **not parsed**
