### ISSUE TITLE
Non-image icons don't appear correctly

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#668]
==Example 1==
![Screenshot_20210720-083006__01](https://user-images.githubusercontent.com/1575546/126250742-3a39a17a-ccd9-456a-a0ae-436cbbfedaf2.jpg)
![Screenshot_20210720-083014__01](https://user-images.githubusercontent.com/1575546/126250754-7f6fdf14-2db3-48c6-b5d4-1390159470b6.jpg)

-----
 ==Example 2==
![Screenshot_20210720-083053__01](https://user-images.githubusercontent.com/1575546/126250759-85ba6dc3-b430-4a0f-8953-2842d950f26a.jpg)
![Screenshot_20210720-083058__01](https://user-images.githubusercontent.com/1575546/126250764-27627161-575e-4c4e-82fa-d71942da6e16.jpg)

I would expect someone who's user name is "stretch" to have an "s" in their icon circle. Instead, their icon seems to use contain the 3rd character of their ID.

This only affects people who don't upload an avatar for their account.

**Comment by KeeJef** [comment]
This seems to be resolved, please reopen if you are still experiencing on the latest version of Session
