### ISSUE TITLE
Tapping on Replied Message No Longer Takes You To That Message

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#670]
![Screenshot_20210721-215558__01](https://user-images.githubusercontent.com/1575546/126510782-f663f36c-b087-4d2d-9dcb-33522b931480.jpg)

When the Replied message is tapped on, the chat doesn't scroll up to that message.

Android 10
Session 1.11.5

**Comment by nielsandriesse** [comment]
A fix for this is in the pipeline :)

**Comment by KeeJef** [comment]
This is fixed
