### ISSUE TITLE
Calls and video calls

### ISSUE THREAD

**Issue by wuniversales** [oxen-io/session-android#68]
It would be nice to allow calls and video calls in the messaging application.
This would also apply to the pc version

**Comment by GintokiHub** [comment]
would love this feature

**Comment by schattenpanzer** [comment]
I don't think decent video calls would be possible over lokinet. However I know mumble over tor works fairly well (with ethernet connection), and voice calls with session over lokinet could be possible.

**Comment by Rex-0x7CB** [comment]
I'd love to see this feature implemented. This is the only feature I miss when I compare Session to other encrypted messaging platforms.

**Comment by UnpilotedRebuilt1** [comment]
I'm not fussed about video calls however voice calls would be the bomb! I really need an app that allows me to voice call without a sign up process

**Comment by meximan** [comment]
Any progress on this?

**Comment by meximan** [comment]
What's the latest update for implementing video calls/voice calls?

**Comment by Flam3z** [comment]
In their latest dev update they state, they have completed the cross platform side of calling, last week was them trying to get it working on the clear net then integrating it into lokinet, voice calling is very close 🤭

**Comment by meximan** [comment]
So, I am assuming they're eventually planning to add in video calls too. I am working on making more $$$ to give big donations

**Comment by J4gQBqqR** [comment]
So in 2022, we saw 1.20 and 1.21 already feature voice and video calling. Maybe this will reach stable soon. Kudos for the team.

**Comment by hjubb** [comment]
This one is live now, you can call people you have conversations with using voice and video if you'd like :+1:
