### ISSUE TITLE
Punycode removal

### ISSUE THREAD

**Issue by JustVictor17** [oxen-io/session-android#681]
Please don't mark as clickable links that have punycodes inside (like ámazon.com) or at least mark them like modern browsers do (like: x----n1mazon.com)
![Screenshot_20210729-000010](https://user-images.githubusercontent.com/87635958/127434439-af588a5f-215d-4291-b54c-5248b595f280.png)

**Comment by JustVictor17** [comment]
Would like this to be implemented on next update, desktop version doesn't suffer the same issue, I don't have an iOS device so I can't check by myself if this is reproduceable on those devices.

**Comment by hjubb** [comment]
Easy solution would be to display the ASCII URL in the open URL dialog. That would mean it's consistent with the displaying / notifications / quotes across platforms while still showing the converted URL to the user in the dialog. That would also mean it would work retroactively for previous message links :+1:
