### ISSUE TITLE
Buggy/Inconsistent Camera

### ISSUE THREAD

**Issue by SD745** [oxen-io/session-android#687]
There are currently 2 methods of using the camera in the app, which in itself may be possible bug, regardless both present their own issues detailed below:

### 1st Issue
- From the chat page select the camera icon then capture an image, this results in an image saved to Android/data/network.loki.messenger/files/Pictures
### 2nd Issue
- From the chat page select the image picker icon, then the camera icon and capture an image this results in a cropped image compared to viewfinder

**Comment by hjubb** [comment]
This should be solved in the latest version v1.11.9 :+1:
