### ISSUE TITLE
Add chatroulette like mode where you can talk with random session users in pm

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#699]

**Comment by User1l0** [comment]
> What's a random Session user here? I don't want anyone pulling me into any conversations 😉
> 
> If this is implemented, someone will have a way to know if a given string of characters actually match a real Session ID 🤔

Why not make chat roulette mode controllable where you can turn off that feature

**Comment by KeeJef** [comment]
I don't think this aligns well with the purpose of Session, closing for now
