### ISSUE TITLE
"Copy message text" function also includes a timestamp prefix

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-android#721]
### Code of conduct

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

### Describe the bug

For mobile clients (Android, iOS), the "Copy message text" function ends up copying the message timestamp as well. 

### To reproduce

- Go into any chat
- Long-tap on a message for more options
- Tap on the "Copy message text" button
- Try to paste into a text input area (Either Session app, or some other application)
- See that the timestamp is included at the very beginning of the message text

### Screenshots or logs

Screenshot below show-casing the issue: 

![copy_message_text](https://user-images.githubusercontent.com/88373201/132079253-addd559b-5b5a-483e-806d-6d2bdc3c120e.jpeg)

### Smartphone (please complete the following information):

 - Device: Samsung Galaxy A7 (a7xelte)
 - OS: Android 10 (LineageOS 17.1)
 - Version of Session or latest commit hash: 1.11.8 (2185)

### Additional context

This is a major issue, especially when sharing open group links inside Session chats.

**Comment by hjubb** [comment]
This will be improved in the next release, we are also going to add the ability to copy the links once you tap on them instead of just being able to open them, that might improve the URL sharing particularly for open group links

**Comment by eyeberic** [comment]
Nice. 

I assume that will be using the similar dialogue as the desktop client counterpart? 

Obviously, a better solution would still be a deep-link URI scheme, but at least we mid-term solution is better than none.

**Comment by hjubb** [comment]
definitely agree regarding the deep-linking URI schemes, at the moment there is also a "add members" function in the open group conversations which will send a kind of invite to individuals that can let them join from the conversation, but making this more visible and accessible would be a good thing

**Comment by hjubb** [comment]
This and the ability to copy URLs should be fixed in the latest release :+1:
