### ISSUE TITLE
[Suggestion] Can you Please put this app in the Fdroid store?

### ISSUE THREAD

**Issue by Ryu945** [oxen-io/session-android#726]
Can you please put this app in the Fdroid store?  Those that use this app because they are concerned about privacy will also be concerned about using the Google Play Store to get apps.   Being in the Fdroid store is much safer as they are not Google and they host open source apps.

**Comment by hjubb** [comment]
Hey @Ryu945 there's an Fdroid repository containing the exact same builds as the play store published versions at https://fdroid.getsession.org/fdroid/repo/?fingerprint=DB0E5297EB65CC22D6BD93C869943BDCFCB6A07DC69A48A0DD8C7BA698EC04E6
