### ISSUE TITLE
Invisible black button

### ISSUE THREAD

**Issue by anton2007** [oxen-io/session-android#732]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
When you select message in dark mode... back button (left up corner of screen) is invisible

**To reproduce**

Select message in any group in dark mode and check back button

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.
I'll do it later and I don't know how safe is it.

**Smartphone (please complete the following information):**

 - Device: Huawei Honor 9S
 - OS: Android 10 (MagicUI 3.1.0)
 - Session v1.11.9

**Additional context**

**Comment by Sepero** [comment]
> Select message in any group in dark mode and check back button

Not enough information. Do you mean "press the back button"?

**Comment by KeeJef** [comment]
Not enough info to go off, tested selecting a message and the back button was visible in dark mode. Closing for now
