### ISSUE TITLE
Linking a device unblocks & recovers user chat.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#735]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

A User I had blocked some time ago appeared again when I had to link my mobile device from my PC, on top of that I even deleted the chat and they were seemingly unblocked and the chat was recovered.

**To reproduce**

1. Block a user
2. Delete their DM
3. Link your mobile device from your PC using your recovery phrase

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10
 - OS: Android 11
 - Version of Session or latest commit hash: 1.11.9

**Additional context**

**Comment by eyeberic** [comment]
Currently both the block and delete function are all client-side only. 

Relevant Issue: [Block users](https://github.com/oxen-io/session-android/issues/577#issuecomment-922280099), [Deleted chats](https://github.com/oxen-io/session-desktop/issues/1887)
