### ISSUE TITLE
unable to send attachments

### ISSUE THREAD

**Issue by kunago** [oxen-io/session-android#737]
Since today, some 3-4 hours ago I am unable to send any pictures. I have not tested with any other attachments yet.

Once I send it, it gives me the upload bar on the bottom and never finishes an upload. 

It does not matter what size it is, it can be a regular picture or a small screenshot. My Session has changed the nodes quite a few times already but it had no effect on deliverability.

As it seems, this issue is not related to my phone only, my contacts suffer from the same issue.

**Comment by dis7ant** [comment]
I'm getting this same behavior on Session Desktop.  It also affects the auto-generated preview when sending links/URLs

Text-only works fine, and when sending a URL I can quickly send the message before URL preview is generated, allowing the link to be sent.

**Comment by kunago** [comment]
It seems to be working now just fine so I am closing this issue as resolved.

**Comment by dis7ant** [comment]
Confirming that it's working again after a session software update today.
