### ISSUE TITLE
Built-in emojis missing on Android

### ISSUE THREAD

**Issue by PandaCoderPL** [oxen-io/session-android#740]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

After rebuilding conversation screen in version 1.11.0 built-in emojis are not available anymore but in Settings->Chats there is still option related to them which suggests that they weren't completely removed. Before 1.11.0 there was emoji button at the bottom left which showed list of emojis. Now there is plus sign instead and available options are: GIF, file, gallery and camera.

**To reproduce**

1. Open any conversation in Session.
2. Look at the bottom left of opened conversation screen.

**Screenshots or logs**

I'm not able to provide any screenshots so I hope that my description of the problem is detailed enough.

**Smartphone (please complete the following information):**

 - Device: Google Pixel 4a
 - OS: GrapheneOS
 - Version of Session or latest commit hash: 1.11.9

**Additional context**

No additional context needed.

**Comment by KeeJef** [comment]
Pretty sure these were just removed in the conversation screen refactor, generally keyboards have access to emojis?

**Comment by PandaCoderPL** [comment]
> Pretty sure these were just removed in the conversation screen refactor

You are right but like I said before there is still option in the settings that suggests existence of built-in emojis in the application.

> generally keyboards have access to emojis?

Most of them do but there are people who are using keyboards like Simple Keyboard which doesn't have emojis so having them built into a messenger is generally nice thing to have.

**Comment by KeeJef** [comment]
Closing this as there doesn't seem to be significant enough support to bring this back, we would have to rejig the UI to fit it back in too
