### ISSUE TITLE
Vibrate on Notification

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#742]
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The vibrate setting in notification is disabled both from app and from android 11 notification for the app but still vibrating on new messages.

**To reproduce**

Disable vibrate settings on chat but still vibrating on new messages.

**Screenshots or logs**

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy M12]
 - OS: [Android 11]

**Additional context**

**Comment by hjubb** [comment]
Thanks for catching this, I'll look at fixing this in the next release

**Comment by KeeJef** [comment]
is this still an ongoing issue?
