### ISSUE TITLE
Feature request: Let users choose message storage method: Send only when both online(no storage on swarm)/Store on Swarm till reciepent recieves/Store on swarm for two weeks

### ISSUE THREAD

**Issue by natur960** [oxen-io/session-android#745]
**Feature Request: Make possibilty to choose message storage and sending method:** 
1. Send only when both online (do not store on swarm)
2. Store on Swarm till reciepent recieves
3. Store on swarm for two weeks

Any way the message passes onion routed through lokinet when using the internet.

**Comment by natur960** [comment]
Any feedback would be highly appreciated, im not sure if any one if the developers have read it. = /

**Comment by natur960** [comment]
Any feedback would be highly appreciated, im not sure if any one of the developers have read it. = /

**Comment by KeeJef** [comment]
Closing for #696 which would add a mode to chat P2P over Lokinet without storing messages on the swarm when both users are online

**Comment by natur960** [comment]
@KeeJef - what about option #2: Store on Swarm till reciepent recieves - like in signal, which also works with multu device (well only one mobile device allowed by signal and the rest non-handy's)
