### ISSUE TITLE
A great solution and concept for fixing the major performance issues

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#766]
Session is lagging to the point of crush, it's impossible using session to visit groups and read the messages, for example trying to visit an official session group becomes impossible, session loads all messages all at once causing cpu burn, crush and lagging, why not make it load messages and it's content consistently like one by one, not all at once? It could fix the major performance issues on the whole session app

**Comment by hjubb** [comment]
Good to hear, I will close this issue and continue to improve the performance to reduce these sort of issues in the future, I think there are a few other places where multiple accounts are being tracked so I might keep discussion in those places
