### ISSUE TITLE
Reject/accept option for DMs

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#770]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

Im sick of random strangers dming me from groups, please add a feature like telegram where i can choose to block or decline their dm ty.

**Comment by Flam3z** [comment]
omg tysm, love you.

**Comment by sierra0scar** [comment]
And add block to that as well... Accept/Reject/Reject and block

**Comment by Sepero** [comment]
Duplicate of #665

**Comment by sierra0scar** [comment]
And.. Can we (in settings) - have an option to have allow/dissallow DM's
