### ISSUE TITLE
(Feature request) Add a gallery section for saved music files

### ISSUE THREAD

**Issue by hardBSDk** [oxen-io/session-android#776]
Add a button inside "+" menu where you can send your saved audio files (Like WhatsApp/Telegram).

Actually you can send audio files as documents and it's play normally, adding a specific section for (Internal storage/Music) with duration and size (showing the size as red when some file is larger than what Session can upload) would be a nice UI improvement.

#616

**Comment by KeeJef** [comment]
This can be tracked as part of #616
