### ISSUE TITLE
(Bug) Broken audio duration

### ISSUE THREAD

**Issue by hardBSDk** [oxen-io/session-android#778]
Sometimes the audio playback remains as 0:00 even after I play it or when playing, the number appears as 0.000 (1:280 for example).

Android version: 9
Session version: 1.11.11

I saw it on a group, IDK about private chat.

**Comment by Creuqe** [comment]
I did a pull request to merge my fix for this issue. #948

**Comment by KeeJef** [comment]
Whats the status on this?

**Comment by KeeJef** [comment]
Closing as im assuming this is fixed
