### ISSUE TITLE
Add the option to mark a conversation as read.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-android#789]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The Session desktop client contains a handy feature to mark a conversation as read in the list of conversations, but the Android client has no such option.

**Comment by hjubb** [comment]
In terms of messages with a disappearing timer which starts upon reading the message, does the desktop / would you expect it to also start that timer or only affect the appearance in the app to say whether or not a thread should be flagged visually?

**Comment by ianmacd** [comment]
> In terms of messages with a disappearing timer which starts upon reading the message, does the desktop / would you expect it to also start that timer or only affect the appearance in the app to say whether or not a thread should be flagged visually?

I don't actually know how the desktop client handles this, but logically it **should** start the expiry timer on disappearing messages, since that's what the act of loading them into the message panel for reading would also do.

I can, of course, see a good argument for adding a toggle in Settings if/when this feature is implemented: _Mark as Read causes immediate expiry of disappearing messages_, with the default being that the option is enabled.
