### ISSUE TITLE
Synchronized DM message deletion and block

### ISSUE THREAD

**Issue by sierra0scar** [oxen-io/session-android#790]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I'm running session with the same ID on an Android, iphone, MacBook Air and Ubuntu 20.4 ( plus a pixel 5a with GraphineOS Droid v12) for the purpose of testing. 
When I receive uninvited DM's which I then block and delete, I have to complete the same task on every device. It would be cool if the deletions/blocking synchronized across all devices.

**Comment by hjubb** [comment]
We are going to be synchronising the block lists across devices soon! :slightly_smiling_face:

**Comment by sierra0scar** [comment]
Good work👍

**Comment by KeeJef** [comment]
This should be correctly syncing now
