### ISSUE TITLE
Mobile Data Usage

### ISSUE THREAD

**Issue by bigvtokyo** [oxen-io/session-android#798]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Session consumes vast quantities of mobile data. For example, in just a few days it is consuming over 10GB of mobile data, compared to only a few megabytes for most other similar chat applications with similar chat volumes (e.g. Signal). The impact is that my carrier throttles my data only a dew days into the month once my 10GB plan us used up.

**To reproduce**

Use Session every day with approx 250 chats active, approx 100 with activity within the last month. There are also four Open Groups (hosted by myself), and several Closed Group chats. Each chat is mostly just text with some links to URLs, nothing particularly "heavy", i.e. no large music or video files.

Keep an eye on App Data Usage in Android's Network and Internet -> SIMs -> App Data Usage. You will see Session clocking up several GB per day. Session is by far the heaviest mobile data app. 

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Pixel 3a
 - OS: Android 12 (Graphene OS)
 - Session 1.11.12 

**Additional context**

This has financial impact to users who need to increase their data plan to accommodate the excess data usage of Sessi
![image_2021-11-15_21-54-08](https://user-images.githubusercontent.com/10481732/141859365-00d34d86-5c91-413e-956c-25621bba312a.png)
on

**Comment by hjubb** [comment]
Thanks for this, is there any way to tell if the data usage is from foreground or background?

**Comment by bigvtokyo** [comment]
I have disabled background data for Session in an attempt to reduce data usage, so it's all foreground (see screenshot).

Regards

**Comment by bigvtokyo** [comment]
> Thanks for this, is there any way to tell if the data usage is from foreground or background?

Background data for Session is disabled, so this is from foreground.

**Comment by bigvtokyo** [comment]
After installing and restoring the session account onto another device, the problem has not reoccurred.

**Comment by hjubb** [comment]
Thanks @bigvtokyo that is good news, it may have been an erroneous state of background running jobs that might have not occurred again. Will look at doing another performance improvement push soon to try to catch anything that could be causing this type of issue from happening in the future but good to know it's sorted itself out for you in this case
