### ISSUE TITLE
Unable to see Open Server Icon

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#799]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

In an open group server that I am in session seems to be unable to sync the icon despite being seen on desktop.

**To reproduce**

1. Join any open group server that is not under the Session/Oxen umbrella.
2. wait until any messages or images are finished syncing/loading.
3. back out of the chat and look at the greyed out icon.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10
 - OS: Android 11
 - Version of Session or latest commit hash: 1.11.12
 

![Screenshot_20211116-172630_Session](https://user-images.githubusercontent.com/57234536/142076312-2920ae81-fada-42af-a78e-b9f318db6ed3.jpg

**Comment by hjubb** [comment]
This should now be fixed in #807 expect it in the next update :+1:

**Comment by Flam3z** [comment]
Thanks for the update, i'll respond again if its fixed for me.

**Comment by Flam3z** [comment]
issue fixed :) (sorry for being super late)

**Comment by hjubb** [comment]
Thanks for confirming @Flam3z glad it's fixed for you
