### ISSUE TITLE
UX 2020-Feb Improvement Suggestions: Session Messenger

### ISSUE THREAD

**Issue by patoshii** [oxen-io/session-android#80]
Some Telegram features that should be ported over:

- Ability to change font sizes
- Add ability to hover over message and hit reply to quote the reply and also alert the user. On mobile swipe to quote.
- Ability to change background image of chat unique to each chat so you can differentiate from one another. Have a global default setting also.
- List previous shared links on group chat.
- Ability to add a custom profile text to each user.
- Ability to save chat log. Also have option for group admins to disable this feature. 
- Give user ability to message themselves. In telegram it is called "Saved messages" feature. 
- Ability to block users or shadowban
- Ability to archive chats

**Comment by mrcnpp** [comment]
An other functional from telegram (mobile android version) :

- ability to delete a message from all users
- ability to quote other's messages

**Comment by hjubb** [comment]
A lot of these features have now been implemented, some telegram specific ones might be future feature requests if they can be accommodated across all platforms
