### ISSUE TITLE
exclude Five Eyes

### ISSUE THREAD

**Issue by ueen** [oxen-io/session-android#801]
Please add an option to only use servers in the EU or exclude Five Eyes country's. Otherwise the app is one of the best privacy cautious IM while remaining incredibly comfortable to use :)

**Comment by hjubb** [comment]
A potential downside for this would be the reduced possible number of nodes that you would be routing your communications through, although maybe you are just concerned about the initial entry node of the network path that is created?

**Comment by lilithium-hydride** [comment]
Isn't the idea behind routing messages through multiple nodes that you don't necessarily need to trust each individual node? If not, then I think it'd be worth looking into, but at first glance this doesn't seem like it'd be worth the reduction in possible nodes.

**Comment by ueen** [comment]
Well if the entry or exit node is in Australia for example, they obviously have my IP address and maybe some metadata (how much traffic).

**Comment by lilithium-hydride** [comment]
> they obviously have my IP address

While I cannot authoritatively state what each node has access to when data passes through it, I'd have a hard time imagining that a service which implements onion routing would then leave the source IP address available for the exit node to grab. It defeats the whole purpose. If you have a source for information that says otherwise, it'd be worth bringing to the attention of the community at large (this also goes for any possible metadata leakage).

**Comment by laudarch** [comment]
Its useless to try and block the 5 eyes because there's treaties and agreements with more countries and that sums up to 41 along with MoUs with various countries.

**Comment by hjubb** [comment]
Going to close this issue for now, I think any further discussion would be better in one of the Session groups and implemented across each platform, if anyone wants to modify the client to suit their own privacy concerns and use-case that wouldn't be impossible but I think making a decision like that for every user without properly assessing the privacy impacts and reduction in available nodes might be better suited to a larger discussion across the community :+1:
