### ISSUE TITLE
Empty open group server doesn't show up on Android

### ISSUE THREAD

**Issue by jagerman** [oxen-io/session-android#802]
If I attempt to join an open group that has no messages in it, I can successfully join the group but when I return to the conversation list the added group is nowhere to be found.

Here's an empty room to test with (please don't post into it): https://testing.open.getsession.org/view/room/Empty

(This is unique to Android; iOS and Desktop versions are fine with the empty group).

**Comment by hjubb** [comment]
I think this is just to do with how we trim empty threads and remove them from DB, can look at this to make sure a regression hasn't been introduced that would exclude open groups from being trimmed this way

**Comment by Ranbeer600** [comment]
As
