### ISSUE TITLE
[Translate]  Media saved and message timer

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-android#814]
Now in chat if user save image, see text "Media saved by Username" but not have translate in other lang
(Desktop version have) 

If change timer wee see "You set the disappearing message timer to ..." but not have translate in other lang.
(Desktop version have)

App Version: 1.11.13 (2355)

**Comment by 144** [comment]
you can contribute translations at Session's Crowdin page (https://crowdin.com/project/session-android/ru)

**Comment by hjubb** [comment]
This is an issue in not having all of the strings we use in the same module, but I can include those strings for translation in future

**Comment by hjubb** [comment]
I've just added these to crowdin now :+1: the links in the readme and above should now let you translate these strings!
