### ISSUE TITLE
Call randomly exits 1 second after clicking call

### ISSUE THREAD

**Issue by Lucifer1903** [oxen-io/session-android#815]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Sometimes call exits by itself 1 second after clicking call button. 

**To reproduce**

Try calling until it happens, it happens frequently enough for me to catch it in a video that I will attach to this issue. 

**Screenshots or logs**

In video I attempt a call which functions normally and I cancel it, then I attempt the call again and it exits by itself after 1 second. 
It seems I'm unable to attach videos, however I can send it directly upon request. 

**Smartphone (please complete the following information):**

 - Device: Huawei mate 40 Pro 
 - OS: Android 10
 - Version of Session: 1.12.0 (2455)

**Comment by hjubb** [comment]
Thanks @Lucifer1903, I think I know what this is related to, but will try to collect some more info from people using calls before trying to fix a lot of the issues that will come out from testing but I will take a look at what I think may be causing this until then and keep you notified

**Comment by Lucifer1903** [comment]
Thanks

**Comment by KeeJef** [comment]
Is this still occurring?

**Comment by Lucifer1903** [comment]
No
