### ISSUE TITLE
Cannot send .doc file as attachment

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#818]
Hello,

It is not possible to send a *.doc file as an attachment via Session Android. If you try to do so, a green bubble without text content is displayed in the chat with a red exclamation mark symbol underneath. The file is not sent.

I assume that the problem also occurs with other file formats.

Found with Session build 1.11.14 (2425).

**Comment by hjubb** [comment]
Thanks @Norbert80, do you know if this has anything to do with the size of the attachment you're uploading? is it also just to the one person you're trying to send and having failures?

**Comment by KeeJef** [comment]
Closed due due to lack of response, please reopen if you have additional information

**Comment by Norbert80** [comment]
I can confirm that this issue is fixed. Thanks and sorry for my late response.
