### ISSUE TITLE
Unify VPN TOR with Session

### ISSUE THREAD

**Issue by Jeze001** [oxen-io/session-android#820]
Hello, first of all I love Session, it's an amazing tool for secure messages, I'll leave a suggestion here that would be to unify Tor with Session for better message security, security never hurts, could you leave an option in Session to connect to one VPN, and with that we could add the TOR network for another layer of protection, think about it, this feature in the tool would be very interesting.

**Comment by ByJumperX4** [comment]
Session is already using onion routing via lokinet (see https://getsession.org/faq#onion-routing)
Lokinet is some kind of alternative to tor that anonymizes your IP in a similar way. Maybe being able to choose between tor or lokinet in the settings could be a feature, but I personally don't see why it would be added, Lokinet already does well the job.

**Comment by hjubb** [comment]
as @ByJumperX4 said the routing over the oxen network already achieves an onion routed result for messages and communications in the application. If you're using a VPN application like orbot or something before the communication goes over the network used by session I don't see why it wouldn't work that way either without any modification on the application side. I'll close this as I think building in extra layers or networks like this would be higher level than the Session Android project and you could bring it up in the other Oxen channels (or the Oxen / Session open group in the app!)

If you do however run some tests and find that your VPN on Android isn't working as intended with Session that could be a bug so please feel free to re-open if that is the case :)
