### ISSUE TITLE
Translation bug in Polish version

### ISSUE THREAD

**Issue by stlsht** [oxen-io/session-android#823]
Hey, just found a little bug in Polish translation. In privacy settings there's... Hungarian text under "show link content". Just that.

![sestran.png](https://user-images.githubusercontent.com/74292287/148145875-a5aefaeb-8f00-4906-ad86-b6cc7c325b64.png)

**Comment by hjubb** [comment]
Thanks @stlsht. The translations are managed on crowdin, if there's a missing or incorrect translation for your locale and are able to contribute it or correct one that would be greatly appreciated! https://crowdin.com/project/session-android/
