### ISSUE TITLE
Unread message count reset to 0 by merely entering conversation.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-android#826]
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When entering a conversation with a lot of unread messages (i.e. more than can be displayed in a single screenful), the unread message counter of that conversation is reset to 0, even though many of those messages cannot have been read, because they have not yet appeared on-screen.

This is compounded by the inaccurate counter, which displays 99+ when there are more than 99 unread messages. This is not granular enough. Busy conversations, such as the official open groups, can reach this threshold in under an hour. A 3 or even 4 digit counter would be much more useful.

### Steps to reproduce
- Enter a conversation with 99+ messages. Do not scroll the conversation window.
- Exit the conversation.
- Observe that the unread message counter for that conversation has been reset.

**Actual result:**

The conversation's unread message counter has been reset.

**Expected result:**

The conversation's unread message counter should have been decremented by only the number of messages that appeared on-screen when the conversation was entered.

### Device info

**Session version:** 1.11.13

**Comment by fracting** [comment]
I can reproduced this bug in both the latest dev branch and the libsession-integration feature branch (9a7d3a45d7acd6ee1eae39bf45ff956c981fe371)

**Comment by fracting** [comment]
On iOS, unread count is not reset to 0 unless a user manually scroll down, I like the iOS behaviour.

**Comment by ianmacd** [comment]
> I can reproduced a related bug in the libsession-integration feature branch ([9a7d3a4](https://github.com/oxen-io/session-android/commit/9a7d3a45d7acd6ee1eae39bf45ff956c981fe371))
> 
> When joining a new Community using Android Session from the libsession-integration feature branch, it will pull the last 100 message, however, the unread message count of the Community thread reset to 0 immediately, this is a surprise to me.

This issue was also [referred to](https://github.com/oxen-io/session-android/issues/1148#issuecomment-1506134886) in the production release of 1.16.7.

Evidently, the bug has not been fixed after all.

**Comment by KeeJef** [comment]
This is resolved as of 1.17.0
