### ISSUE TITLE
Image viewer crashes as i try to zoom out past the threshold

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#831]
**Code of conduct

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The app crashes or resets back to the chat list when i move my fingers outwards even viewing a photo.

**To reproduce**

1. Go into any chat
2. Find a photo
3. View it and attempt to "zoom out"

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Galaxy S10
 - OS: Android 11
 - Version of Session; 1.12.0

**Additional context**

**Comment by pythonInRelay** [comment]
Try updating the app. 1.12 is pretty old.

**Comment by Flam3z** [comment]
Issue still occurs on 1.11.17

**Comment by Flam3z** [comment]
just an update 1.13.0 still has the issue, if more information is needed please let me know.

**Comment by KeeJef** [comment]
Unable to reproduce here

**Comment by KeeJef** [comment]
Do you have the image this is occurring with? and what is the device model?

**Comment by Flam3z** [comment]
> Do you have the image this is occurring with? and what is the device model?

Happens to any image and my device model is the same one i mads with the intial post.

**Comment by Flam3z** [comment]
Issue no longer persists
