### ISSUE TITLE
Notifications not going away when messages are seen on other devices

### ISSUE THREAD

**Issue by x80486** [oxen-io/session-android#832]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I have Session installed as a Desktop (Linux) application and on an Android device. Whenever I receive a notification and I open up the messages in the Desktop application, the mobile push notification doesn't go away — which is very confusing because it always look like I received new messages.

**To reproduce**

- Install Session (desktop) in Linux
- Install Session in an Android device
- Tell someone to send a message to you 😏

**Smartphone (please complete the following information):**

 - Device: `Google Pixel 4a (5G)`
 - OS: `Android 12`
 - Version of Session in mobile (or latest commit hash): `1.11.15 (2465)`
 - Version of Session in desktop (or latest commit hash): `1.7.6`

**Additional context**

It also happens the other way round. If I check on the mobile, whenever I open up the desktop application, I can still see the green vertical bar that states the messages haven't been read.

> I do use the `Fast Mode` for notifications on the mobile.

**Comment by hjubb** [comment]
Thanks for the issue. Out of curiosity does the message thread show as read in the application itself? I think there could be a potentially easy fix for this, will look into it :+1:

**Comment by x80486** [comment]
The message thread shows as unread (the green vertical bar on the left for that contact). It happens in both: mobile and desktop — in the sense that, when using the mobile, the issue is reflected on the desktop, and vice-versa.

**Comment by SingerGuy** [comment]
I am running Windows desktop 5.55.0 and Android 1.13.7 and this is still an issue. Expand the issue to me sending a message from Windows desktop and my Android gives me an alert that a new message has arrived, even though it was just me. I shouldn't get a notification on one device when I send a message from the other device.

**Comment by hjubb** [comment]
@SingerGuy the issue of getting notified for your own messages might be resolved in versions 1.14.0 and above

**Comment by x80486** [comment]
@hjubb, were you able to figure it out this one?
