### ISSUE TITLE
Letters are being cut off.

### ISSUE THREAD

**Issue by fightuntilwedie** [oxen-io/session-android#839]
Letters like "g" inside a contact's name are being cut off at the bottom of the name.
![session-attachment-2022-02-08-094642](https://user-images.githubusercontent.com/88578064/152963263-05428db1-2a11-4ed1-91c7-4b8b836863ab.jpeg)

**Comment by hjubb** [comment]
Thanks @fightuntilwedie is this in a specific section of the application? in the main list of conversations or in a specific conversation thread?

**Comment by fightuntilwedie** [comment]
@hjubb It's at the top of a conversation, next to the contact's profile picture.
