### ISSUE TITLE
Unread message counter has inadequate contrast in dark mode.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-android#844]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The unread message count doesn't provide enough of a visual cue to the user.

**Comment by KeeJef** [comment]
This has been implemented, unread message counter is now accent color
