### ISSUE TITLE
[Bug] "Enter Key Sends" doesn't seem to work

### ISSUE THREAD

**Issue by mystic-githuber** [oxen-io/session-android#846]
Version 1.11.17
Android 12

Turning on enter key to send a message doesn't seem to work.

**Comment by holequantum** [comment]
Same bug android 11 and android 10
Send when press enter does not do it pressing enter do nothing just adds enter does not send when will this big going to be fixed.

**Comment by KeeJef** [comment]
This seems to work for me, what Keyboard are you using?

**Comment by KeeJef** [comment]
Closed due to insufficient information
