### ISSUE TITLE
[Bug] audio call doesn't work in beta

### ISSUE THREAD

**Issue by cherifyass** [oxen-io/session-android#847]
**Describe the bug**

Voice and video call doesn't work.

**To reproduce**

1st attempt was from OPPO to Samsung: Samsung phone rang but after accepting the call, the screen remains stuck and no audio is heard.

2nd attempt was from Samsung to oppo : no ringing in OPPO and call fails or times out in Samsung phone.

**Screenshots or logs**

I have already sent the bug logs collected from the app by mail. Request number is 1860. 

**Smartphone:**

 - 1st Device: Samsung Galaxy S20 FE 5G
 - OS: Android 12
 - Version of Session : prelease 1.12.3

- 2nd Device: Oppo A15
 - OS: Android 10
 - Version of Session : prelease 1.12.3

**Comment by hjubb** [comment]
Is this still the case on the latest pre-release versions?

**Comment by cherifyass** [comment]
I have tested the latest pre-release and confirm its fixed!
Thanks for great work!

**Comment by hjubb** [comment]
Thanks, I'll close this issue!
