### ISSUE TITLE
Incorrect, negative new message counter and scroll button after deleting only message.

### ISSUE THREAD

**Issue by fatchan** [oxen-io/session-android#848]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When deleting the only message in a conversation, the message counter and arrow button to scroll will show "-1". Also the arrow button seems to be in a weird position when it shows "-1".

**To reproduce**

1. Open a conversation to a session ID you have no message history with.
2. Send any message.
3. Delete the message
4. Observe the message counter and arrow button. 

**Screenshots or logs**

Opening a fresh conversation:
![image](https://user-images.githubusercontent.com/18641559/154502883-814fc9fa-aebe-47bb-a96d-fe4a91014e4e.png)

Sending a message:
![image](https://user-images.githubusercontent.com/18641559/154502911-92be62f1-3aff-4918-9362-44cab3cee400.png)

After deleting that message:
![image](https://user-images.githubusercontent.com/18641559/154502960-ee40bd8b-7ebc-4af7-a967-5446d73f82c2.png)

**Smartphone (please complete the following information):**

 - OS: Android 11
 - Version 1.11.17

**Additional context**

Perhaps, this is the relevant code?
https://github.com/oxen-io/session-android/blob/a002e3e1f7592be5bce4e65a959321ae3d96197e/app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt#L758

unreadCount > 0 might be better, so that the indicator does not show negative numbers. And of course, figure out where the unreadCount gets set < 0. (I didn't dig too deep)

Thanks!

**Comment by hjubb** [comment]
Cheers for the issue, am able to reproduce easily. I'll fix this up :+1:

**Comment by hjubb** [comment]
I've got this fixed now, this behaviour was just UI, not a DB unread count being negative. In a `RecyclerView`'s `LayoutManager` when you call the `findFirstVisibleItemPosition` it will return the constant `RecyclerView.NO_POSITION` in the case where there are no items (now empty thread) which is in fact `-1` so just coercing that to be at least `0` should fix it in this circumstance :+1:
