### ISSUE TITLE
[Documentation] Add link to Session's github repo to the download page

### ISSUE THREAD

**Issue by Chief36** [oxen-io/session-android#849]
Users usually do not know if Session has an F-Droid repo and finding the link to it is not that easy. Adding the link to the downloads page will make it easier for new users to find it.

**Comment by hjubb** [comment]
Hey @Chief36 are you referring to the getsession website, or somewhere else?

**Comment by KeeJef** [comment]
Links to F-droid are on the Github page and the Session website now
