### ISSUE TITLE
New discovery: news but no notification 1

### ISSUE THREAD

**Issue by rrn21833** [oxen-io/session-android#859]
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by hjubb** [comment]
Would it be possible to get more information for this issue @rrn21833 ?

**Comment by stephen-a2z** [comment]
so did I. No notification on my mobile phone.

**Comment by KeeJef** [comment]
Closing due to lack of information
