### ISSUE TITLE
Deleting a message from both parties results in a crash.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#866]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Whenever I delete the final message from me and another user, it results in a crash nearly each time.

**To reproduce**

1. Open a dm with another user.
2. Send a message.
3. Delete the message for yourself and the other person.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung S10
 - OS: Android 12
 - Version of Session or latest commit hash: 1.11.20

**Additional context**

I'll provide any additional information if needed.

**Comment by hjubb** [comment]
Is this happening before the message has been sent? or after it's got the tick icon that it's been delivered?

**Comment by Flam3z** [comment]
After the tick icon.

**Comment by hjubb** [comment]
Thanks, I'll try to reproduce it. Is the message the only message in that conversation thread?

**Comment by Flam3z** [comment]
Yes. I tried it with 2 different users

**Comment by Flam3z** [comment]
issue still persists in 1.13.0, crashing seens to happen if the message i delete for both sides is the only message in our dm so it quickly takes me out then crashes.

**Comment by hjubb** [comment]
I think I've figured out the issue, thanks for the update. Will try to push this in a fix shortly

**Comment by hjubb** [comment]
This should be fixed now @Flam3z 
feel free to re-open and let me know if it's still an issue
