### ISSUE TITLE
Video calls, self viewer not mirrored. Very disorienting. 

### ISSUE THREAD

**Issue by Lucifer1903** [oxen-io/session-android#874]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Self video viewer is not mirrored, this is a standard feature of the majority of video caller apps and it is missing from Session which makes using video calls very disorienting. 

The easiest way to see the issue is by starting a video call, look at yourself in the corner self viewer, wink. It is disorienting because you expect the video to be mirrored but it is not. This also makes it difficult to centre the camera on your face as the camera moves in the opposite direction than expected. 

Note: when correcting this only the self veiw should be mirrored, the video that is sent to the other caller should stay un-mirrored. 

**To reproduce**

Call someone and share your video feed with them. 

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [Huawei mate 40 Pro]
 - OS: [Android 11]
 - Version of Session: 1.12.15 (2725)

**Additional context**

**Comment by hjubb** [comment]
Will fix this
