### ISSUE TITLE
Day theme selected message not seen

### ISSUE THREAD

**Issue by dsm** [oxen-io/session-android#875]
Hi, 

If select a message in chat screen using day theme don't recognise message is selected or not selected.

I assume night theme's select color black and day theme's select white may be change white is good for us. Grey or grey like color is better, thanks.

**Comment by KeeJef** [comment]
Is this still an issue? i believe we changed this to be far more visible, its now a light blue which i can distinguish fairly well

**Comment by dsm** [comment]
issue is fixed. themes are good now.
