### ISSUE TITLE
call run on  background for 2 hours

### ISSUE THREAD

**Issue by g1zza** [oxen-io/session-android#881]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g Realme ]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

call in background after iv hang up for 2 hours
was on.

**Comment by KeeJef** [comment]
Closing due to lack of information, please reopen with additional info
