### ISSUE TITLE
Have an option to route the calls through Bluetooth

### ISSUE THREAD

**Issue by x80486** [oxen-io/session-android#882]
**Code of Conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the Bug**

Not exactly a bug, but it would be great to have an option to route the calls to bluetooth as well — speaker and phone already works.

**To Reproduce**

Make an audio/video call; try to route the call to any of the connected device's bluetooth.

**Screenshots or Logs**

N/S

**Smartphone (please complete the following information):**

 - Device: Google Pixel 4a
 - OS: Android 12.x
 - Version of Session or latest commit hash: 1.11.20

**Additional Context**

N/A

**Comment by hjubb** [comment]
currently if you're on a call and have speakerphone off it will try to route the call over bluetooth as a priority, if you are toggling between speakerphone on and off it will also try to default to bluetooth if you currently have a headset connected. Making this a more explicit option to select / display a bluetooth output as an option might be a better option moving forward

**Comment by x80486** [comment]
I think that would be great: an explicit option.

The problem I'm facing is that it never routes to the Bluetooth, unless I start the call with the headset. If I start the call, and then connect the headset, it can't find it.

**Comment by bisoxfan** [comment]
I am experiencing the same issue as solinium. I can use my Bluetooth headset to listen to voice notes and/or record voice notes but even though my Bluetooth headset is connected when I start a call, the call does not come through the Bluetooth headset for some reason. I recently reinstalled Session but I don't think I had this issue before... I'm hoping this is just a glitch but if not, I'm hoping this can feature can be added, please. Thank you.
