### ISSUE TITLE
option to  able delete  call login on users

### ISSUE THREAD

**Issue by g1zza** [oxen-io/session-android#885]
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by hjubb** [comment]
Could I have more info for this?

**Comment by g1zza** [comment]
![Uploading IMG_20220521_205358.jpg…]()

**Comment by g1zza** [comment]
to be able to delete all calls in out,time changing  with users
