### ISSUE TITLE
Notification error same like arch desktop

### ISSUE THREAD

**Issue by RajrupDasid** [oxen-io/session-android#886]
Notification issue same like arch desktop zip client,
and I mentioned already in the desktop area but you need to recruit new admins for your official page because current admins has a very bad attitude to new people , not only they abuse me also my best friend.

of course after observing their behave I am sure that my issues going to remove but nothing to do, it's your platform oxen , do what ever you want , like assign some corporate dictator minded people on your official room is going to give you like this posts also.
FOSS software have dictator mentality , i dont think where it's going to end ?

**Comment by hjubb** [comment]
can you link the issue from desktop?

**Comment by hjubb** [comment]
Closing this for now, seems like it is related to a desktop issue. Feel free to re-open with any mobile specific errors and I can take a look at fixing it
