### ISSUE TITLE
Note to self doesn't allow attachments

### ISSUE THREAD

**Issue by sconim** [oxen-io/session-android#891]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Note to self doesn't allow adding any attachments.

**To reproduce:**

When trying to add any attachments (media, documents, GIF) by tapping the "plus" button on the bottom-left corner nothing happens. 

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung S20 - SM-G980F
 - OS: Android 10
 - Version of Session or latest commit hash: v. 1.13.0 (2785)

**Additional context**

**Comment by hjubb** [comment]
This will be fixed in the next version :+1:

**Comment by nahcos** [comment]
Now attachments can be added but cannot be opened (PDF, images, etc.). The attachment can only be deleted, nothing else - which is pretty useless. Please fix!

**Comment by hjubb** [comment]
I'll look further into it, it could be a case of the attachment downloading but not having any useful progress indication. Does the attachment allow saving after a time or are even older attachments you have seen for a while still like this?

**Comment by nahcos** [comment]
All attachments are like this.

Sincerely,
Cosmin N.

**Comment by sconim** [comment]
Attachments can now be added BUT cannot be accessed. A ticket flagging this misbehavior is already open.
