### ISSUE TITLE
I'm receiving notification old messages I sent and received 1 month ago

### ISSUE THREAD

**Issue by Gaotu07** [oxen-io/session-android#893]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I woke up today and I am receiving too many notifications from my conversations that have been deleted automatically (I use the 30min limit for conversations usually).

I joined the chat options and confined to 200 the conversation limit and then to 10 in order to delete all, because ALL messages were coming back, as if someone had invaded and restored a backup of my conversations ... how is this possible?  why this happens?

**Screenshots or logs**

![Screenshot_20220519-101939_WhatsApp](https://user-images.githubusercontent.com/104527432/169317369-a4e3c3ae-5df3-4acd-b410-4c7e031065c2.jpg)

 - Device: Galaxy S21 Ultra
 - OS: last
 - 1.13.0(2785)

**Comment by hjubb** [comment]
See #888, I will close this as a duplicate
