### ISSUE TITLE
No more notifications since update to v1.13.4.

### ISSUE THREAD

**Issue by fightuntilwedie** [oxen-io/session-android#901]
While messages are being transmitted we don't get notifications anymore since we updated on 2 devices with unofficial LineageOS 19.1 (Android 12). We use the APK version and updated manually. There are no notification sounds, dots, pop-ups anymore.

**Comment by fightuntilwedie** [comment]
Would like to mention that we are using microG 0.2.24.214816 (latest version) for FCM push notifications. Session is still registered on both devices and everything worked flawlessly before the latest update.

**Comment by githupper** [comment]
No notifications as well on my GOS Pixel 6XL. No Play services but app has been to have unrestricted background access which worked for other apps like Signal and Telegram. 

Hence issue is purely on Session's side

**Comment by fightuntilwedie** [comment]
In the meantime I'm back to v1.13.1 via F-Droid where it's the latest and recommended version. Same with Google PlayStore on a Stock ROM device.

**Comment by hjubb** [comment]
Hey, I've got a new version coming that should fix this and #909, let me know if this is fixed now for you all on 1.13.6

**Comment by fightuntilwedie** [comment]
And since the new version is already on PlayStore: My StockAndroid device also notifys reliably again. Great job!!!
