### ISSUE TITLE
[Feature] changing messages background color

### ISSUE THREAD

**Issue by mkoushan** [oxen-io/session-android#902]
The deafault color of messeages are really bright and it hurts my eyes. It will be nice if you add something to change them.

**Comment by x80486** [comment]
Indeed. I think it's about time `Session` introduces themes — or a similar concept.

**Comment by jonas-w** [comment]
Agreed, i love the dark theme except this bright green color.

**Comment by KeeJef** [comment]
This is complete as part of themeing
