### ISSUE TITLE
No more notifications since update to v1.13.5.

### ISSUE THREAD

**Issue by fightuntilwedie** [oxen-io/session-android#909]
One and the same problem as here: https://github.com/oxen-io/session-android/issues/901

2 Samsung S7 with unofficial LineageOS and microG 0.2.24.214816 (latest version). No more notifications also on a stock Android device (Samsung Tablet) with Android 8.

Everything worked flawlessly on all devices up to v1.13.1.

**Comment by hjubb** [comment]
Hey, this should be fixed in a version coming out very shortly, let me know @fightuntilwedie

**Comment by blackburnman04** [comment]
I'm running Xiaomi 10T Lite with LineageOS 19.1 and microG 0.2.24.214816 (latest version) and notifications are working for me again in v1.13.6.

Thanks for fixing @hjubb
