### ISSUE TITLE
[Feature Request] Add a feature to backup secret key Google Drive. So, android users can easily login after changing the device.

### ISSUE THREAD

**Issue by ZishanAdThandar** [oxen-io/session-android#911]
Add a feature to backup secret key to Google Drive. So, android users can easily login after changing the device.

**Comment by Andser99** [comment]
This sounds like terrible opsec and would inadvertently open many amateur users to private information leaks, why would you want to store your secret key with google specifically? They have the worst reputation when it comes to user privacy and google drive is proprietary so you can't trust them they won't sell your keys to official authorities in case something happens.

**Comment by moeindev** [comment]
I agree @Andser99, @ZishanAdThandar Securing the recovery passphrase is user's responsibility and this feature request is not valid... Maybe integrating with other authentication apps would be good if users want extra steps for securing their accounts.

**Comment by KeeJef** [comment]
I think we should offer additional backup options for the recovery phrase, but i don't think we would want to encourage users to store it on a cloud service which is not really designed for storing passwords/secret info. Could be cool to integrate more easily with password management applications though (Lastpass, 1password, Keepass etc..). Closing for now
