### ISSUE TITLE
[Feature Request] Add emoji reactions to messages

### ISSUE THREAD

**Issue by SisyphusRising** [oxen-io/session-android#917]
Add emoji reactions to messages (similar to Element, Discord, or Telegram). Instead of each person replying with a gigantic emoji in response to a message, just add the ability to respond to the message itself with a mini version of the emoji appended to it. Declutters chat space, visually consolidates everything, and simplifies emoji responses.

**Comment by Para-lyzed** [comment]
I was looking through the pull requests and just wanted to let you know that is looks like this has already been a work in progress feature, and it will be implemented with #889. I wanted to let you know that since there hasn't been a reply to this issue yet.

**Comment by hjubb** [comment]
This one is merged now and should be available! Sorry for the late reply
