### ISSUE TITLE
Android phone permissions

### ISSUE THREAD

**Issue by zcyph** [oxen-io/session-android#918]
Opening issue for this as there have been repeated discussions about it in the Session group chats on Telegram and Session. The official Android builds for Session require phone permissions, which allow apps to determine phone number and device IDs. The concern expressed by community members is that this poses a privacy and metadata risk.

During these discussions, somebody pointed out that the phone permission is required to make calls. However, I was able to successfully place calls with both the official Session build with phone permission disabled, and with the unofficial F-Droid build which does not include the phone permission requirement.

There is some discussion here: https://discuss.techlore.tech/t/session-now-requires-phone-id/395/7

Which suggests the permissions are there so that Session may detect whether another call is already in progress.

There appears to be significant demand for an official Session build in the official F-Droid repo that does not contain the phone permission and other things like the Google Firebase components.

Please consider! Thanks everyone for all your hard work on this project. :)

**Comment by hjubb** [comment]
Thanks @zcyph, looking at removing this now after it came to my attention

**Comment by hjubb** [comment]
This should be removed now in 1.13.7
