### ISSUE TITLE
Session over scrcpy shows only as black screen

### ISSUE THREAD

**Issue by chrisamow** [oxen-io/session-android#931]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Running session messenger shows a black screen over scrcpy.  This does not happen for any other app that I'm aware of.

**To reproduce**

Connect to android phone via scrcpy
Start Session
(opposite order also shows the same)

**Screenshots or logs**

Screenshot attached.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
Pixel 4XL

 - OS: [e.g. Android Pie]
Graphene (i.e. Android 12)

 - Version of Session or latest commit hash
Session fdroid 1.13.6

**Additional context**

scrcpy 1.24
![session_on_scrcpy](https://user-images.githubusercontent.com/5819969/180325220-e5b88f97-9e13-412a-81d9-88c81b2a58dc.png)

host machine is ubuntu 20.04

**Comment by hjubb** [comment]
Hey @chrisamow this is due to the default "screen security" which you can disable if you'd like under the `Privacy` category of the in-app settings. By default it is enabled to prevent screen recorders or screenshots from capturing the app content

**Comment by hjubb** [comment]
Closing, if this still is an issue feel free to re-open
