### ISSUE TITLE
When I use recovery phrase on new device all  my messages and my contact messages reappear again!

### ISSUE THREAD

**Issue by Gaotu07** [oxen-io/session-android#934]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When I use recovery phrase on new device or switch device, all message's deleted by auto delete mode are back again, my messages and my contact messages. That is, if someone puts the recovery phrase on a new device, the messages I thought would be deleted will reappear, including photos, videos, voice messages, etc. If bandits or the police or oppressive government of a country have access to my device, where the Session password is mandatory the password of the device, will my messages and the people I mentioned are compromised? Where is the much-publicized privacy of this app? You user want to check? Take new device and put your recovery phrase and you will see all your old message's again!! That's terrible!

**To reproduce**

Take new session installation and put recovery phrase. Done. All your secure messages will appear again and you fuck**.

**Screenshots or logs**

**Smartphone (please complete the following information):**

 - Device: iPhone 13 Pro Max
 - OS: 15.6
 - Version of Session or latest commit hash: 1.13

**Comment by session11** [comment]
I feel that people at Session needs to understand that if a user is enabling "disappearing messages", that means he/she wants those messages to disappear, forever, without any chance of retrieval. Disappearing Messages must not be saved anywhere, even on the server. Ideally, "pass phrase" should retrieve only those messages/chats, where "disappearing messages" has not been enabled. I hope development team will consider this request.

**Comment by lungdoge** [comment]
Hey @session11, thanks for your report. 

What you are describing is actually the expected behaviour, currently. It has to do with the messages time-to-live (TTL). You can learn more about disappearing messages, TTL and restoring your account via the seed phrases [here](https://sessionapp.zendesk.com/hc/en-us/articles/4416517720985-Why-do-disappearing-messages-reappear-after-restoring-my-Session-ID-). 

We do have future plans to change this behaviour so that the TTL of a message also takes into consideration any disappearing message timer set. We don't yet have an exact date on when this will be completed, but it's certainly on the roadmap. 

Thanks for your support!

**Comment by Gaotu07** [comment]
Ok thank you for explaining, sure this is very important to user privacy.

**Comment by easthvan** [comment]
> Hey @Gaotu07, thanks for your report.
> 
> What you are describing is actually the expected behaviour, currently. It has to do with the message's time-to-live (TTL). You can learn more about disappearing messages, TTL and restoring your account via the seed phrases [here](https://sessionapp.zendesk.com/hc/en-us/articles/4416517720985-Why-do-disappearing-messages-reappear-after-restoring-my-Session-ID-).
> 
> We do have future plans to change this behaviour so that the TTL of a message also takes into consideration any disappearing message timer set. We don't yet have an exact date on when this will be completed, but it's certainly on the roadmap.
> 
> Thanks for your support!

Hi, 

How is it now in 2024? What is the current TTL and can the user change the TTL on server? 

And did you solve that if user manually deletes message OR the TTL expires OR the disappearing timer expires than the message to be insta deleted (secure wiped if on HDD and not in STP RAM)?

**Comment by KeeJef** [comment]
As of today, users cannot modify the TTL of messages stored in their swarm. However, we are very close to completing our update on Disappearing Messages. This will enable users to choose between two modes: 'Disappear After Send,' which modifies the TTL of the outgoing message, and 'Disappear After Read,' which alters the TTL once the message is read.

Once implemented, if the TTL or the Disappearing Message timer expires, the message will be removed both locally and remotely from the swarm. This ensures that it is not restored when recovering or linking a device.
