### ISSUE TITLE
Feature request and some bugs: Session really misses some features, and has some serious bugs.

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#937]
1 - Change the record button into an input menu. That way session can prevent accidental voice recordings.

2 - Making Able to remove your profile picture.

3 - Make delete for me and for everyone button at least more separated + make it able to remember the action.

4 - Make able to delete opponents message in pm.

5 - Make able to switch notifications to only me mention + set it as default in settings, to not get bombarded by notifications.

6 - Delete all messages from yourself button in channels.

7 - No spam ID Like in tox messenger.

8 - Selecting files or pictures from android document provider.

9 - Add picture in picture mode for videos

10 - Add music selection gallery, like in telegram

11 - Bug: after pressing delete your whole session account, session keeps the cache data. You can see it in app info.

**Comment by KeeJef** [comment]
Many of these issues are duplicates of previous or ongoing issues, please check for duplicates and reopen these as individual issues for easier tracking. Closing for now
