### ISSUE TITLE
Big issue: unable to receive new messages

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#938]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I am unable to recieve any new open group messages after updating to the latest version at this time.

**To reproduce**

Update to 1.14 and have android 12
**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Galaxy S10
 - OS: Android 12
 - Version of Session or latest commit hash: 2925

**Additional context**

**Comment by insolublegreen** [comment]
yep same issue sending messages to open groups works fine. but i don't recieve any.
can session please implement beta releases before pushing updates often feels like there is not testing of these updates.

**Comment by Flam3z** [comment]
Bug fixed in 1.14.1, thx team for quick fix <3
