### ISSUE TITLE
Implement passphrase Independent from device unlock

### ISSUE THREAD

**Issue by lshw42** [oxen-io/session-android#94]
**Describe the bug**
In case the access to the session app is restricted the android screen lock is used as passphrase.

**To reproduce**
1. Open Session app
2. Go to privacy settings
3. Enable access restriction using screen lock/fingerprint
4. Close Session app
5. Open Session app (may be wait a while)
6. Enter android screen lock code / use fingerprint

**Smartphone:**
 - Device: Fairphone 2
 - OS: Android 7.1.2
 - Version of Loki Messenger: 1.0.1

**Additional context**
Signal used an independend passphrase to secure the app until it removed this feature in 2018 (couldn't find the correct version-no, sorry). In fact, that the usage of the android screen lock code or fingerprint isn't a best practice to secure a messenger app and it is comparable simple to overcome this access restriction (more easily when fingerprint is used), it should be removed and a independend passphrase should introduced.

**Comment by KeeJef** [comment]
Closing this for #424
