### ISSUE TITLE
[BUG] Setting `Notification_Settings.Mentions` for open groups doesn't get saved

### ISSUE THREAD

**Issue by LeoMeinel** [oxen-io/session-android#945]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Setting `Notification_Settings.Mentions` for open groups doesn't get saved.
Meaning that after some time (probably after the app is restarted) you will get all the notifications from Open groups.
After updating, the notifications will also be reset to all.

**To reproduce**

1. Install Session 1.14.1 from F-Droid
2. Join an Open group
3. Set Notification Settings to Mentions
4. Wait some time, maybe killing the app is also enough.
5. After restarting the app, you get notifications for everything.

**Smartphone (please complete the following information):**

 - Device: OnePlus 9 Pro
 - OS: Android 12
 - Session: 1.14.1

**Comment by hjubb** [comment]
Currently looking at this

**Comment by hjubb** [comment]
Do you have multiple devices that are linked to the same account out of curiousity?

**Comment by LeoMeinel** [comment]
No, the device specified is the only device linked to that account.
Thanks for looking into this that fast!

**Comment by hjubb** [comment]
I think we'll post a new version soon to see if it's related to some people experiencing issues with multiple open groups syncing from linked devices, might have fixed something accidentally in that branch but it is very difficult to reproduce and I only saw it a few times in the version before those fixes :thinking: but I'll keep track of it if it still persists after that version to see if there's anything else that might be causing it

**Comment by LeoMeinel** [comment]
Perfect! I'll try to keep you updated if the issue persists on my device when a new version is released.

**Comment by zcyph** [comment]
I have same issue on OnePlus 3T + LineageOS, and I do use Linux desktop client as well.

I deleted Session account from Android client + did "Clear All Data - Entire Account" from desktop client.

Waited some time, then restored account from desktop client, confirmed everything was wiped out, starting fresh. I then restored account on Android. I then re-joined open groups from desktop client. They then automatically re-appear on Android client within subsequent seconds/minutes.

Unfortunately within short time, notifications settings on Android continue being reset. This behavior never happened for me prior to the recent updates.

**Comment by hjubb** [comment]
Thanks all, will keep trying to track down this issue and find a fix, at least it is semi-reproducible

**Comment by zcyph** [comment]
> Thanks all, will keep trying to track down this issue and find a fix, at least it is semi-reproducible

fyi, after updating to 1.15.1 today, i still have same issue

**Comment by LeoMeinel** [comment]
> > Thanks all, will keep trying to track down this issue and find a fix, at least it is semi-reproducible
> 
> fyi, after updating to 1.15.1 today, i still have same issue

I am pretty sure that the issue is fixed for me. I'm not 100% certain but my settings got saved for at least some groups after the update.

**Comment by LeoMeinel** [comment]
Okay, actually it definetly isn't. All groups but one just stopped syncing since Tuesday :D
Seems to be a new issue. I may create one later, but it may also be just specific for my device since I haven't found anyone else mention it

**Comment by hjubb** [comment]
There is a potential fix in the works that we are just testing to make sure the settings stay persistent (as you can imagine testing is a bit of a headache when the bug has only presented itself sometimes after several days or weird interaction behaviour). But that should be available soon! Hope to fix this once and for all then

**Comment by LeoMeinel** [comment]
Hello,
I am pretty sure that it is actually not fixed.
At least for me most groups started to reset the setting again.
Seems like I misjudged it being fixed.

**Comment by hjubb** [comment]
Are you running 1.15.3? It seems to be fixed for a lot of people using this version. It may require you to set it once again after updating

**Comment by LeoMeinel** [comment]
Okay, it's my fault. I didn't check if it was already added to 1.15.2..
Thanks a lot for the fix! 1.15.3 works flawlessly :)

**Comment by hjubb** [comment]
All good, understandable the merge and state change happened before the release was built and released so I understand why it was confusing
