### ISSUE TITLE
Deleting messages doesn't work 

### ISSUE THREAD

**Issue by mubali1987** [oxen-io/session-android#946]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
Deleting messages doesn't work anymore for me
direct messages are not deleted for the 2 users
I'm on android

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by hjubb** [comment]
Could I get some more information for this issue? Are you referring to not being prompted to delete a message? Is this in a 1 on 1 conversation? Is it related to expiring messages? Is it related to unsending messages? Are all devices on the same platform and version?

**Comment by mubali1987** [comment]
yea 1 conversation against 1 conversation. yes message deleted. yea Windows desktop device android

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KeeJef** [comment]
Is this still occurring? are you using the option to "Delete just for me" or "Delete for me and x" what is the behavior that indicates that a message is not being correctly deleted?

**Comment by KeeJef** [comment]
Closing due to lack of info
