### ISSUE TITLE
When I am in a chat and the other person is typing, the typing indicator causes a message received alert

### ISSUE THREAD

**Issue by SingerGuy** [oxen-io/session-android#950]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When I am in a chat with another person and they start typing, the • • • bullet typing indicator appears, causing the Android client to give a message received alert. If they pause typing and the indicator goes away, the instant they resume typing the indicator returns and another message alert is generated. I have had dozens of alerts while my friend is typing a lengthy reply and pausing to collect their thoughts. It is extremely annoying. I have to leave Session altogether and then launch when there is an actual message received.

**To reproduce**

Be in a chat with another person. Watch them start typing. Listen for the alert. Rinse. Repeat.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S9
 - OS: Android 8.0.0
 - Version of Session 1.13.7

**Additional context**

**Comment by hjubb** [comment]
Thanks, this one should be fixed soon however in the meantime I think you can disable the in-chat notifications and it should remove this issue. A more permanent fix will be incoming
