### ISSUE TITLE
Verifying signatures instructions give 404

### ISSUE THREAD

**Issue by katelynsills** [oxen-io/session-android#955]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Starting with 1.11.0 and onward, the instructions in Step 2 of [Verifying Signatures](https://github.com/oxen-io/session-android#verifying-signatures) give a 404 rather than signatures.asc. 

The signatures can still be found in the [Release Notes](https://github.com/oxen-io/session-android/releases/tag/1.11.0), though, so I suspect one solution is just updating the instructions. 

**To reproduce**

Visit [https://github.com/oxen-io/session-android/releases/download/1.11.0/signatures.asc](https://github.com/oxen-io/session-android/releases/download/1.11.0/signatures.asc)

**Comment by hjubb** [comment]
Thanks for the info, will try to get this updated

**Comment by hjubb** [comment]
The latest release (`1.15.1`) should contain the appropriate .asc files and we will include them again going forward. Thanks for the heads up!
