### ISSUE TITLE
Possible to support push notifications by supporting ntfy?

### ISSUE THREAD

**Issue by githupper** [oxen-io/session-android#956]
Code of conduct

[x]  I have read and agree to adhere to the Code of Conduct

As topic.

Current choice only support Google or the 15min scheduled check which is not customizable. Having an open source push notification service will helps.

Ntfy is currently in use with many Matrix clients.

Would appreciate the team at least give ntfy a bit of consideration 

Thanks

**Comment by Para-lyzed** [comment]
Closely related to (but not a duplicate of) #924

**Comment by githupper** [comment]
Having an open source push notification service is more efficient than one that uses polling but yes, having a persistent notification much like Signal's or Telegram FOSS will help to alleviate the current slow/late rate too.

**Comment by githupper** [comment]
Realized #558 already referenced the same issue with UnifiedPush since 2021. Not hopeful but keeping my hopes up for this to take place soon. Closing this ticket
