### ISSUE TITLE
[Feature Request] Changing contact nick for our view

### ISSUE THREAD

**Issue by Yonle** [oxen-io/session-android#963]
Say, We have our Session Contact to our mother/father. So we want to give the contact nick as "Dad" or "Mom" instead of their real name.

**Comment by hjubb** [comment]
Currently if you long press the contact in the main screen and then tap `Details` you can tap their profile name and set a local nickname to display on your device! Let me know if this helps!

**Comment by hjubb** [comment]
Good point, I'll see if we can add it in there as well
