### ISSUE TITLE
In app discoverability of Communities / Open groups

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#971]
Make available public group urls, so you can make it directly from the app session network and not in separate server

**Comment by hjubb** [comment]
I'm not too sure if this one is related to just creating open groups through the app, which is a feature that will be built in the future or related to deep-linking which is probably a shorter term goal to support many session specific links opening directly in app across all the platforms. Might need more info on this one

**Comment by Yonle** [comment]
I think i have a idea for public group.

Instead of URL, We can make it work like how Session UID work, Like this:

```
Group ID: ld81840bs42lfb9173638n31l13b04
```

So, We can just paste the Group ID to join the group, But it would also good to make it possible to regenerate GID.

**Comment by KeeJef** [comment]
Closing for discussion here https://github.com/oxen-io/session-desktop/discussions/2268
