### ISSUE TITLE
Chat roulette + with tags like omegle

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#972]
Make able to participate in random pm chat mode by your choice, so when you turn that on session automatically registers your id into random chat, so it can pair the registered IDs, so you can talk to random people, also with your favorite topics with tags. Or when you leave random chat, session again automatically deletes your id from random chat database.

**Comment by hjubb** [comment]
This is probably an idea for an extension to something like the [session open group server](https://github.com/oxen-io/session-pysogs) that someone could implement there without needing to modify the clients to support it. I don't think at this stage such a feature would be coming to the clients in the near future.
