### ISSUE TITLE
Audio Duration bug

### ISSUE THREAD

**Issue by Yonle** [oxen-io/session-android#983]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

![Screenshot_2022_0928_213144.png](https://user-images.githubusercontent.com/63401712/192816378-92b77ace-2282-4d95-9a53-adb9bc6239e9.png)

**To reproduce**

Just upload 3 minutes long audio file.

**Smartphone (please complete the following information):**

 - Device: Vivo 1820
 - OS: Android 8.1
 - Version of Session: 1.15.4 (3035)

**Comment by hjubb** [comment]
I think this is fixed in #948 , I'll aim to get that merged for next release

**Comment by KeeJef** [comment]
Closing as i'm assuming this is now fixed, please reopen if this is still an issue
