### ISSUE TITLE
Green stuff

### ISSUE THREAD

**Issue by Yonle** [oxen-io/session-android#984]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

What are those green thingy?
![Screenshot_2022_0929_005427.png](https://user-images.githubusercontent.com/63401712/192854446-3b38b895-0560-454a-92ab-54f3fb7ccd05.png)

**To reproduce**

Switch to night mode & relaunch the app.

**Smartphone (please complete the following information):**

 - Device: Vivo 1820
 - OS: Android 8.1
 - Version of Session: 1.15.4 (3035)

**Comment by hjubb** [comment]
This is definitely unintended behaviour :+1: 
I'll take a look at what's happening here, currently working on theming stuff but this looks like what I've seen when I use an emulator and the main view gets selected by some kind of element selector like a hardware keyboard or accessibility control. Are you running anything like that on the device?

**Comment by Yonle** [comment]
> This is definitely unintended behaviour :+1: 
> I'll take a look at what's happening here, currently working on theming stuff but this looks like what I've seen when I use an emulator and the main view gets selected by some kind of element selector like a hardware keyboard or accessibility control. Are you running anything like that on the device?

I run in normal device without external hardware

**Comment by hjubb** [comment]
This is currently happening consistently every time you are on the home screen in the app?

**Comment by Yonle** [comment]
> This is currently happening consistently every time you are on the home screen in the app?

Not every time, It appears in random time.

**Comment by hjubb** [comment]
Thanks, I will look further into it. The upcoming theming changes may prevent something like this from happening in the future as well so it might be fixed after the next release anyway :+1:

**Comment by KeeJef** [comment]
is this still occurring?

**Comment by Yonle** [comment]
Rarely occurs. Closing
