### ISSUE TITLE
[Feature Request] Adaptive themed icon support

### ISSUE THREAD

**Issue by PhaserArray** [oxen-io/session-android#987]
This feature is already present in the Signal app, it would be nice if Session supported the [adaptive themed icons feature.](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) 

(Apologies if this is a duplicate or already planned, i did a quick search and didn't see anything)

**Comment by PhaserArray** [comment]
Relevant pull request #1037

**Comment by KeeJef** [comment]
This is now complete
