### ISSUE TITLE
Readme.md in main branch

### ISSUE THREAD

**Issue by shosseini811** [oxen-io/session-android#988]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Is readme updated in main branch? Went through all the steps but it did not work.
Do I need to use latest release version?

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by hjubb** [comment]
Which part of the readme is this in reference to? I'll get it updated if something is out of date

**Comment by KeeJef** [comment]
Closed due to lack of information
