### ISSUE TITLE
Can't Copy User ID in Closed Groups

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#995]
Try to long press on user message and copy ID, and nothing is copied to the clipboard. See attached video

Android 10
Session 1.15.2

https://user-images.githubusercontent.com/1575546/193987245-05414922-145c-48a1-b811-d4f9176de8d7.mp4

**Comment by KeeJef** [comment]
This will be fixed in a release coming in the next few days

**Comment by KeeJef** [comment]
This has been fixed
